### ISSUE TITLE
Triangle madness

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#1008]
All the red error boxes now have triangle madness

![image](https://user-images.githubusercontent.com/6563663/142681438-57727eed-6d87-4e22-b6f2-267491ec0d78.png)

**Comment by aloverso** [comment]
@aaronvux @skeeJay heads up, moved this into the current sprint, that ok?

**Comment by aaronvux** [comment]
Yup.

**Comment by aaronvux** [comment]
this looks good to me
