### ISSUE TITLE
Netlify User Authentication

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1018]
As a Netlify user, I need to be able to securely access the Navigator Netlify instance so I can have confidence unauthorized users are not making updates that have not been approved.

## Acceptance criteria

- Able to login into Netlify with Github account.
- Able to post content from Netlify to the Navigator repo with Github account.

## Notes

- [ ] PO Approval
- [ ] UX Review

**Comment by dsueltenfuss** [comment]
Added the Netlify GitHub add-on. Need to work with Dave Cole to see if we can tighten the permissions around it.
