### ISSUE TITLE
Industry Picker - Add Synonyms 

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#1035]
We should add options synonyms to the industry object 
So that the new industry picker can be filtered by additional terms

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review
For the initial implementation, I added the following additional search terms
* car - will display Auto-Body Repair
* ecommerce - will display E-Commerce

**Comment by aaronvux** [comment]
Looks good.  Moving to staging.
