### ISSUE TITLE
Content: For Business Formation

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1045]
Create content for the business formation screen.

[X] identify what content needs to be created

Develop contextual information:
[ ] Official Formation Document
[ ] "certified copy" what is it? and what is the benefit of getting it?

**Comment by CeciliaRam** [comment]
Certificate of Formation:
https://github.com/newjersey/navigator.business.nj.gov/blob/main/content/src/display-content/contextual-information/certificate-formation.md
Certified Copy:
https://github.com/newjersey/navigator.business.nj.gov/blob/main/content/src/display-content/contextual-information/certified-copy.md

**Comment by Jesslax** [comment]
@CeciliaRam I think we need to say Certified Copy of what. It's the Certified Copy of the Certificate of Formation, right? I would rename the title of this one to "Certified Copy of Certificate of Formation" and edit the first sentence to "A certified copy of the Certificate of Formation... " Or is this a definition for all certified copies?

Has Don reviewed the copy for both of these?

**Comment by CeciliaRam** [comment]
@Jesslax, left the content without specification to give us the possibility to also use the contextual information in other instances where certified documents are an option.
Thoughts? can change if we don't wanna go in that direction.

**Comment by Jesslax** [comment]
@CeciliaRam I am open to that, let's just check in with Don, because I don't know what other certified documents are offered and if a universal definition is plausible.
