### ISSUE TITLE
UX Enhancement - Headings

### ISSUE THREAD

**Issue by fiorella-io** [newjersey/navigator.business.nj.gov#1065]
## Acceptance criteria

 Onboarding
- "Tell Us About Your Business"  (Bold, 32px)
- "Location" (Bold, 22px)
- "Home-based business?" (Bold 16px)
- Adjust font weight for "(Optional)" to regular (300) -> Certifications
- Adjust font weight for (Steps N of X) to regular (300) -> Heading
- Adjust font weight for (If you have one) to regular (300) -> Entity Id
![image](https://user-images.githubusercontent.com/91498500/144510198-d1da12c2-d89c-4394-a1e3-1bc76571f9d0.png)

https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?page-id=6025%3A108014&node-id=6029%3A111003&scaling=scale-down&starting-point-node-id=6029%3A110425

**Comment by FarazA22** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@FarazA22 this looks good except for this:
Adjust font weight for "(Optional)" to regular (300)

It's still showing as 400 when I look in the inspector.

**Comment by FarazA22** [comment]
@aaronvux mhmm, can we jump on a call, I've set it to 300 and i appears as 300 within my browser/inspector.

<img width="1250" alt="Screen Shot 2022-01-05 at 9 36 56 AM" src="https://user-images.githubusercontent.com/72581979/148235354-ad8f4b75-7f25-422e-a901-6d197edf8a34.png">

**Comment by FarazA22** [comment]
@fiorella-io QQ, the regular font weight for USWDS is 400; font-weight of 300 is considered light. Should the '(Optional)' font-weight be 300 or 400 (it's currently 400 in figma). Also, should the font-weight for '(Steps x of x)' be 300 or 400 (it's currently 400 in figma)?

Note: In dev, optional is currently set at 300, Steps is current set at 400.

**Comment by FarazA22** [comment]
@aaronvux @fiorella-io I made all the updates. The font-size changes are also reflected on the profile page.

**Comment by fiorella-io** [comment]
@FarazA22 Looks good. Thanks, Faraz!
