### ISSUE TITLE
Business Formation V2 (LLC)

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1072]
As Poppy, I need to have a simple and intuitive experience when submitting my business's formation information through the Navigator so that I don't have to use the State's website.

## Acceptance criteria

- Separate the single form design into 3 steps (Business, Contacts, Payment)
- Validations will fire on each page before a user will be allowed to move onto another page.
-- Display validation message below the Business Name field if it is not populated.
- Users will navigate between pages with a primary button and secondary back button.
- No change to API errors.

## Design
**Prototype**
https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?page-id=6474%3A158222&node-id=6474%3A160334&viewport=389%2C48%2C0.02&scaling=min-zoom&starting-point-node-id=6474%3A160334

**Designs**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6474%3A158222

## Additional Acceptance Criteria
- Follows Design
- Works in Mobile
- 508 Compliant

## Notes

- [x] UX Review
- [x] PO Approval

**Comment by aaronvux** [comment]
@fiorella-io Business Formation MVP Design implementation story.

**Comment by aaronvux** [comment]
Capture and store business formation date once the user is issued their entity ID.

**Comment by aaronvux** [comment]
Create new story for API Error.

**Comment by aaronvux** [comment]
Might need to repoint to include updates to payment page.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
@FarazA22 I'm not seeing separated steps in dev.  I tried in cognito and still not seeing it.

**Comment by aaronvux** [comment]
@FarazA22 the validations are not firing on the individual steps.  I can move forward with the incorrect zip codes and I don't see the error until the final step.

**Comment by fiorella-io** [comment]
@FarazA22 Styling Issues I noticed:

Step 1
1. Add new content paragraph before "Business Name and Legal Structure"
2. Adjust Business Name and Legal Structure into a gray div
![image](https://user-images.githubusercontent.com/91498500/149401465-0696a198-a21b-4e59-b1e1-031ca67c3afd.png)
3. Add hr divider before Location heading and Registered Agent
4. Adjust the spacing between input fields. There's more space between "Address Line 1" and "Line 2" vs "State" and "Zip Code" (preferred spacing)
5. City, State, and Zip Code should be in one line
![image](https://user-images.githubusercontent.com/91498500/149401172-7a3efb1c-3a5c-4fe3-b014-7aacd5977582.png)
6. For Registered agent, adjust description copy and change "Registered Agent Number" to "Registered Agent ID Number"
7. For "Manually Identify Registered Agent" there are two checkboxes that are missing

Step 2

8. Make sure the delete icon aligns to the left of the input field
![image](https://user-images.githubusercontent.com/91498500/149403507-fd956668-3397-4659-9838-01d17d1161bd.png)
9. Add New Signer needs to be underlined and adjust the plus icon to be centered 
![image](https://user-images.githubusercontent.com/91498500/149403707-8b9cff42-ff71-4903-8171-5ea8b0067a43.png)
![image](https://user-images.githubusercontent.com/91498500/149403864-317a75f9-ec8a-4838-8e86-f29d9dc8a69c.png)

Last Step
10. Reduce spacing between F Name, L Name, and phone. It should be 20px 
11. First Name and Last Name should be in one line
12. For Notifications, remove the Learn More links for both checkboxes listed

Global
13. Back button should have a white background #FFF 
14. Change H3 font-weight to 400

**Comment by FarazA22** [comment]
@aaronvux I believe I addressed the autofill issue. Can you try again. If the data is preloaded, try clearing the address within the autofill dropdown and setting it again. I've also added the scroll to the top. 

All other styling issues will need to be noted within a separate ticket.

**Comment by aaronvux** [comment]
@kmelefsky We need to discuss on Tuesday the API validation UX with EJ and Jess for 16th minute.

**Comment by aaronvux** [comment]
Tasks button will be removed only the Business Formation pages.  The Successfully submitted page will be removed so testing can continue after the form is submitted.  All other design issues will be moved into a separate story.

**Comment by FarazA22** [comment]
@aaronvux  Task button and successfully submitted page are removed.

**Comment by Jesslax** [comment]
My review:
1. The line spacing is not consistent throughout, for example, the spacing between the two address fields is different from the spacing between NJ State and Zipcode fields. I think the latter spacing is the right one @fiorella-io 
2. How can I review all the error message copy?
3. Where can we edit this copy, and should we do that now or later? I would do it later if Dev plans to make more copy edits/additions from Figma.
4. My last name was not auto-populated in the "last name" field, I believe it should auto-populate from login info
5. Once a person clicks "Start Forming My Business" should the status change to "in-progress" (not to say that they could not change it back themselves too)
6. The dependency box should only display on the first screen
7. Believe there are a few other designs feature still to come?

**Comment by fiorella-io** [comment]
@aaronvux 
Regarding 1. That's correct. I had mentioned it earlier. We should match the spacing between State and Zipcode throughout the form

**Comment by FarazA22** [comment]
@aaronvux The dependency alert will now only display on the first tab.

**Comment by aaronvux** [comment]
EJ and Jess agreed we should remove the API error after the user leaves the page and new error message will display on submit.

For Jess's other notes:
1. Design ticket will be created for spacing.
2 & 3.  @FarazA22 can you help Jess locate these files please?
4. Need to investigate this.  I am unable to reproduce it.
5. Status update is a separate story and needs to be discussed again.
6. Fixed.
7. There are other stories.

@kmelefsky tagging for visibility.

**Comment by FarazA22** [comment]
@Jesslax the file path to the markdown files is here:
navigator.business.nj.gov/content/src/display-content/business-formation/

the file path to the default text file is here:
navigator.business.nj.gov/web/src/display-defaults/roadmap/business-formation/

**Comment by FarazA22** [comment]
@aaronvux implemented fix to hide alert when submit page is revisited

**Comment by aaronvux** [comment]
Getting a response error.   When I leave the page and come back it's still there.

**Comment by aaronvux** [comment]
Working now.  Moving to staging.
