### ISSUE TITLE
Unable to update task status in production

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1080]
Successfully updated task status within task:
![image](https://user-images.githubusercontent.com/62653834/144106676-53b709d8-48dc-4784-8266-40877e7c8107.png)

Return to roadmap, and task status has reset to "Not Completed"

After trying this 3 more times, the updated task status is finally visible in the task and the main roadmap.

**Comment by carye3** [comment]
@dsueltenfuss @FarazA22

**Comment by dsueltenfuss** [comment]
Fixed in #976
