### ISSUE TITLE
Create Pharmacy Permitting Page

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1082]
As Poppy,  I need access to a Pharmacy specific Permitting Page in the Navigator so I can easily ensure I have all the necessary items completed in order to submit my application.

## Acceptance criteria

- Create Checklist of items necessary to submit Pharmacy license application for the new tasks below
- Replicate design & functionality of Cosmetology license

**Prepare for Pharmacy Requirements**
- Dependency: None
- Content 
-- The State regulates pharmacies for the safety of workers and customers. To help guide pharmacies on rules they have created a handbook.
-- This document contains critical information on:
-- Permit application and renewal process
-- Shop requirements (Design, Appliances, and Library)
-- Requirements of the Pharmacist-In-Charge and Other Personnel
- CTA: Read the Pharmacy Rules 
- CTA Link: https://www.njconsumeraffairs.gov/regulations/Chapter-39-State-Board-of-Pharmacy.pdf
**Apply for a Pharmacy Permit (step 5c) Screen 1**
- Dependency: ["obtain-site-safety-permits"]
- Content
-- The New Jersey Board of Pharmacy requires that new shops, relocated shops, or shops that have transferred 100% of the ownership obtain a permit with the New Jersey Division of Consumer Affairs. After you submit your application it will be reviewed, and your site will be inspected. Your site should be operation ready when you do your site inspection. Once a permit is issued, your pharmacy must open within 90 days and notify the Board in writing of the date the business opens.
-- To complete this application, you must have:
--- Pharmacy Name (This is usually your registered businesses name)
--- Have your name registered with the county clerk
--- Names and addresses of registered agent (c-corps only)
--- Names and addresses of all officers and owners of 10% or more of stock (c-corps only)
--- Registered pharmacists name, hours of work, an certificate #
--- Name and contact of unregistered employees
--- Pharmacist in-charge
--- Copy of prescription and poison label
--- Business Address
--- Hours of operation
--- Floor dimensions of Pharmacy Shop dimensions (height x width)
--- Floor dimensions of Prescription department (height x width)
--- Pharmacy counter dimensions (height x width)
--- Possessed or ordered required pharmacy equipment and references
--- Picture of any exterior signage (if it is available at the time they submit the application)
--- Site inspection date
-- After you complete this task, you will have:
--- An  issue permit # 
--- A pharmacy permit
- CTA 1: Apply for My Permit with the Division of Consumer Affairs
- CTA 2: I Submitted My Application Check My Application Status

**LICENSE STATUS CHECK**
- Display Check Status Tab on Apply for Pharmacy License Tab

**Apply for a Pharmacy Permit (step 5c) Screen 2**
- Content
-- After you’ve applied for your permit, input the information from your application below to get automatic updates about your application here in your roadmap.
- Fields
-- Business Name - auto fill from profile
-- Business Address Line 1 
-- Business Address Line 2 (Optional)
-- ZIP Code 
-- State (Drop down)​
- CTA: Submit
-- If application is not found, error message: Your application has not been received or entered into the system yet. It takes at least 10 days from submission date.

**Apply for a Pharmacy Permit (step 5c) If application is found, Screen 3**
 
- Registered pharmacist in charge
- Notarized Application
- Application Fee
- Inspection : <Can we get the date the inspection is scheduled for?>
-- Tip: Business are often told if anything is missing during their inspection. If something is missing, you can send a photo of the adjustment made to meet code.
- Inspection Report Created
-- Tip: Allow 30 days from inspection for report creation and review.
- Board Review of Inspection Report
- Passed Inspection
- Board Approval
- For all fields except “Inspection” options are:
-- Checked =Show: “Completed”
-- Unchecked = Show: “Information Not Reviewed Yet”
-- Incomplete = Show: “Missing Information”

## Standard Acceptance Criteria

- Works in Mobile
- Follows Design
- 508 Compliant

## Standard Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant
- Feature Flag?

## Design
TBD

## Notes
- [ ] UX Review
- [ ] Content Approval
- [ ] PO Approval

**Comment by aaronvux** [comment]
@Jesslax going to put this under a feature flag for now until the Boomi issue is resolved.

**Comment by Jesslax** [comment]
ok

**Comment by aaronvux** [comment]
@Jesslax this can be reviewed, but the Boomi issue has not been resolved so you won't get any results on the license search.  The feature flag will hide this in Prod until we get the Boomi issued fixed.

**Comment by aloverso** [comment]
remove feature flag
