### ISSUE TITLE
Allow Checkboxes in Content on Cannabis Task Screens, All Consumer Affairs License Task Screens

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1083]
As Poppy, I need to see checkboxes on my License Task Screen in the Navigator so that I can track the steps I need to submit my license application.

## Acceptance Criteria
- Display registration modal window when the user tries to check a checkbox on the task screens below if they are in Guest mode.  Checkbox will not be checked. 
- Add checkboxes to License Task screens: Cosmetology, Home Improvement, Pharmacy, Massage, Accounting Task "Start Application" tab in the Navigator
- Add checkbox capability to three (3) cannabis Task screens: annual license Task, conditional permit Task, and conversion license Task
- Save the state of the checkboxes within the session and between sessions when the user is logged in.
- Wipe any enabled checkboxes if the Industry is changed by the user.

## Standard Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10164%3A183294

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux when the acceptance criteria says "Wipe any enabled checkboxes if the license is changed by the user." - by "license changed" does that mean when industry changes?

**Comment by aloverso** [comment]
@aaronvux @Jesslax  will the checkboxes editable in guest mode? and if so, is it correct that they should be reset when a guest-mode user changes their industry, also?

**Comment by aaronvux** [comment]
@aloverso let's discuss at story writing

**Comment by aloverso** [comment]
@aaronvux this will be ready for review once Jess adds some checklist content to some tasks, right now the code is ready but no tasks yet has checklists

@Jesslax to add checkboxes, make a bullet list with square brackets `[]` and then, directly after, use curly braces `{}` to write out a unique ID for that item. We will use this id to remember whether that checkbox is checked for a user even if the copy for it changes. I recommend something using the task ID combined with the list item, since multiple tasks should not reuse the same ID.

Here's an example:

```
- []{cannabis-conversion-list} text with `contextual info|some-id-here`
- []{evaluate-your-location-item-2} another one with **bold**
```

Here's some examples of some common mistakes or pitfalls to avoid, these WON'T work:
- forgetting the ID: `- [] some text here`
- forgetting the space between `-` and `[]`: `-[]{id-here} text`
- adding a space between the `[]` and the id: `- [] {id-here} text`
- putting a space inside the brackets: `- [ ]{id-here} text`

**Comment by Jesslax** [comment]
thanks @CeciliaRam fyi

**Comment by Jesslax** [comment]
@dsueltenfuss I tried this out for "Apply for a Massage Therapy License" once it moves to dev I will double-check it worked. That said, the preview in netlify does not yet support this feature, would be good to add.

**Comment by aaronvux** [comment]
@Jesslax sounds like you'd like a story to preview checkboxes in Netlify correct?

**Comment by dsueltenfuss** [comment]
@Jesslax The page wasn't previewing due to errors with how the checkboxes were setup. I've fixed them, and it should render now.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please review

**Comment by aaronvux** [comment]
@mikewolfd  @dsueltenfuss does this have to be enabled in Netlify to see it in dev?  I'm not seeing this yet for the Cannabis screens.  Tried incongito as well.

**Comment by fiorella-io** [comment]
I don't see the checkboxes on dev
![image](https://user-images.githubusercontent.com/91498500/160932319-691ebafa-93dd-4a3c-8374-846ea9bb6c51.png)

**Comment by dsueltenfuss** [comment]
@Jesslax needs to set it up for each task. So far, she has only done it for the Massage Therapy license task

**Comment by aaronvux** [comment]
@dsueltenfuss I was under the impression from the AC that the setup would be done as a part of this ticket.

**Comment by aaronvux** [comment]
@fiorella-io @carye3 @Jesslax Looks good.  Please review.

**Comment by dsueltenfuss** [comment]
@aaronvux I'm just going off of this comment Anne made: https://github.com/newjersey/navigator.business.nj.gov/issues/1083#issuecomment-1079426533

**Comment by fiorella-io** [comment]
@dsueltenfuss I noticed a few things:

- When I use the "tab" button and then I want to select a checkbox using the "enter" key it doesn't work. 
- For some reason, every time I click on each checkbox, there is this blue highlight that appears over the green highlight in the tabs. Can we remove that?
![image](https://user-images.githubusercontent.com/91498500/161071126-a4ff5e41-6330-4206-847f-1b0fc5a7ad51.png)
- For contextual links, every word should be highlighted, not just the last line. 
![image](https://user-images.githubusercontent.com/91498500/161071654-74d16219-05d6-49dd-ab7b-b0ca5a85a26c.png)

**Comment by mikewolfd** [comment]
@fiorella-io I can fix the first one. The other two are existing bugs which we should create tickets for

**Comment by aaronvux** [comment]
@CeciliaRam @Jesslax State of the checkboxes are being saved successfully.  We need another industry to test if the checkboxes wipe when the industry is changed.

**Comment by mikewolfd** [comment]
@fiorella-io @aaronvux 
So I looked into it, and ended up refactoring the tab components entirely for accessibility reasons. 

It works and looks better.

A couple of things, though: 

- According to accessibility guidelines, native checkboxes should only be checked by pressing space, not enter. Using enter on checkboxes is an anti-pattern 
- The new tab component we're using has a slightly different tab-highlighting-style (bottom vs top), I could try to change it, but that would require more time. If it's an issue, create a new ticket for that.

**Comment by fiorella-io** [comment]
@mikewolfd Thank you! 
- It works by clicking on the spacebar. 
- For the tab component, I've added it to our dev/design pairing ticket.

**Comment by Jesslax** [comment]
@mikewolfd @aaronvux I created checkboxes for Cannabis annual license task screen. Needs to be pushed to dev so you can try it out Aaron. Also can confirm need a tkt to improve the preview layout for this feature in netlify. If you can add please.

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for testing on dev. As @Jesslax mentioned, its for the Annual Cannibas license type.

**Comment by aaronvux** [comment]
@fiorella-io @carye3 please approve if you're good.  It looks good to me.
