### ISSUE TITLE
Add Inspection Date to Pharmacy and Cosmetology Licenses

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1084]
As Poppy, I need to be able to see my site inspection date for my Pharmacy or Cosmetology license so I can keep track of when my inspection will take place or has taken place when I check my license status.

## Acceptance criteria
- Add Inspection Date as a returned list item after a request for the license status has been submitted.
- Inspection Date not set:
- Inspection Date set, but not completed
- Inspection Date set and completed.

## Standard Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@aloverso  Check with Cheryl at Consumer affairs if Inspection Date can be returned with the license status response.

**Comment by aloverso** [comment]
@aaronvux no, it is not: https://njcio.slack.com/archives/CQNBLAZ41/p1639593911415800
