### ISSUE TITLE
Design s-corp onboarding and profile

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1095]
s-corp is a legal structure type that only c-corps can apply for. If a business wants to be an s-corp we would display 2 additional tasks in step 3 of their roadmap.

We would also want the user to be able to edit their s-corp status in their profile.

[Onboarding Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7246%3A169371)

**Comment by carye3** [comment]
@Jesslax so looking it up briefly, it looks like first you must become an LLC as a business entity, and then you can ADD a tax classification of S-Corp or C-Corp on top of that LLC.... is that right?

**Comment by Jesslax** [comment]
@carye3 cc: @carye3 First you become and C-corp, and then you have the option to add S-corp. If you want to become an s-corp, there are two additional filings you need to do after you do the c-corp filing. From Don, we recently learned that businesses usually know straight away that they want to be an s-corp. The question is: What is the best way to discern if the user needs the additional s-corp tasks? Previously we discussed a few ideas: 1. Having an s-corp option in the legal structure screen of onboarding 2. If a user selects c-corp in onboarding, following up with a question on if they want to be s-corp. 3. Having a post onboarding question in the roadmap after they select c-corp. After learning from Don that most businesses know straight away they want to be s-corp, we may just want to go with option 1, which would not require additional design.

**Comment by Jesslax** [comment]
@carye3 @CeciliaRam also I think this is important information C found, that we should include to help guide the user selecting s-corp: 
To qualify for S corporation status, the corporation must meet the following requirements:
- Be a domestic corporation
- Have only allowable shareholders
- May be: individuals, certain trusts, and estates
- May not be: partnerships, corporations or non-resident alien shareholders
- Have no more than 100 shareholders
- Have only one class of stock
- Must be an eligible corporation (some financial institutions, insurance companies, and domestic international sales corporations are not eligible).
