### ISSUE TITLE
Add Members to Business Formation (LLC)

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1123]
As Poppy, I need the ability to add members to my business formation application so that my legal documents accurately reflect the members of my LLC.

## Acceptance criteria

- Add Members Section to Contacts Section of Business Formation
-- Content:  Complete this if you are a multi-member LLC
-- Content: List the LLC's members and the street address of each. You may list up to 10 members.  Members’ names are listed on the Certificate of Formation and will have the ability to file and sign documents. 
-- Table: Name, Street, Action (horizontally scrollable in mobile)
--- Content: No members have been added (default, display member info once it has been added)
-- Add New Member Link
--- Clicking the link will open a modal window displaying:
---- Checkbox: The Name and Address is the same as the registered agent
----- Clicking this checkbox auto-populates the fields with the registered agent information.
---- Full Name (required)
---- Address Line 1 (required)
---- Address Line 2 
---- City (required)
---- State (required)
---- Zip Code (required)
--- Close Icon and Cancel Button
---- Closes the modal window without saving
--- Add Member button
---- Clicking the button adds the information to the Members Table
-- Display Success Message (current design)
-- Edit icon next to each row
--- Clicking the edit icon opens the populated modal window where the user can make changes.
-- Delete icon next to each row
--- Clicking the delete icon removes the member from the table and success message is displayed.

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6904%3A161583

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@Jesslax please review and approve content prior to sprint planning for this story.

**Comment by fiorella-io** [comment]
Hi, @mikewolfd please adjust the following:

1. "Members" should be H3.
2. In the table, "Action" should be "Actions"
3. Can we underline "Add New Member"
4. In the modal, "Address line 2 should have the "(Optional)" label
5. **BUG:** When I successfully enter a member, and then I go back to edit and delete let's say the city, and I click on "Cancel". When I go back and click on the edit button again, the modal is empty. 
6. If I add the same member twice, with an identical address, are we throwing an error when the click on "Continue"?

**Comment by Jesslax** [comment]
Hi,

I think this should read "Address" and not "Street"
 The following letter is missing in this copy: "Complete this if you are **a** multi-member LLC"

@fiorella-io 
1. Should "Name? be left aligned
2. Should the city, state and zip code automatically display on a 2nd line to organize that information more easily?
3. If no member is added, is the user automatically added as a member?  For the purposes of the Navigator, we assume our user is the businesses owner, and so the account holder will always be a member, but there may be other additional members they want to add. Did we consider automatically adding the owner as a member or passing through that information? I don't recall where this landed. I know this field isn't required, but wondering if I should check this with NICUSA?

**Comment by mikewolfd** [comment]
@Jesslax 

I fixed the address/street thing, and the copy issue.

"Name" is currently left aligned with the name text, do you mean with the border?

**Comment by mikewolfd** [comment]
Pushed my changes

**Comment by Jesslax** [comment]
I meant the Name header should be left-aligned with the copy above it.

**Comment by fiorella-io** [comment]
@mikewolfd @Jesslax since the name is inside a table, the table has padding to distinguish that it is a table. I think it's ok if it's not aligned to the text above it. 

For 2) we can adjust and have the city, state and zipcode all in one row to match the address format everywhere else
![image](https://user-images.githubusercontent.com/91498500/150869903-aee93363-251d-4377-bf0f-44a56f4de718.png)

**Comment by Jesslax** [comment]
@fiorella-io I do not see an outline of a table, just seems to be incorrectly aligned. 
![image](https://user-images.githubusercontent.com/78366346/150870498-d0d67ae9-5f52-4530-ba6c-fb405203be39.png)

**Comment by fiorella-io** [comment]
@Jesslax I see what you mean. Which browser are you using?
I'm using Chrome and this is what I see. We need to make sure the table is consistent on all browsers. 
![image](https://user-images.githubusercontent.com/91498500/150870730-074b889c-2358-450b-a855-26387e668322.png)

**Comment by Jesslax** [comment]
@fiorella-io ah, that makes sense, I use Firefox.

**Comment by aaronvux** [comment]
@fiorella-io any design issues left for the Members section?  It looks good to me.

**Comment by fiorella-io** [comment]
@aaronvux @mikewolfd I'm still experiencing the following bug:
When I successfully enter a member, and then I go back to edit and delete a field, let's say the city, and I click on "Cancel". When I go back and click on the edit button again, the modal is empty.

**Comment by aaronvux** [comment]
@mikewolfd I am able to reproduce the bug Fiorella is experiencing.

**Comment by kmelefsky** [comment]
next steps - taking a look at bug today

**Comment by aaronvux** [comment]
This is working for me now. @fiorella-io please check and let me know if we are good to move this story to staging.

**Comment by fiorella-io** [comment]
@aaronvux Everything looks good, thanks @mikewolfd!

**Comment by aaronvux** [comment]
Moving outstanding UI issue to the UI ticket.  Ticket is moving to staging.
