### ISSUE TITLE
Google Analytics receiving incorrect event when "Form My Business" green button clicked

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1169]
Clicking the Form My Business button is capturing the incorrect event.

The correct event should be: primary_call_to_action.

## Notes

- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux What event is it currently sending for that button?

**Comment by aaronvux** [comment]
Looks like it is sending two.  External link is incorrect.
<img width="557" alt="Screen Shot 2022-01-12 at 10 58 20 AM" src="https://user-images.githubusercontent.com/36163601/149175614-cb638eae-b68d-413b-9da5-77b8ba3719d6.png">

**Comment by mikewolfd** [comment]
This already seems to have been corrected?
