### ISSUE TITLE
Legal Structure dropdown in Profile displays markdown content within placeholder label

### ISSUE THREAD

**Issue by FarazA22** [newjersey/navigator.business.nj.gov#1188]
**Current Behavior:**

When a user navigates to the Profile Menu. Given that the legal structure is not set. The placeholder label for the Legal Structure dropdown displays markdown content.

**Expected Behavior:**

The dropdown should display the placeholder text if the legal structure is not set by the user.

**Steps to Reproduce:**
1. Log-in to system as a user that does not have Legal Structure set
2. Navigate to the Profile page

Additional fix layout of the dropdown, its width is larger then the other input fields.

<img width="991" alt="Screen Shot 2021-12-17 at 9 46 00 AM" src="https://user-images.githubusercontent.com/72581979/146564783-2ad369c6-0a87-4148-ac68-cef85b0b7dad.png">

<img width="904" alt="Screen Shot 2021-12-17 at 9 46 29 AM" src="https://user-images.githubusercontent.com/72581979/146564788-4e17dc09-b3e3-473c-89ed-dd9c277efdac.png">

**Comment by dsueltenfuss** [comment]
@aaronvux: This issue has been corrected, but is also no longer possible now that legal structure is required

**Comment by aaronvux** [comment]
Thanks!
