### ISSUE TITLE
Add Review Section to Business Formation V2

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1200]
As Poppy, I need the ability to review the information I am submitting to form my business so that I can ensure everything is accurate before making a payment.

## Acceptance criteria

- Add review section as the third step in the Business Formation workflow.
- Each section will have an edit link that will navigate the user to the appropriate page to update the information in that section.
- If a Registered Agent # is entered display:
-- Agent #
- If a Registered Agent is manually entered display:
-- Name, Agent Email, Address
- If Members were not added, do not show the Members section.

## Standard Acceptance Criteria
- Follows Design
- Works in Mobile
- 508 Compliant

## Design

Desktop:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6693%3A148227

Mobile:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7156%3A192250

## Notes

- [x] UX Review
- [ ] PO Approval
- [ ] Content Approval

**Comment by FarazA22** [comment]
@fiorella-io @carye3 @aaronvux In mobile, the contextual info link is missing, but is present in the desktop. Is this by design?
<img width="336" alt="Screen Shot 2022-01-21 at 10 19 47 AM" src="https://user-images.githubusercontent.com/72581979/150552282-4756b234-5473-4982-b9b5-e331467216d2.png">
<img width="359" alt="Screen Shot 2022-01-21 at 10 21 11 AM" src="https://user-images.githubusercontent.com/72581979/150552510-f55fee41-47d7-48f1-806d-79e89e63ed21.png">


mobile - https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7156%3A192250

desktop - https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6693%3A148227

**Comment by FarazA22** [comment]
@aaronvux Can you confirm if the 'learn more' contextual info link points to an existing markdown file (i.e. there is a contextual link that appears in the onboarding flow when the user is selecting their structure) or would we be displaying new content.


<img width="317" alt="Screen Shot 2022-01-21 at 11 03 55 AM" src="https://user-images.githubusercontent.com/72581979/150559741-4f328939-4241-4cbf-8334-cb2bd642e255.png">
.

**Comment by FarazA22** [comment]
@aaronvux when the registered agent number is selected, the AC states we should display the No., Name, and Address. Can you clarify which name and address we are displaying. Note: when registered agent number is selected, we only send the number via the api. When manual entry is selected, we send the email, name, and location. - see images below. 

<img width="222" alt="Screen Shot 2022-01-21 at 2 44 05 PM" src="https://user-images.githubusercontent.com/72581979/150590512-82044660-6425-49bf-8186-6f03d9af7f14.png">

<img width="312" alt="Screen Shot 2022-01-21 at 2 49 46 PM" src="https://user-images.githubusercontent.com/72581979/150591228-d7288f05-5613-4358-aa4c-abc50efdcfdc.png">

**Comment by aaronvux** [comment]
You're right Faraz.  For now just display the Registered Agent Number.  In the future, hopefully we can return their info based on the number.

**Comment by aaronvux** [comment]
The styling should be consistent between mobile and desktop. @fiorella-io please update the designs.

**Comment by fiorella-io** [comment]
@FarazA22 The "Learn More" should also appear in the mobile designs (Designs are fixed). Regarding content, what we have now in the Onboarding/Profile legal structure contextual info should be the same. 
Can we add # F7F7F7 as a new color in our design system so we don't have a contrast issue?

**Comment by FarazA22** [comment]
@fiorella-io changing the background color to #F7F7F7 does not address the contrast issue. I've made a note within the dev/design sync ticket. We can address it outside this ticket.

<img width="1323" alt="Screen Shot 2022-01-24 at 2 55 37 PM" src="https://user-images.githubusercontent.com/72581979/150854911-f360ffce-adae-4de1-8b27-004062e0c0d2.png">

**Comment by fiorella-io** [comment]
@FarazA22 Let's discuss this on our dev/design sync.

**Comment by FarazA22** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@FarazA22 Two things I'm seeing.

1. There's a "0" in the above Signatures if no Member has been added.
2. The styling of the section headers are not bold in the design.

<img width="644" alt="Screen Shot 2022-01-26 at 10 52 59 AM" src="https://user-images.githubusercontent.com/36163601/151198018-29064281-f29a-4658-8e44-264e548fa61d.png">

**Comment by fiorella-io** [comment]
@aaronvux @FarazA22 
When clicking on the Location and Registered Agent "Edit" link, can we have them jump to that section? Right now it takes me to the top of step 1 but I have to scroll to find it.

**Comment by FarazA22** [comment]
@fiorella-io @aaronvux The scrolling/jumping to specific section is doable. Can we create a new story for this change.

**Comment by aaronvux** [comment]
Moving outstanding UI issue to the UI ticket.  Ticket is moving to staging.
