### ISSUE TITLE
UX Improvements in Business Formation V2

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1202]
As Poppy, I need to have an intuitive experience while forming my business so that I can easily complete the form and obtain my formation documents.

## Acceptance criteria
- Add omitted content
- Save state of the form when navigating to the Profile to update information then coming back.
- No ability to save changes to form / return to it later
- Task status doesn't update automatically (revisit this topic)
- Integrate Google Maps/Mapbox/etc into Address info input

## Notes

- [ ] UX Review
- [ ] PO Approval
- [ ] Content Approval

**Comment by aaronvux** [comment]
@Jesslax @skeeJay We need to discuss if we need add anything around how we capture name information to auto-populate the form.

**Comment by aaronvux** [comment]
@Jesslax @skeeJay I think we should close this story.  We can decide if we want to automatically update the status for the user and add Google Maps as separate stories.

**Comment by skeeJay** [comment]
@aaronvux I'd agree. This is currently vague as a collection; they're best as separate improvements if we still want them.
