### ISSUE TITLE
Implement Clickable Stepper in Business Formation Workflow

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1203]
As Poppy, I need the ability to navigate between steps in the Business Formation workflow so that I can easily view information I have completed and need to still complete.

## Acceptance criteria

- Add the visual stepper to Business Formation.
- Clicking each step will navigate the user to the corresponding page.
- Display the Snackbar Validation Error anytime the user tries to navigate to a new step when page validations are failing
- Do not allow users to skip steps before all page validations are passing.
-- You must complete Step 1 - Business before proceeding.
-- You must complete Step 2 - Contacts before proceeding.
-- You must complete Step 3 - Payments

## Design

Desktop:
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=6601%3A147611

Mobile:
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=7116%3A167824

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by skeeJay** [comment]
@aaronvux We should move this to icebox, probably, since we haven't decided to move forward at all with it, right? It will also be reassessed/redesigned in the future, post-name search merge, as discussed today.
