### ISSUE TITLE
Merge Business Name Check as New Step in Business Formation Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1204]
As Poppy, I need to understand if my Business Name is still available when I am forming my business so that I don't get frustrated during the process.

## Acceptance criteria
- Add New "Name" Step to Stepper
- Create input field for Business Name
- Clicking Check Availability or using Enter on the keyboard will call the Business Name API to check that the user's business name is available.
  - If the user changes the Business Name after a successful result is returned, do not display continue button. The user must check availability again.
- Display Success message if Business Name is available
  - Display Continue button
  - Display copy that the name is not official until formation is complete.
  - Link to Profile to update the business name.
- Display Warning message with unavailable Business Names if unsuccessful.
- Remove Business Name search task from the roadmap & dependencies for LLC.
- Move "Check Available Names and Form Your Business" task to the first task in the Start step in the roadmap and mini- roadmap.

## Analytics
- Add:  business_formation_name_step_continue_button/click/go_to_next_formation_step
- Add:  business_formation_name_step_update_name_on_roadmap/click/update_name_on_roadmap
- Copy: task_business_name_check_availability/submit/view_business_name_availability

## Design

**Desktop**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9157%3A228708

**Mobile**
*Note: DO NOT use content from mobile design; use desktop copy instead*
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9157%3A229401

## Notes

- [ ] UX Review
- [ ] PO Approval
- [ ] Content Review

**Comment by aaronvux** [comment]
Double check design to make sure Update Name on your roadmap with this one link is available.

**Comment by aaronvux** [comment]
Splitting 
**UI**
- Decrease field the height of all input fields to match button height****

**Comment by namanaman** [comment]
@carye3 @fiorella-io In this design compared to the existing business search task, there are differences in the error/success state styles. Do we want to also apply this new error/success state styling to the existing business search task? 

This will help plan how much code the two name checks (in business formation and separate task) should share.

**Comment by aaronvux** [comment]
the designs for this ticket are specific to the LLC Business Formation and nothing should change for the other business name search functionality for the other legal structures.

**Comment by namanaman** [comment]
@Jesslax @CeciliaRam Will you be adding the new content for this to the repo or should I? (not sure what the process has been in the past)

**Comment by Jesslax** [comment]
Hi @namanaman The copy on the figma file is accurate. We now update the copy on the figma files so that when you all build it for the first time copy has been considered. (Not sure what you mean by adding new content)

**Comment by namanaman** [comment]
@Jesslax Oh I had meant adding the new content files to our code via Netlify

**Comment by Jesslax** [comment]
@namanaman since this is a unique design you're building for the first time, dev usually pulls the copy from figma, and if I have copy edits I made them after. Adding @aloverso who knows best about procedures here.

**Comment by aloverso** [comment]
@namanaman yes, for any new files and content necessary for the story, we as devs create everything as part of the development of the story and fill the content in with anything from the figma. And Jess/Ce can make edits after the fact if they choose. This way, delivering the story isn't blocked or dependent on the content team

**Comment by namanaman** [comment]
@Jesslax @aloverso Okay gotcha, thanks!

**Comment by namanaman** [comment]
@aaronvux Can be reviewed now

**Comment by aaronvux** [comment]
@namanaman can you remove the success message as well if the user changes their input value before continuing?

**Comment by aaronvux** [comment]
@Jesslax @skeeJay This feels weird to me that there is a link to update their profile after a successful search.  If I don't click the update link and move forward, it is displaying the name I searched with, but not "Updating" my profile until after the formation is complete.  I'd propose removing the link and just updating the profile when the user moves to the next page.  That way, they will consistently see the same name.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please review.

**Comment by namanaman** [comment]
@aaronvux Updated the success message logic

**Comment by aaronvux** [comment]
@namanaman looks good!  Thank you!

**Comment by aaronvux** [comment]
@namanaman is it possible to disable the autofill on the field?

**Comment by namanaman** [comment]
@aaronvux Yep that's easy to change. Is that something we want for this ticket?

**Comment by aaronvux** [comment]
@namanaman if it can be done with this ticket, great. If not, no big deal.  The autofill in chrome is showing when I try to do another search in the field and it's weird

**Comment by namanaman** [comment]
@aaronvux Turned off autocomplete

**Comment by aaronvux** [comment]
Moving to deploy
