### ISSUE TITLE
Success Page in Business Formation V2

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1205]
As Poppy, I need the ability to view a page that indicates my payment was processed and displays accompanying information so that I know I have completed the Business Formation process successfully.

## Acceptance criteria
- After payment and a success response is returned from the API, return the user to the Success page in the Navigator.
- Mark the Form Your Business Entity task as Completed.
- Content:
-- Hooray
-- You have successfully form your business entity!
-- Below is a list of document(s) from this transaction that you can click and download for <Transaction Date + 30 days>.
-- MM/DD/YYYY format
- Only display documents that are returned by the API with download icons.
- Clicking the icon or text will download the document to the user's device.
- Display Entity ID
-- Save the Entity ID to the user's profile and disable editing. 
- Display the Confirmation ID. 

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6474%3A159729

## Additional Acceptance Criteria:
- Follows Design
- Works in Mobile
- 508 Compliant

## Notes
- [x] UX Review
- [x] PO Approval
- [x] Content Approval

**Comment by aaronvux** [comment]
This work should be linked to a new story from the Discovery board ticket #1277.

**Comment by aaronvux** [comment]
@Jesslax @skeeJay Should Entity ID be editable after the successful formation of the business?

**Comment by Jesslax** [comment]
No. Once they submit their form via the API, and we get the Entity ID we should auto-input that into the profile and lock it. In the future, we can explore letting them make an amendment to their filing via our platform, but I do not think this a common need.

**Comment by aaronvux** [comment]
After I get to the NIC payment page, if I click cancel, I'm sent to the Treasury website.  Do we need to ask NIC if the user can be redirected back to the Navigator if they enter via our site?

**Comment by aloverso** [comment]
@aaronvux ready for review!

**Comment by aaronvux** [comment]
@aloverso I'm not able to download the formation document on the success page.
![Screen Shot 2022-01-25 at 10 16 32 AM](https://user-images.githubusercontent.com/36163601/151004348-aa8a6200-0bd0-46f2-96ab-a2832e121b72.png)

**Comment by aloverso** [comment]
@aaronvux I sent an email to NICUSA to ask them to address this

**Comment by aaronvux** [comment]
I can get it to download if I click the link directly in the inspect tool.

**Comment by fiorella-io** [comment]
@aloverso For "You have successfully formed your business entity and reserved your business name!" can we keep the font size to 16px/1rem, and bold the date. Everything else looks great. Thanks!

**Comment by aaronvux** [comment]
Showed @aloverso an issue that once my Entity ID was populated, the tax calendar wasn't pulling it correctly and was allowing me to input a new value, which then updated in my profile, creating a mismatch between what the state issued me and my profile.

**Comment by kmelefsky** [comment]
nest steps - complete issue Fiorella mentioned above and review issue that came up if we will be creating a new bug or fix the issue to decide if we're pushing as is

**Comment by aloverso** [comment]
@fiorella-io @aaronvux made the styling fix, this story should be all set

**Comment by aaronvux** [comment]
Moving to staging!
