### ISSUE TITLE
OIT Firewall Update - Newsletter & User Research Opt-Outs

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1281]
This ticket is to track the OIT Firewall Update in order for the Newsletter and User Research Opt-Out work that was previously completed to be live in production.

**Comment by dsueltenfuss** [comment]
Request was submitted to OIT on 12/22/21 - REQ0048737

**Comment by dsueltenfuss** [comment]
Firewall rules have been updated, and @mikewolfd was able to successfully test in production.
