### ISSUE TITLE
Design Oscar MVP & Gather Team Feedback

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1296]

**Comment by aaronvux** [comment]
@carye3 Can this one be moved to done or are you still using it to track the design for the next design review?

**Comment by carye3** [comment]
Let's keep it @aaronvux for the design reviews in this sprint

**Comment by kmelefsky** [comment]
@carye3 is this good to close out now that we're at the end of the sprint? thx!
