### ISSUE TITLE
Google Analytics  - Business Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1306]
As an Office of Innovation team member, I need to include Business Formation in Google Analytics so I can track metrics successfully.

## Acceptance criteria

**Business**
- business_formation_business_name_edit/click/go_to_profile_screen
- business_formation_legal_structure_edit/click/go_to_profile_screen 
- business_formation_business_step_continue_button/click/go_to_next_formation_step

**Contacts**
- business_formation_contacts_step_continue_button/click/go_to_next_formation_step

**Review**
- business_formation_review_step_continue_button/click/go_to_next_formation_step

**Billing**
- business_formation_billing_step_continue_button/click/go_to_next_formation_step

## Notes

- [ ]

**Comment by aaronvux** [comment]
@skeeJay I will schedule time for us to update the requirements for Google Analytics and Business Formation.

**Comment by aaronvux** [comment]
Schedule meeting to discuss.

**Comment by kmelefsky** [comment]
check in again on Monday

**Comment by skeeJay** [comment]
I see four of the six new event categories showing up in GA. Willing to say this has been spot-checked.

<img width="944" alt="Screen Shot 2022-02-14 at 9 44 12 AM" src="https://user-images.githubusercontent.com/506096/153889035-edb3683b-3aad-42a0-b61d-8badce6b8ea2.png">
