### ISSUE TITLE
Create Sectors field in onboarding and profile for Oscar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1309]
## User Story
As Oscar, I need the ability to select a Sector so that I can have funding dynamically displayed to me correctly.

## Acceptance criteria
- Remove Industry field from Oscar onboarding and profile.
- Create new single-select searchable dropdown for Oscar in onboarding and Profile called Sectors (required field)
- Use the selected Sectors to support dynamic funding display on the Oscar Dashboard.
- Use the list below in alphabetical order.
- Always display home based business question for Oscar.
- Do not display Liquor license question or mobile location question

**Sectors List**
- Accommodation and Food Services
- Administrative and Employment Services
- Agriculture, Forestry, Fishing, and Hunting
- Arts, Entertainment, and Recreation
- Cannabis
- Clean Energy
- Construction
- Digital and Print Media
- Educational Services
- Finance and Insurance
- Health Care and Social Assistance
- Life Sciences
- Manufacturing
- Mining, Quarrying, and Oil and Gas Extraction
- Organizational or Financial Management of Companies
- Other Services
- Professional, Scientific, and Technical Services
- Real Estate
- Retail Trade and E-Commerce
- Technology
- Transportation and Warehousing
- Utilities
- Waste Management and Remediation
- Wholesale Trade 

## Additional Acceptance Criteria
- Works in Mobile
- 508 Compliant

## Notes
- [x] UX Review
- [x] Content Review
- [x] PO Approval
- [x] Industry value should be set to generic for Oscar users

**Comment by aaronvux** [comment]
@Jesslax should I move this to prioritized column or do you think we can add some details today before grooming?

**Comment by Jesslax** [comment]
@aaronvux this is a @carye3 question.

**Comment by carye3** [comment]
you can go ahead and move it to prioritized @aaronvux

**Comment by FarazA22** [comment]
@fiorella-io @carye3 Can you add the link to the final designs for this ticket. Where will this dropdown sit on the onboarding and profile pages?

**Comment by aaronvux** [comment]
@FarazA22 my understanding is that it is replacing the Industry field.  Use the same location for Profile and Onbooarding.

**Comment by FarazA22** [comment]
@aaronvux @Jesslax Two 

sector list items are very similar, would like to confirm if we are keeping both (second references industries)
1) Other Services (except Public Administration)
2) Industries Not Classified

**Comment by carye3** [comment]
> @fiorella-io @carye3 Can you add the link to the final designs for this ticket. Where will this dropdown sit on the onboarding and profile pages?
> 
> 

@FarazA22 this has the same design as the current industry Dropdown

**Comment by Jesslax** [comment]
@FarazA22 great question! Let's only have "Other Services" and not the other one, I am updating the tkt now.

**Comment by FarazA22** [comment]
@Jesslax @aaronvux 

Is it ok if I update "Real Estate and Rental and Leasing" to say "Real Estate, Rental and Leasing"?

**Comment by Jesslax** [comment]
@FarazA22 yes

**Comment by Jesslax** [comment]
@FarazA22 made my copy tweaks, and I removed offshore wind as an option as it is covered by Clean Energy

**Comment by FarazA22** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@FarazA22 Professional, Scientific, and Technical Services needs to capitalized and in the correct spot in the list.
![Screen Shot 2022-02-09 at 2 38 29 PM](https://user-images.githubusercontent.com/36163601/153277353-000ee123-98c2-42d5-8be4-3f68dbc2e320.png)
c

**Comment by FarazA22** [comment]
@aaronvux fixed, will be available shortly

**Comment by fiorella-io** [comment]
@FarazA22 

- For mobile, can we make sure when the options wrap to two lines there is no indent? Make sure everything is left aligned.
![image](https://user-images.githubusercontent.com/91498500/153432553-62b5b5ec-a27c-4846-9acc-5d7119d50817.png)

- (possible bug) For some reason, when I have the inspect open, and I switch to another tab and then come back, it changes from Oscar to Poppy.

**Comment by fiorella-io** [comment]
@FarazA22 Everything looks good. Thanks!
