### ISSUE TITLE
Update Oscar Onboarding for Oscar Dashboard V1

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1323]
As Oscar, I need to be able to input my business formation date and add my demographic information to onboarding so I can have my Dashboard customized based on my selections.

## Acceptance criteria

**Oscar Onboarding**
- Add Business Formation Date to Oscar Onboarding Step 1 (required)
-  Update content in Certifications dropdown
-- A Women
-- A Minority
-- A Veteran
-- A Disabled Veteran

[Figma Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6029%3A110729)

## Google Analytics
TBD

## Additional Acceptance Criteria:
- Works in Mobile
- 508 Compliant
- feature flag

## Notes
- [x] PO Approval
- [x] UX Review

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please add the design.

**Comment by mikewolfd** [comment]
@fiorella-io is there design for this?

**Comment by fiorella-io** [comment]
@mikewolfd @aaronvux I've added the design for the Business Formation date on Step 2 of Onboarding

**Comment by kmelefsky** [comment]
finishing up refactor for next steps

**Comment by aaronvux** [comment]
@fiorella-io please check.  This looks good to me.

**Comment by carye3** [comment]
- Business Formation date: we should include a "Where can i find this?" contextual menu
- Business Formation date: what if a user doesn't remember the exact date of formation? To avoid losing users in onboarding if they don't know the exact day, it might be useful to just ask for month and year
- Industry should be labelled as Optional
