### ISSUE TITLE
Remove Operate Section from Poppy

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#1324]
As a Navigator user I should only see content that applies to my persona so that I receive the most relevant information to my business.

## Acceptance Criteria:
- Remove the Operate section from Poppy on the Roadmap and mini-roadmap.
- Do not display Start and Grow sections for Oscar.
  - Only Display the Oscar Dashboard on the landing page.
  - Only display the Operate section in the mini-roadmap on the task screen.

- [x] PO Approval

**Comment by dsueltenfuss** [comment]
#880 should be completed before this task is started

**Comment by aloverso** [comment]
@aaronvux thinking I could pick this one up next, thoughts?

**Comment by aaronvux** [comment]
@aloverso sounds good.

**Comment by aaronvux** [comment]
@aloverso can you add some points to this one please?

**Comment by aaronvux** [comment]
Looks good.  Moving to staging.
