### ISSUE TITLE
One-Time Import of Funding Opportunities from Airtable for Oscar Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1326]
As a Content Administrator, I need the Funding Opportunity information currently being stored in Airtable to be automatically imported and available in the Oscar Dashboard.

## Acceptance criteria
- Import the funding opportunities from the airtable to the Navigator and available in the Oscar Dashboard
https://airtable.com/appMLFtbZCJrJPTf4/tblFkGCCfFEWORzDA/viwlGyyn6eJdsxKEc?blocks=hide

- Use ROW 1 as the Column headers in the airtable
- Opportunity Type: Funding
- Title: Program Name (airtable)
- Task Description: Description + Benefits Summary + Eligibility (airtable)
- Call to Action Button Copy:  "Apply Now"
- Call to Action Button URL: Call to Action URL (airtable)

## Notes

- [ ] PO Approval

**Comment by aaronvux** [comment]
@Jesslax please review

**Comment by Jesslax** [comment]
LGTM
