### ISSUE TITLE
Business Formation - Mobile Design

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1330]
As Poppy, I need the ability to form my business using my mobile device so that I can easily get my Entity ID without needing a laptop.

## Acceptance criteria
- Business Start Date should be full width (Done in #1331)
- Business State & Zip Code should be on the same line (Done in #1331)
- Registered Agent spacing between content and radio buttons.
- Registered Agent radio buttons content on 1 line 
- Register Agent State & Zip Code should be on the same line (Done in #1331)
- Add Member modal, State and Zip Code should be on the same line. (Done in #1331)
- Add New Signer field should extend.  Delete icon should be on the right. (Done in #1395)

## Design
Mobile:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7001%3A182165

## Notes
- [x] UX Review
- [x] PO Approval

**Comment by namanaman** [comment]
@fiorella-io Regarding the AC "Registered Agent radio buttons content on 1 line," the content would only fit on 1 line if the font was pretty small, at `font-sans-3xs`. Which of the following font sizes below would you prefer?

`font-sans-xs`
<img width="366" alt="xs" src="https://user-images.githubusercontent.com/9057802/153635570-3b7c569d-beeb-40a3-99f1-17604cbdd312.png">

`font-sans-2xs`
<img width="367" alt="2xs" src="https://user-images.githubusercontent.com/9057802/153635589-713f27bd-cbbe-410d-aa3e-68726d25d0fe.png">

`font-sans-3xs`
<img width="394" alt="3xs" src="https://user-images.githubusercontent.com/9057802/153635610-b6bdb0a7-beec-4589-bb71-0f111f482b4c.png">

**Comment by fiorella-io** [comment]
@namanaman We don't want to reduce the font. Let's keep it 16px. It's ok if it wraps. For some reason at 320px viewport, I see an empty space to the right of the radio button. It seems there's some sort of padding on the right. If we can remove that it should be fine. 
![image](https://user-images.githubusercontent.com/91498500/153669952-a56467a5-3b4c-4c8c-a399-4263a0ef1239.png)

**Comment by namanaman** [comment]
@fiorella-io Ah I see, yep, will remove the extra padding in there and leave the font size as is. Thank you!

**Comment by aaronvux** [comment]
@fiorella-io please continue to review.

**Comment by fiorella-io** [comment]
I've noticed this issue on the dropdown, where you have the close button on top of the state on mobile (320px viewport). We might need to use a different pattern for State. We can discuss this during our dev/design sync.
<img width="99" alt="image" src="https://user-images.githubusercontent.com/91498500/153921134-3b866033-5707-4651-bc56-b50e8eb6d9f8.png">

Can we add more padding between the "Cancel" and "Add Member" buttons (320 viewport)
<img width="218" alt="image" src="https://user-images.githubusercontent.com/91498500/153921828-095291b2-c919-4e21-b4ba-7a924ea65917.png">

**Comment by namanaman** [comment]
@fiorella-io Good point, I had not tested `mobile-sm`. I can increase the column width of the state dropdown so theres a little more room (see pic below), otherwise I can put the state dropdown and zip code in their own rows as before. What do you suggest?

<img width="320" alt="Screen Shot 2022-02-14 at 2 14 27 PM" src="https://user-images.githubusercontent.com/9057802/153931307-9a5fcd10-d6c7-48a1-b028-36b44b16a5b7.png">

**Comment by fiorella-io** [comment]
@namanaman That works! thank you! Just make sure the "Cancel" and "Add Member" buttons are right-aligned.

**Comment by namanaman** [comment]
@fiorella-io Changes are ready for review!
