### ISSUE TITLE
Convert to an S-Corp Designation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1363]
As a Navigator user, I need the ability to designate my business as an S-Corp so that I have the correct designation on file with the State.

## Acceptance criteria
- Add S Corp to Onboarding to the Legal Structure step
  - Update the list in accordance with the design
- Add S Corp to the Legal Structure dropdown in the Profile
- If S-Corp is the legal structure, display the C-Corp Roadmap
- Add two new S-Corp tasks under step 3
  - Apply for S Corporation Designation with the Federal Government  
  - Apply for S Corporation Designation with the State of New Jersey
  
## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8176%3A189797

## Notes

- [x] PO Approval
- [x] UX Review

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
Additional tweaks being made.  Should close before demo tomorrow.

**Comment by CeciliaRam** [comment]
S Corp content has been reviewed, edited, approved, and published. @aaronvux all done.
