### ISSUE TITLE
Business formation "Response error" when it should be more descriptive

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#1364]
When i enter a business name that's already taken, the API logs show the proper error but the user only sees "Response error" which is not very helpful.

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aloverso is there a way to wrap the URL?
<img width="682" alt="Screen Shot 2022-01-31 at 12 03 06 PM" src="https://user-images.githubusercontent.com/36163601/151839100-cd8042f5-299b-41c5-9a20-8c1f75d3189f.png">

**Comment by aaronvux** [comment]
@aloverso Received a response error.  I believe it is from the Agent Number field.  I used 1234.  I don't believe it exists when it's validating against the API.   Is this the same thing you emailed NIC about recently?

<img width="619" alt="Screen Shot 2022-01-31 at 12 05 03 PM" src="https://user-images.githubusercontent.com/36163601/151839942-4087d907-62d8-41bc-a3dd-27280d57ba43.png">

**Comment by aloverso** [comment]
@aaronvux yes, the response error for agent number isn't in our control, that's what I emailed Michael about earlier today.

**Comment by aaronvux** [comment]
Emailed Michael with additional information about Registered Agent validation.

**Comment by aloverso** [comment]
@aaronvux I did do the wrapping URL
