### ISSUE TITLE
Fix "Persona" Custom Dimension

### ISSUE THREAD

**Issue by kmelefsky** [newjersey/navigator.business.nj.gov#1394]
**Current Behavior:**
fix build process, verify that new analytic persona exists in newly built html
[what's incorrect]

**Expected Behavior:**

[what should happen instead]

**Steps to Reproduce:**
1. 
2. 

**Acceptance Criteria**
Verify that the dimension is actually appearing in the Google Analytics dashboard, instead of just verifying via the console.

**Comment by dsueltenfuss** [comment]
@mikewolfd verified that this is now working in production

**Comment by skeeJay** [comment]
@dsueltenfuss @mikewolfd @aloverso @aaronvux I unfortunately still don't see Persona showing up as a Custom Dimension in our Google Analytics. But it's analytics, so there's always a change I'm looking wrong. Any thoughts as to why I may not be seeing it?

**Comment by skeeJay** [comment]
@aaronvux @kmelefsky Really feel like we need to reopen this bug. The custom dimension is still not appearing in GA.

**Comment by skeeJay** [comment]
Adding to acceptance criteria that when reviewing and before closing again, we should validate that the dimension is actually appearing in the Google Analytics dashboard, instead of just verifying via the console. cc @kmelefsky

**Comment by dsueltenfuss** [comment]
Closing. No Deployment needed.
