### ISSUE TITLE
Business Formation - UI Updates

### ISSUE THREAD

**Issue by fiorella-io** [newjersey/navigator.business.nj.gov#1395]
As Poppy, I need the ability to form my business so that I can easily get my Entity ID and other business documents.

## Acceptance criteria

- Add hr divider before Location heading and Registered Agent
- City, State, and Zip Code should be in one line
![image](https://user-images.githubusercontent.com/91498500/149401172-7a3efb1c-3a5c-4fe3-b014-7aacd5977582.png)
- Make sure the delete icon aligns to the right of the input field
![image](https://user-images.githubusercontent.com/91498500/149403507-fd956668-3397-4659-9838-01d17d1161bd.png)
- Double-check all designs in prototype
- Fix mobile edit button spacing issue and missing horizontal lines in Members section.

### Designs
[Figma Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6474%3A160334)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@fiorella-io can we add individual outstanding items as AC to each of these before Grooming on Monday please?

**Comment by aaronvux** [comment]
@kmelefsky repoint for additional AC at planning.

**Comment by aaronvux** [comment]
@fiorella-io please review

**Comment by fiorella-io** [comment]
Everything looks good! 
I still notice some spacing issues between fields which should be fixed with #1432  

Bug: When I click on the "Update your profile" link for City, and after I make the change on my profile and click on "Save" it doesn't take me back to the form as it does with editing the Business Name and Legal Structure.
@namanaman @aaronvux
