### ISSUE TITLE
Profile Screen for Oscar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1396]
## Acceptance criteria
- Clicking Cancel or Save on the Oscar Profile page will take the user back to the Dashboard.
- Create a profile specific to the Oscar persona, to include the following fields (submission criteria same as onboarding):

**Header: "Business Profile" Section**
- Business Name
- Industry
- Location
- Ownership
- Number of Employees

**Header: "References/Important Numbers" Section**
- EIN #
- Entity ID
- NJ Tax ID
- Tax PIN 
  - Validation: Tax PIN must be 4 digits.
- Notes

Note: replace certifications.md file with ownership.md file

[Figma Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8421%3A196321)

- Feature Flag

## Notes
- [x] PO Approval
- [x] UX Review

**Comment by FarazA22** [comment]
@Jesslax Could you review and update the AC?

**Comment by FarazA22** [comment]
@aaronvux Can you confirm the AC for me. Just want to make sure we didn't miss anything. I have some notes based on my review.

1) We capture Certifications via onboarding, but it's not captured in the AC
2) We are removing Legal Structure for Oscar within Profile page, confirm this is correct
3) The requirements mentioned Ownership and Tax Pin. Are they new fields?

Also, if the user enters NO for their home based business question, change to an industry where the home based question is not applicable (question goes away) and changes back to an industry where the home based question is applicable, the value updates to YES. I feel like this is a bug, but wanted to confirm.

**Comment by FarazA22** [comment]
@fiorella-io Aaron will be reviewing the AC, but based on what's stated right now, I'm wondering if we have any designs for this page. If so, can you add. It looks like the profile page for Oscar is separated into sections.

**Comment by aaronvux** [comment]
1. Certifications is changing to Ownership.
2. We are not capturing legal structure for Oscar.
3. Tax Pin is new.  It is not required, but there is a 4 digit validation on the value.
4.  --- 
5. Not sure about this one.  Let's discuss.

**Comment by kmelefsky** [comment]
next steps - discuss comments later today, need link provided for design

**Comment by fiorella-io** [comment]
@aaronvux I've adjusted the order to match the order of Onboarding, to keep it consistent:
Business Name, Location, Number of employees, Certifications, Industry, Legal Structure (I didn't see it listed). What is ownership?

**Comment by FarazA22** [comment]
@fiorella-io The fonts are not using the tokens, can we please take another look. It looks like we are introducing new styles.

**Comment by FarazA22** [comment]
@aaronvux Are any of the validations changing for existing inputs/fields? (i.e. if I have an existing business, should business name be required).

**Comment by aaronvux** [comment]
@FarazA22 I don't believe there are any changes to existing fields.

**Comment by FarazA22** [comment]
@fiorella-io Can you update the designs to include the new 'Tax Pin' text field.

**Comment by FarazA22** [comment]
@aaronvux The Onboarding Entity Id input for Poppy gets disabled when the user completes the business formation form. Can you confirm if this disabled functionality is applicable for Oscar, I'm assuming the field does not get disabled.

**Comment by fiorella-io** [comment]
@FarazA22 Done!

**Comment by aaronvux** [comment]
My understanding for the Oscar profile is that it will not be disabled.  @Jesslax please confirm.

**Comment by Jesslax** [comment]
If they use our new business formation screen to submit their legal structure, and we get back their eid, it will be locked. That could happen for a Poppy who becomes Oscar, but for Oscar in general, not locked. We might lock it later once we can validate their EID with Treasury.

**Comment by FarazA22** [comment]
@aaronvux Should there be a unique error message for the Tax Pin or the generic error message ( 'Must be 4 digits long.' )

**Comment by aaronvux** [comment]
@FarazA22 "Tax Pin must be 4 digits"

**Comment by FarazA22** [comment]
For Poppy, design would like the H1 heading to also be 'Business Profile' instead of 'My Profile'.  The heading does not match the name in the drop down. 

Since this ticket only touches Oscar, we are dynamically rendering the content. Should we remove the dynamic rendering and only refer to a single variable?

<img width="1031" alt="Screen Shot 2022-01-28 at 4 55 26 PM" src="https://user-images.githubusercontent.com/72581979/151626904-f0940684-b622-42ee-acb4-38bc12398595.png">

**Comment by FarazA22** [comment]
@aaronvux We have a hierarchy/ accessibility issue, and would like to discuss a possible solution. Let's catch-up on Monday.

**Comment by FarazA22** [comment]
@aaronvux @fiorella-io @carye3 I have a question about the Save Alert
<img width="373" alt="Screen Shot 2022-01-31 at 10 38 57 AM" src="https://user-images.githubusercontent.com/72581979/151823727-a14b2948-7fdc-4344-80b2-f26f7194bcb4.png">

**Comment by FarazA22** [comment]
@aaronvux RDY

**Comment by fiorella-io** [comment]
@FarazA22 I noticed an extra question mark for Tax Pin
![image](https://user-images.githubusercontent.com/91498500/151981066-eccf8587-f3bd-4796-a1c2-ce483dc29c58.png)

**Comment by FarazA22** [comment]
@aaronvux Well need a separate ticket to add business formation date/ start date to the profile page for Oscar.

**Comment by aaronvux** [comment]
@FarazA22 I think Jess left it out for a reason on this ticket.

**Comment by Jesslax** [comment]
@FarazA22 @aaronvux  I forgot that we are adding it to onboarding, let's put it in the profile. Sorry about that.

**Comment by aaronvux** [comment]
Moving to staging.
