### ISSUE TITLE
Business Formation - total cost on documents section is not calculating when returning to page

### ISSUE THREAD

**Issue by FarazA22** [newjersey/navigator.business.nj.gov#1397]
Given when an LLC user has the optional documents preselected as true within their userData. When they navigate to the payment tab of the business formation form. The total cost should reflect the correct amount. 

User should be able to navigate away from the payment tab, when the user data is saved and the user returns to the tab, the total cost on initial render of the tab should be correct.

**Comment by dsueltenfuss** [comment]
@aaronvux  this is ready for review

**Comment by aaronvux** [comment]
this looks good.  The Payment Type story will add back the charges for each payment type.
