### ISSUE TITLE
Task status no longer automatically updating with license status

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#1428]
<img width="587" alt="Screen Shot 2022-01-24 at 1 47 23 PM" src="https://user-images.githubusercontent.com/506096/150851069-462c281c-9c3d-4a70-bc49-fc3099d4c713.png">

**Current Behavior:**

[what's incorrect]

**Expected Behavior:**

Task status should update automatically to match license status.

**Steps to Reproduce:**
1. As a Pharmacy, enter test address into license status Task screen
2. Observe that on both Task screen and Roadmap, status does not change

**Comment by aloverso** [comment]
@skeeJay @aaronvux I can't replicate this bug - appears to be working for me. Can someone else verify? Maybe this was a one-off random failure?

**Comment by aaronvux** [comment]
@aloverso the status did not update to "Pending" for me.
![Screen Shot 2022-01-31 at 2 41 56 PM](https://user-images.githubusercontent.com/36163601/151861440-a068639a-1140-41af-a6d7-531e85d61c56.png)

**Comment by aloverso** [comment]
Ah, I see. It's only happening for Pharmacy licenses. will fix

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
This looks to be working now.  Moving to staging.
