### ISSUE TITLE
Update Beta Bar Design in Navigator

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1439]
As a Navigator user, I need to have a simplified BETA Bar that allows me to have access to a survey so I understand the site's release state and can give my feedback.

## Acceptance criteria

- Update background color
- Remove "BETA", follow copy.

## Design

https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109170

## Notes

- [x] PO Approval
- [x] UX Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this story is ready for review

**Comment by fiorella-io** [comment]
@dsueltenfuss Can we add some padding to the left of the text for mobile (320px viewport). There should be 16px/1rem padding on the left and right of the text. 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/91498500/154287805-0bca8629-d748-4f83-9db3-dc77e9e04d84.png">

**Comment by dsueltenfuss** [comment]
@fiorella-io I've added the margin, and this is ready to review again

**Comment by fiorella-io** [comment]
Thank you so much @dsueltenfuss! It looks good.
