### ISSUE TITLE
Update Business Formation API to Pass More Info to NIC

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1441]
As Poppy, I need to have as much of my information passed to NIC that I input into the Navigator so that I don't have to reenter it.

## Acceptance criteria

- Business Name > CompanyName
- Business Address 1 > Address1
- Business Address 2 > Address2
- Business City > City
- Business State > StateAbbreviation
- Business Zip Code > ZipCode
- Profile Email > Email

## Notes

- [x] PO Approval

**Comment by aaronvux** [comment]
Need to cross check this with the API documentation.

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
Looks good.  Moving to deploy.
