### ISSUE TITLE
Implement New Favicon

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1443]
As a Navigator / Business.NJ user, I need to see an icon that represents the application as a Favicon so I can easily identify it amongst multiple tabs.

## Acceptance criteria

- Follow Design
- Implement new favicon 

[Design: Business.NJ Favicon](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9061%3A224743)
[Design: Navigator Favicon](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9061%3A224744)

## Notes

- [ ] PO Approval
- [ ] UX Review

**Comment by mikewolfd** [comment]
@carye3 @fiorella-io could you export the icons out of figma as a png?

**Comment by carye3** [comment]
> @carye3 @fiorella-io could you export the icons out of figma as a png?

this was resolved

**Comment by carye3** [comment]
Favicon without white background (Navigator) 
![Navigator](https://user-images.githubusercontent.com/62653834/154287693-17cc3a33-dc6e-4613-b376-709f5ebdc096.svg)

**Comment by aaronvux** [comment]
I see the icon in my desktop Chrome browser, but not in my phone in Chrome.
![IMG_4602](https://user-images.githubusercontent.com/36163601/154493141-d9ea1b1f-353c-458b-86f7-4e217e6ac5a0.jpg)

**Comment by skeeJay** [comment]
I am actually not seeing this at all in production. Have we validated that this was deployed to production? cc @aaronvux @dsueltenfuss

**Comment by aaronvux** [comment]
@skeeJay I'm also not seeing it.  I wonder if it's a caching issue I mentioned above that I experienced on my phone.

**Comment by skeeJay** [comment]
@aaronvux I don't believe it's caching. I'm not seeing it on a fresh browser installation. Something about the production config means the favicon is not there.
