### ISSUE TITLE
Handle Industries that are Missing Step 2 in their Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1469]
As Poppy in an industry that does not have Step 2 in their roadmap, I still need the ability to successfully navigate my roadmap and obtain useful information for my business.

## Acceptance criteria

- Combine tasks from Plan Your Business and Make Few Decisions into "Step 1 - Plan Your Business" for all Roadmaps
- Step 2 will always be "Register and Form Your Business" and fall under START.

## Designs

https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8313%3A195945

## Notes

- [ ] UX Review
- [ ] PO Approval
- [ ] Content Review

**Comment by dsueltenfuss** [comment]
@aaronvux this change is ready for review

**Comment by aaronvux** [comment]
@Jesslax This looks good to me.  Please review.

**Comment by Jesslax** [comment]
LGTM
