### ISSUE TITLE
Visually Identify Critical Steps in the Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1471]
As Poppy,  I need to be able to easily identify critical tasks in the Roadmap so that I can focus on things that are required for me to start my business.

## Acceptance criteria

- Add "Required" icon to the left of the task status
- Display tool tip on hover: "Required"
- Add "Required + Copy" icon to the top of the task screen.
- Add to cms so that icon can be applied to any task 

## Additional Acceptance criteria
- Follow Design
- Works in Mobile
- 508 Compliant

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8198%3A193517

## Notes
- [ ] UX Review
- [ ] PO Approval
- [ ] Content Review

**Comment by namanaman** [comment]
@carye3 @fiorella-io Just to confirm, do we prefer this square icon over other exclamation point options that are already in the US WDS? (from searching "exclamation point" in the Component Preview section - https://designsystem.digital.gov/components/icon/)

**Comment by carye3** [comment]
The square ones @namanaman , users picked them out easily. Thx!

**Comment by namanaman** [comment]
@carye3 @fiorella-io Two more questions:
1. In the design, the required icon has the color `cool-accent-darker` on the roadmap and #2E6276 on the task screen. Can we align them to the former or is the difference intentional?
2. I saw a mismatch in the heights of the tags between the design and current product, so I wanted to check which height we want to go with for all tags, so I can then align the new Required tag to have that same height. 
*In Design:*
Completed Status Tag - 18px 
Required Tag - 19px

*In Current Product:*
Completed Status Tag - 20px

**Comment by fiorella-io** [comment]
@namanaman Use the cool-accent-darker and the current Completed tag height of 20px. Thanks!

**Comment by namanaman** [comment]
Thanks @fiorella-io ! Is it possible to send me or update the design with a 20x20px version of the required icon's SVG. Then I can directly use that file in the code. I know it's late, so I can follow up Monday.

**Comment by namanaman** [comment]
@carye3 @fiorella-io Following up about this, thanks^

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam can we identify the critical tasks and add them in dev please?

**Comment by Jesslax** [comment]
@aaronvux We can test it and take it off, does that work? My understanding was that we would not be expected to get this setup during this sprint.

**Comment by aaronvux** [comment]
@Jesslax that's fine.

**Comment by Jesslax** [comment]
Everything looks great. The only item is the preview, the spacing between the status and required button is a little too close together:
![image](https://user-images.githubusercontent.com/78366346/153251021-d2afe6fd-d302-4535-a5b4-558d7e5021ee.png)

**Comment by namanaman** [comment]
@Jesslax I think that may have to do with how the preview shows the Not Started button. This is what it looks like on Chrome, does this seem fine or would you still say it could use more spacing?
<img width="666" alt="Screen Shot 2022-02-09 at 2 13 43 PM" src="https://user-images.githubusercontent.com/9057802/153273546-bbe2324e-59f2-4c5b-9c76-391139f4160b.png">

**Comment by Jesslax** [comment]
That's fine, thanks.

**Comment by carye3** [comment]
lgtm! @namanaman
