### ISSUE TITLE
Add Business Formation Date to Oscar Profile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1504]
As Oscar, I need to be able to view and edit my Business Formation Date in my profile so that I can correct any errors I have made.

## Acceptance criteria

- Add Business Formation Date to the Oscar Profile
- Field is editable
- Required field and date formatting validation

[Figma Link](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8421%3A196321)

## Notes

- [x] PO Approval
- [x] UX Review

**Comment by aaronvux** [comment]
@mikewolfd @aloverso can one of you pick this one up please?

**Comment by aaronvux** [comment]
@fiorella-io please review.  Looks good to me.  We'll update the validation message through content files.

**Comment by fiorella-io** [comment]
@aaronvux looks good to me. Thanks, @mikewolfd!
