### ISSUE TITLE
Add Funding Opportunities to Netlify CMS

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#1505]

**Comment by aaronvux** [comment]
@aloverso how can @CeciliaRam or @Jesslax test this?

**Comment by aloverso** [comment]
The files are now available for editing in the CMS

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam please review.

**Comment by Jesslax** [comment]
@aloverso They all uploaded, yay! 1) The fields that say "eligibility" and "benefits" should be displayed in the body of the task screen. They are not meant to be database copy that we reference. Is it possible for the copy in those two fields to show up in the main copy box. In a more ideal world, the words "eligibility" and "benefits"  would be bold and look like it does [here](https://business.nj.gov/funding). 2) The preview function is a bit off, it shows all the copy, not the user facing copy.

**Comment by aloverso** [comment]
@Jesslax -

1. yes that makes sense, and is easy, but @aaronvux can we add a story to show these fields on the task screen body? should be pretty simple 
2. similarly, we haven't built the preview function yet but we can add a story to preview them just like we do with Tasks
