### ISSUE TITLE
Implement "Guest Mode"/Move myNJ Registration

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1515]
As a Navigator user,  I need to be able to access the Navigator without creating a myNJ account so that I don't abandon onboarding.

## Acceptance criteria

**Onboarding**
- Display Snackbar window to create an account/login when the user lands on the Dashboard or Roadmap until the user closes it.
  - Redisplay when the user refreshes the Roadmap or Dashboard.
- Clicking on tasks status dropdown, License Status task link on the Roadmap, Business Formation task link on the Roadmap, and Profile link or Edit Profile link will open the registration/login modal window.

**Modal Window**
- Copy
- Register Button redirects to myNJ login.
- Login Link redirects to myNJ login.
- Bring the user back to their current page after successfully registering/logging in.
  - Display Snackbar success message.
- Do display Snackbar again after the user has successfully completed myNJ registration.

**Profile Area**
- Display Guest Mode Icon until registration is complete, then follow current implementation.
- Display only the "Register" option in the dropdown until registration is complete, then follow current implementation.

**Analytics**
https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

- Set Custom dimension7 according to spec, with four possible values
- Remove/confirm that red events are being removed
- Add/create green events

## Additional Acceptance Criteria
- Works in Mobile
- 508 Compliant 
- Follows Design

## Designs

**Prototype**
https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9155%3A234521&scaling=min-zoom&page-id=9150%3A225150&starting-point-node-id=9155%3A234521&show-proto-sidebar=1

## Notes

- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Need to add design for duplicate email address being found in myNJ.

**Comment by aaronvux** [comment]
Create separate story to document analytics.

**Comment by fiorella-io** [comment]
@aaronvux I just added the design for duplicate email and content was vetted by Ce

**Comment by skeeJay** [comment]
@mikewolfd @aaronvux Here is what I have specced for the custom dimension:

dimension7
name: “Registration Progress”
potential values: [“Unstarted”, “Began Onboarding”, “Onboarded Guest”, “Fully Registered”]

Let me know if it makes sense and looks good. If so, I'll add to the acceptance critieria.

**Comment by skeeJay** [comment]
@mikewolfd @aaronvux Actually, I am learning I might need to update/add new events too. Stand by.

**Comment by aaronvux** [comment]
@mikewolfd Please move the Registration Modal for the Check Available Names and Form Your Business task to when the user clicks the "Continue Forming My Business" button.

<img width="647" alt="Screen Shot 2022-03-16 at 2 17 07 PM" src="https://user-images.githubusercontent.com/36163601/158659853-ecc19072-770e-4593-b842-af44429404ab.png">

**Comment by skeeJay** [comment]
@mikewolfd @aaronvux Okay, I have specced the Custom Dimension and the new necessary events. Also, there are old events that will no longer exist/make any sense in the new flow, and we could confirm all of those are being removed entirely. In the spec, new events are green, events to remove are red, and there is one specific old event that should remain in a new place and we should confirm it fires at the right new time. Please let me know if you'd like to walk through all of this.

https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

**Comment by skeeJay** [comment]
@mikewolfd @aaronvux Okay, I have specced the Custom Dimension and the new necessary events. Also, there are old events that will no longer exist/make any sense in the new flow, and we could confirm all of those are being removed entirely. In the spec, new events are green, events to remove are red, and there is one specific old event that should remain in a new place and we should confirm it fires at the right new time. Please let me know if you'd like to walk through all of this.

https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please review.

**Comment by carye3** [comment]
@aaronvux having a persistent snackbar even after the user closes it seems broken. I think the tool should remember the users preference and hide it for 15 minutes before popping it up again.

**Comment by carye3** [comment]
A couple other changes:

Snackbar styling:
- Make paragraph break spacing consistent with elsewhere on site <img width="304" alt="Screen Shot 2022-03-21 at 2 14 21 PM" src="https://user-images.githubusercontent.com/62653834/159339448-dfc9fb9f-9e5b-4cc7-b765-f899d1d3fde6.png">
- Registration snackbar (grey) has different styling than [informational snackbar ](https://www.figma.com/file/EraDAUUvuOksWZtTgp2c9I/BFS-Design-System?node-id=1475%3A2213)(blue) <img width="729" alt="image" src="https://user-images.githubusercontent.com/62653834/159339630-5c4af844-ef37-4f01-9ae9-ad6e1c9286da.png">

**Comment by carye3** [comment]
One more request: 

**Clicking on restricted detail screen brings up registration modal**. I'm noticing that you only get a modal after entering a restricted detail screen (eg forms), but if you'd mistakenly closed it, you are no longer provided with feedback with why that detail screen is restricted.
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/62653834/159342597-5bc486b7-3c9c-46d6-96f9-c1df59e88146.png">

**Comment by mikewolfd** [comment]
@carye3 @aaronvux fixed the styling things and removed the alert from the task/funding screens, it's only when you go to the dashboard or roadmap as per the acceptance criteria.

**Comment by aaronvux** [comment]
@mikewolfd Let's talk at standup.  I can be ok with this, but I think the intent of the AC was to only display the snackbar when the page is refreshed, not just navigating back to Roadmap or Dashboard when you're already in the app.

**Comment by carye3** [comment]
@mikewolfd @aaronvux looks good, i'll make a ticket for the other issues (clicking on restricted task, etc)

See #2076
