### ISSUE TITLE
Vertical Stepper Graphic lags behind section accordion close in task view

### ISSUE THREAD

**Issue by mikewolfd** [newjersey/navigator.business.nj.gov#1536]
Vertical Stepper Graphic lags behind section accordion close in task view

![Screen Shot 2022-02-03 at 11 25 30 AM (3)](https://user-images.githubusercontent.com/12499270/152384618-554ba8d6-93a7-4613-8d05-c93bad246856.png)

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
looks good to me
