### ISSUE TITLE
Dynamically Display Veteran Certification Opportunity on Oscar Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1556]
As Oscar, I need the ability to have the Veteran Certification Opportunity display on my Dashboard when I am a veteran or disabled veteran so I know what certifications are available for my business

## Acceptance criteria
- Only display the Veteran Certification Opportunity on the Oscar Dashboard when the Ownership value from Onboarding is veteran or disabled veteran.
- Do not display the Veteran Certification Opportunity on the Oscar Dashboard for any other Ownership value.

## Notes
- [x] UX Review
- [x] PO Approval

**Comment by aloverso** [comment]
@Jesslax to be clear, is it ALSO subject to regular filtering logic? I notice that the opportunity is listed only for Burlington county and for non-home-based only. So even if a user selects veteran-owned, they still might not see it due to the other filtering, correct?

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aloverso this looks good.  Moving to staging.
