### ISSUE TITLE
Accommodate Sole Proprietorship and General Partnerships on Oscar Dashboard Calendar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1557]
As an Oscar user who is an SP or GP, I need the ability to access the dashboard without providing a business formation date so I can complete onboarding.

## Acceptance criteria
- Make Business Formation Date Optional
- If Business Formation Date is not populated, no annual filing should display.
- Copy on the Business Formation question will be updated by Jess/C 

## Notes
- [ ] UX Review
- [ ] PO Approval
- [ ] Content Review

**Comment by aaronvux** [comment]
@namanaman @mikewolfd Business Formation Date is showing in the calendar even though no Business Formation Date was input.
<img width="1242" alt="Screen Shot 2022-02-23 at 9 39 07 AM" src="https://user-images.githubusercontent.com/36163601/155341394-5a296af4-0049-40ba-a1c4-490275af7df4.png">

**Comment by namanaman** [comment]
@aaronvux Should be fixed now

**Comment by aaronvux** [comment]
Looks good.  Moving to staging.
