### ISSUE TITLE
Graduation/Toggle: Just Buttons at Bottom of Roadmap/Dashboard, Linking to Onboarding/Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1560]
As a Navigator user, I need the ability to toggle between or graduate to functionality that is not available to me so that I can keep my business growing or start a new business.

## Acceptance criteria

- Remember if user has switched and take them to the appropriate page

**Poppy**
- Add Graduation button and content at the bottom of the Roadmap
- Clicking the button displays takes the user to the Oscar onboarding
  **- Pre-populate any information that has already been input during Poppy onboarding.** 

**Oscar who Started as Poppy**
- Clicking the link will take the user directly to the roadmap
  
**Oscar who completes Onboarding**
- Do not display Content Box.

## Analytics

Events:
- Oscar back to roadmap link: `dashboard_ungraduate_button/click/existing_dashboard_to_prospective_roadmap`

https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

Custom Dimensions:
- Update the persona custom dimension appropriately when the user graduates/un-graduates from Roadmap to Dashboard, or vice versa

## Design
**Poppy**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9150%3A230102

**Oscar**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9150%3A229640

## Notes
- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by aloverso** [comment]
To be clear, once we do this story, we're removing the compliance text, yeah?

![image](https://user-images.githubusercontent.com/6563663/154338056-28a10e19-e961-4398-8641-c695f45c1e44.png)

@aaronvux @skeeJay @carye3

**Comment by skeeJay** [comment]
@aloverso Yes, that was only introduced because we did not have a graduation button at the bottom. I believe it should be totally removed. cc @Jesslax in case there's any reason I'm wrong.

**Comment by Jesslax** [comment]
@aloverso @skeeJay that sounds right to me, remove.

**Comment by aloverso** [comment]
@carye3 @fiorella-io can you export the green congratulations icon as an SVG for me

**Comment by aaronvux** [comment]
@aloverso I'm not being taken to Oscar onboarding.  It's taking me to the profile.  This is a new account.

https://user-images.githubusercontent.com/36163601/156226853-d04786a3-bc95-4021-9e4b-f40ca2429002.mov

**Comment by aaronvux** [comment]
Moving this one to deploy.
