### ISSUE TITLE
Require Industry for Poppy in Onboarding and Profile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1561]
As Poppy, I need the Industry field to be required in Onboarding and in my Profile so that I get a customized experience in the Navigator.

## Acceptance criteria
- Make Industry a required field in Poppy Onboarding and the Profile.
  - Error Message: Industry is a required field.
- The error message should be available in Netlify.

## Notes
- [x] Content Review
- [x] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux This change is ready for review

**Comment by aaronvux** [comment]
This looks good.  @CeciliaRam Can you please check that the error message is in Netlify?

**Comment by CeciliaRam** [comment]
@aaronvux reviewed. good to go.
