### ISSUE TITLE
Update Display Order of Opportunities

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1648]
As Oscar, I need to have opportunities displayed in an order that are more easily comprehendible so I can obtain information pertinent to my business quickly.

## Acceptance criteria
- certifications display at the top (For now that is just Veteran Owned Business)

funding programs display in the following order:
- prioritize based on the input in the column "status," items marked "deadline" should display first, followed by "first-come-first-served," followed by "open"
- alphabetically if more than one for each status (deadline, first-come-first-served and open)

## Notes
- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by Jesslax** [comment]
@mikewolfd this is not prioritize based on the input in the column "status," items marked "deadline" should display first, followed by "first-come-first-served," followed by "open"

**Comment by mikewolfd** [comment]
@Jesslax maybe it seems to be working for me? Wana take another look @Jesslax ?

**Comment by aaronvux** [comment]
@Jesslax please review

**Comment by Jesslax** [comment]
@mikewolfd  working, thank you!
