### ISSUE TITLE
Update Netlify Fields For Funding Display

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1649]
As a Content Administrator, I need to update the field labels for the display of Funding Opportunities in Netlify so I can make the tool easier to use.

## Acceptance criteria
- Update Business size label to, "Employee Required"
  - Values: Yes, N/A
- Update Preference Given label to "Preference for Opportunity Zone".
- Update Industry label to "Industry Sector".
- Remove Benefits field
- Remove Eligibility field
- Move Open Date and Due Date to the bottom of the list.
- ~~Industry Sector fields should populate with All if they are blank.~~

## Notes
- [ ] PO Approval

**Comment by aloverso** [comment]
Can we change the story title here to Funding instead of Opportunity, since we have now separated in the CMS the two concepts of "Funding" and "Certification" instead of grouping them under "Opportunity"

**Comment by aaronvux** [comment]
@aloverso updated.

**Comment by dsueltenfuss** [comment]
@Jesslax currently, if a funding isn't for a specific sector, the field is left blank
is there a reason switching from blank to All is needed?

**Comment by aloverso** [comment]
@dsueltenfuss the reason for switching to All from blank was discussed with @CeciliaRam here: https://njcio.slack.com/archives/C02AJKBCH38/p1644510775248829

**Comment by dsueltenfuss** [comment]
Spoke with @Jesslax 
We are going to spin the last bullet, Industry Sector fields should populate with All if they are blank., to a separate story #1844

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
@Jesslax please review.

**Comment by Jesslax** [comment]
@mikewolfd  Looks good, thanks
