### ISSUE TITLE
Certifications in Netlify Need the Same Fields as Tasks

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1650]
As a Content Admin, I need to have the same fields that are available for tasks in Netlify, available for Certifications so that I can easily use the application.

## Acceptance criteria

- Certification fields in Netlify should match what is available for tasks.

## Notes

- [ ] PO Approval

**Comment by aloverso** [comment]
Can we be more specific as to which fields? Right now they have nearly all the same fields, but the other Task fields seem irrelevant for Certifications, can we clarify?

Task fields:

-   id,
-   name,
-   urlSlug,
-   callToActionLink,
-   callToActionText,
-   postOnboardingQuestion,
-   required,

Certification fields:

-   id
-   name
-   urlSlug
-   callToActionLink
-   callToActionText
-   agency
-   applicableOwnershipTypes

As you can see, the only missing fields are `postOnboardingQuestion` and `required` - are these what are being referred to in the story? Those are very Task-specific so can you explain why we need those for Certifications?

**Comment by aaronvux** [comment]
@Jesslax can you please review Anne's comment above?

**Comment by Jesslax** [comment]
@aloverso right now we dont have a need for required or post onboarding questions for certifications, you are right. what you have listed for certification fields make sense to me.
