### ISSUE TITLE
Add Error Messages to Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1652]
As a Content Admin, in Netlify, I need to be able to view & edit error messages that display in the Navigator so I can ensure that they make sense to the user.

## Acceptance criteria

- Update Netlify to include error messages that appear in the Navigator where appropriate.

**Poppy Onboarding**
- Location
- Legal Structure

**Oscar Onboarding**
- Business Formation Date
- Business Name
- Industry Sector
- Number of Employees
- Location

**Business Formation**
- Business Name
- Business Suffix
- Business Start Date
- Business Address Line 1
- Business Zip Code
- Registered Agent ID Number
- Registered Agent Name
- Registered Agent Email
- Office Address Line 1
- Registered Agent City
- Registered Agent Zip Code
- Member Full Name
- Member Address Line 1
- Member City
- Member State
- Member Zip Code
- Signer Full Name
- Contact First Name
- Contact Last Name
- Contact Phone Number
- Payment Type

**Snackbar Errors**
- Add Snackbar messages if possible.

## Notes

- [ ] PO Approval

**Comment by aloverso** [comment]
In order to point this story, I would need it to be more specific about when the errors are occurring and what is meant by "where appropriate"

**Comment by aloverso** [comment]
Is this error messages in the app, or errors that occur while using Netlify? A little confused but perhaps we can talk this one over more

**Comment by aaronvux** [comment]
@aloverso It's error messages that appear in the Navigator.  Jess needs the ability to update them in Netlify.

**Comment by aloverso** [comment]
Got it. Is this part of a larger effort for us to transition from the typescript files in GitHub that currently have those error messages? Why move just the error messages? Is this for all error messages across the whole site?

**Comment by aaronvux** [comment]
I think we at least need to start adding new work that contains error messages to Netlify.  It's difficult to find the files in Github.  It would make life easier for Jess and C.  We can come back to adding all the existing messages to Netlify in another story if that's easier.

**Comment by dsueltenfuss** [comment]
These items were setup in Netlify as part of the TS migrations (#1823)
