### ISSUE TITLE
Task Format Improvements

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1672]
As a Navigator user, I need the ability to easily consume information on tasks screens so that I am not overwhelmed by large blocks of text.

## Acceptance criteria

- Add Issuing Agency & Form # & only display when populated
  - Add to Netlify
  - If either field is not populated, do not display that field.
- Update bullets within callout boxes (see designs)

## Designs

- [ ] [Desktop Design](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200323)
- [ ] [Mobile Design](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200629)

## Notes

- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by carye3** [comment]
@Jesslax

**Comment by carye3** [comment]
@aaronvux this was overlooked last sprint and needs to have acceptance criteria added

**Comment by aaronvux** [comment]
@namanaman does content have to be added for this to be tested?

**Comment by Jesslax** [comment]
In general, this looks great. But it's not working for special license screens, for example like the designs we have for Consumer Affairs - https://dev.navigator.business.nj.gov/tasks/apply-for-shop-license... I don't actually think we need for these screens since the button says it, but would like a design take @carye3

**Comment by namanaman** [comment]
Thanks @carye3 will update the callout rounding. Regarding the gray background on CTAs, currently aside from business formation, none of them have a gray background. Is this something needed in this ticket?

**Comment by namanaman** [comment]
@carye3 I added the rounded corners and made the CTA backgrounds gray.

**Comment by aaronvux** [comment]
@carye3 please review.

**Comment by carye3** [comment]
nice! lgtm @namanaman @aaronvux

**Comment by aaronvux** [comment]
Moving to deploy.
