### ISSUE TITLE
Add Other Certifications and Display Dynamically on the Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1695]
As Oscar, I need the ability to have Certifications dynamically displayed on the Dashboard so pertinent information to my business is easily accessible. 

## Acceptance criteria

- Onboarding

  - Business size is lower than 120 will see the SBE Certification on their Dashboard.

## Notes

- [x] PO Approval

**Comment by aaronvux** [comment]
This will happen automatically:
  - Minority or Woman in the Ownership field will see the MWB Certification on their Dashboard.
  - Disabled Veteran in the Ownership field will see the DVOB Certification on their Dashboard.

**Comment by FarazA22** [comment]
@Jesslax @aaronvux QQ, the veteran owned business certification markdown file is currently active. We are utilizing the  applicableOwnershipTypes key (image 1) to identify the possible dropdown values within the ownership dropdown that would display this certification. Since the SBE certification is based on the number of employees, I'd like to confirm if there is a use case that will result in populating the applicableOwnershipTypes key within the SBE markdown file (image 2).

<img width="481" alt="Screen Shot 2022-02-22 at 10 55 40 AM" src="https://user-images.githubusercontent.com/72581979/155169567-cda9290d-902f-4f2d-9400-52797596ab1b.png">

<img width="454" alt="Screen Shot 2022-02-22 at 11 02 36 AM" src="https://user-images.githubusercontent.com/72581979/155170908-03868975-6b39-4d10-90d3-ed8e05d27dd3.png">

**Comment by FarazA22** [comment]
@aaronvux @Jesslax Ready for Review

**Comment by Jesslax** [comment]
@FarazA22 this is not working for me. None of the other certifications are showing up

**Comment by Jesslax** [comment]
@FarazA22 when I have women or minority selected DVOB license still shows. When I have disabled veteran, mwbe still shows.

**Comment by FarazA22** [comment]
@Jesslax
We've added logic to show the certifications based on 1) applicableOwnershipTypes and 2) isSbe keys.

If applicableOwernshipTypes is empty (i.e. [ ]), it will show for everyone
To restrict it, you'll need to specify which ID it applies to (i.e. veteran-owned-business.md)

Note: if you wanted to show a small business certification for a specific ownershipType, you will need to fill applicableOwnershipType with that specific ID and have isSbe to equal true.

<img width="240" alt="Screen Shot 2022-02-25 at 2 51 44 PM" src="https://user-images.githubusercontent.com/72581979/155785731-69c8ca3e-85b4-40b1-b08d-d15bbde6542a.png">

**Comment by Jesslax** [comment]
OK, where do we do this?

Aaron's note suggest it will happen automatically?
I don't see this in netlify.

**Comment by dsueltenfuss** [comment]
@Jesslax its the last option on the Certification edit screen
![image](https://user-images.githubusercontent.com/3985977/155789797-ea0f5f37-7b99-4b8d-a5e7-9a7495c8290c.png)

**Comment by Jesslax** [comment]
@dsueltenfuss Thanks, the certifications folder wasn't showing for me in netlify before. But now updated and published. Just need to wait for it to show in dev to double-check it's working.

**Comment by FarazA22** [comment]
@Jesslax I forgot to add the isSbe dropdown within the CMS, adding it now. Should be in dev within the next 30 minutes.

**Comment by Jesslax** [comment]
@FarazA22 why does it need to be a drop down? I am not even sure how that would work? the other certifications relate to ownership, sbe doesn't. all the certifications seem to be working correctly now.

**Comment by FarazA22** [comment]
@Jesslax Within the CMS, there is another dropdown "For a small business" that will be available. By default, it's value is false; the SBE markdown has a value of true, all the others markdown files have a value of false.

If the value is true, then the logic to see if they are in fact a small business (<120) will be checked. 

As I mentioned above, if you wanted to show a small business certification for a specific ownershipType, you will need to fill applicableOwnershipType with that specific ID and have isSbe to equal true. This allows for a complex to be applied if needed.

**Comment by FarazA22** [comment]
@Jesslax it's a radio button, not a dropdown

**Comment by aaronvux** [comment]
Need to be able to complete onboarding to test.

**Comment by aaronvux** [comment]
This looks good. Moving to staging.
