### ISSUE TITLE
Date Picker Not Inputting Business Formation Date on New Account

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1705]
**Current Behavior:**

After creating a new account, choosing a business formation date from the date picker is not inputting the selection into the field, causing validation to fire.

**Expected Behavior:**

Date should be displayed in the field after clicking the date or clicking away after selection.

**Comment by dsueltenfuss** [comment]
I tried manually inputting a date for this field, and it triggered the validation until I used the picker.
