### ISSUE TITLE
Design: Reduce number of total Onboarding steps for Poppy

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1722]
**As** Poppy / Oscar
**I need to** be able to use a tool like Navigator with as few preliminary steps as possible
**So that** I can begin using its core features quickly and without additional cognitive load.

*Currently, with the guest checkout step, onboarding can span up to 6 step. Explore how to consolidate these steps or remove some*

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by carye3** [comment]
@Jesslax @skeeJay @aaronvux as discussed in design review today

**Comment by Jesslax** [comment]
@carye3 this is a feature scale tkt, since we are breaking up this work into smaller, one-by-one stories for each onboarding page or question, can we delete this tkt?
