### ISSUE TITLE
Graduation/Toggle: Add Modal Questions When Graduating from Roadmap to Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1734]
As Poppy, I need the ability to answer questions when I graduate to Oscar so I can have my experienced customized correctly on the Dashboard.

## Acceptance criteria
- Display modal window for Poppy when graduation button is clicked.
  - Business Formation Date: Only display for LLCs, LP, LLP, c-corp, or c-corp with s-tax designation, pre-populate if user has already done business formation form
  - Number of Employees
  - Industry Sector: Pre-populate the appropriate Sector that maps to the industry from Poppy onboarding, unless Other Industries was selected during Poppy onboarding.  Jess to provide Mapping
  - Ownership

## Analytics

Events:

- Click graduation button on Poppy Roadmap to bring up modal: `roadmap_graduate_button/click/view_graduation_modal`
- Successfully submit graduation modal form on Poppy Roadmap, bringing you to Oscar Dashboard: `graduation_modal/submit/prospective_roadmap_to_existing_dashboard`

https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

Custom Dimensions:

- Ensure that Persona custom dimension updates to "Existing" when the user successfully submits the modal form and completes the graduation to the Oscar Dashboard.

**Netlify**
- Ability to map the industry to the correct sector

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9225%3A173128

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by mikewolfd** [comment]
@aaronvux

**Comment by aaronvux** [comment]
Looks pretty good overall, but Business Formation Date is not pre-populating.

**Comment by fiorella-io** [comment]
Hi @mikewolfd, can we adjust the following:

1. Remove the left padding in the Continue button
![image](https://user-images.githubusercontent.com/91498500/156387540-cd2f2826-88ba-46ad-afc8-5ba10df139d8.png)

2. We also need to stack everything from top to bottom for mobile
![image](https://user-images.githubusercontent.com/91498500/156389724-dcc3e5dd-a1d3-4365-b189-fc57d9046351.png)

3. We can't have contextual information inside a modal. It appears behind it and I can't close it. It also disables the ability to type on any field when I have the contextual info slide-out open. 
![image](https://user-images.githubusercontent.com/91498500/156390086-c6dd51f9-2568-46c8-b971-30cfd005905f.png)


@aaronvux I'm not sure if the toggle is covered in this story, or if we should create a new one

**Comment by aaronvux** [comment]
@mikewolfd 
- If the user successfully formed their business through the Navigator, use the Business Start Date value to pre-populate the Business Start Date in the graduation modal window as a read only field.
  - In the Oscar profile, pre-populate the Business Start Date and make it a read only field.

**Comment by fiorella-io** [comment]
@mikewolfd @aaronvux One last thing. When I toggle to the dashboard, where I fill out every field, then toggle the roadmap, and back to the dashboard, should I see the modal? Can the user just be taken to the dashboard at this point?

**Comment by mikewolfd** [comment]
@aaronvux I just pushed the read-only and auto-filling work.

@fiorella-io I fixed the context info z-index, it should be ontop. We can create a story to change that behavior, but it's more involved.
In regarding to the stylings, this ticket was only for the modal, we can deal with those things in dev-design sync.

**Comment by aaronvux** [comment]
Business Date will now autopopulate after formation is complete and be read-only in the graduation modal and on the oscar dashboard.  Moving to deploy.
