### ISSUE TITLE
Replace Business Name & Make It Uneditable in the Profile on Completion of Business Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1735]
As Poppy, I need to have my Business Name added to my profile after I complete Business Formation so I know my Business Name has been officially filed.

## Acceptance criteria

- After Business Formation has been completed and the success page displayed, replace the Business Name to the user's profile as an uneditable field.
- Do not allow the user to edit the Business Name in Onboarding after Business Formation has been successfully completed.

## Notes

- [ ] PO Approval
- [ ] UX Review

**Comment by aaronvux** [comment]
Need to maintain replace functionality to support story #1204

**Comment by namanaman** [comment]
@aaronvux Ready for review, you can test the disabling, but it may be easier to test the replacing part after #1204 is complete

**Comment by aaronvux** [comment]
This is working in the profile.  Need to wait to approve until #1204 is complete to verify the replace functionality.

**Comment by aaronvux** [comment]
Will move this to deploy.  Any issues with the replace will need to be addressed as apart of 1204.
