### ISSUE TITLE
Create Splash Page From myNJ

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#1739]
As a Navigator User, I need to be able to navigate smoothly across the application so I have a pleasant experience.

## Acceptance Criteria
- Create splash page from myNJ (need design)
  - Use current available spinner.
  - Display Header and Footer.
- Oscar gets navigated to the dashboard
- Poppy and Dakota get navigated to the Roadmap.
- Redirects
  - myNJ>successful registration
  - myNJ>successful login

## Design
[Splash page (Desktop)](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13925%3A184850)

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Create a landing login page, for when the user is returning back from the MyNJ login process
This page should be able to determine where the user should be directed to, and also accept an incoming address if we want to direct the user to a specific page in the site
