### ISSUE TITLE
Date Picker in Oscar Onboarding 

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1752]
https://user-images.githubusercontent.com/36163601/154296271-5232ab7a-ccbc-4546-97a4-cc5dcb3349ce.mov

**Comment by mikewolfd** [comment]
https://github.com/mui/material-ui/issues/31247

**Comment by aaronvux** [comment]
Check status of bug in material UI in a week. Revisit if progress is not being made for us to address.

**Comment by mikewolfd** [comment]
Submitted a PR to MUI, waiting on them to review/merge things https://github.com/mui/mui-x/pull/4770/files

**Comment by mikewolfd** [comment]
Done, waiting on the release of https://github.com/mui/mui-x/pull/4827

**Comment by dsueltenfuss** [comment]
This will be fixed when the @mui/lab package upgrades the sub package for date pickers to - @mui/x-date-pickers@5.0.0-alpha.3
We are currently on @mui/x-date-pickers@5.0.0-alpha.1
