### ISSUE TITLE
Cannabis First Version: Add Cannabis Onboarding Question + Build Roadmaps with Ordinary Tasks

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1792]
As Poppy, I need the ability to obtain information for my Cannabis business so that I can comply with State regulations.

## Acceptance criteria
**Onboarding**
- Add Cannabis as an Industry to Poppy onboarding
  - Do not show Home Based Business questions
  - Description: A business that manufactures, delivers, or sells cannabis.
- Add Question: Which type of license do you plan to get?
  - Radio Button: Conditional or Annual (Contextual Links)

## For Jess and C

**Roadmap Conditional**
Plan your business 
Register and Form Your Business (dependent on legal structure)
After Registering Your Business
- Add: Determine if You are Eligible for Priority Status
- Add: Apply for Your Conditional Cannabis Permit
Before Opening Your Site
- Modify: Obtain Zoning Approval
- Add: Submit Your Conversion Cannabis License

**Roadmap Annual**
Plan your business 
Register and Form Your Business (dependent on legal structure)
After Registering Your Business
- Add: Determine if You are Eligible for Priority Status
- Modify: Obtain Zoning Approval
Before Opening Your Site
- Add: Apply for your Annual Cannabis License 

**Final Copy**
- After you complete this application, you will have:
  - A Cannabis license number
- CTA: TBD

## Additional Acceptance Criteria
- Works in Mobile
- 508 Compliant
- Follows Design
- Feature Flag - Production

## Design
**Desktop**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9387%3A157951

**Mobile**

**Prototype**

## Google Doc
https://docs.google.com/document/d/14qDBJRcttoM-4hVzgX9EZgm8wUiU6o8eyMF3bo0yzoQ/edit

## Notes

- [x] UX Review
- [x] PO Approval
- [x] Content Review

**Comment by aaronvux** [comment]
Consider adding Conditional or Annual question to Onboarding.  Would need to be added to Profile as well.

**Comment by aaronvux** [comment]
Split the story with onboarding question and information tasks with requirements checklist.

**Comment by aloverso** [comment]
@aaronvux @Jesslax  ready for review

**Comment by aaronvux** [comment]
Looks good to me.

**Comment by Jesslax** [comment]
@aaronvux @aloverso the conditional/annual needs to be required, if they don't make a selection there should be an error message. Alternatively, we could make a pre-selection for conditional, because that will be more common, and people who will get annual licenses will be more likely to know what to select, conditional is for more novice business. Other than that I just need to make some copy updates and change where some of the tasks arise in the roadmap, which I will do now.

**Comment by aaronvux** [comment]
@aloverso I vote for defaulting to conditional.  Seems like the easiest solution.

**Comment by aloverso** [comment]
@Jesslax @aaronvux the switch to default-to-conditional is now in dev, will move to staging

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please
Review

**Comment by fiorella-io** [comment]
@CeciliaRam Hi Ce, below are contextual links that need content:
- Diversity Owned Business -  "Determine if You are Eligible for Priority Status" task
- Entities of Interest
- Diversely-Owned Businesses Only

@aloverso 
This bullet looks off for "Apply for Your Annual Cannabis License" (annual), and the EIN contextual link needs content @CeciliaRam 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/91498500/157912781-16a4566d-0348-46c4-b6f1-1028af214871.png">

**Comment by Jesslax** [comment]
@CeciliaRam There is contextual information for those, I think I just linked it incorrectly.

**Comment by CeciliaRam** [comment]
@aaronvux contextual info looks good
