### ISSUE TITLE
Dashboard: Visual Treatment of Empty Calendar for Sole Proprietor/General Partnership

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1793]
## Acceptance criteria

- When Formation Date is blank, display the empty calendar state.
- Add to Netlify

## Detailed acceptance criteria

WHEN a user **starts as Poppy & graduates to Oscar**, with a **SP/GP legal structure**:
THEN do not display annual filing in calendar (even if they entered a Formation Date in graduation)

WHEN a **user starts as Poppy & graduates to Oscar**, with a **non SP/GP legal structure**
AND they entered a formation Date
THEN display annual filing date in calendar

WHEN a user **starts as Poppy & graduates to Oscar**, with a **non SP/GP legal structure**
AND they **did not** enter a formation Date
THEN do not display annual filing date in calendar because we don't know their formation date

---

WHEN a user **starts as Oscar** 
AND enters a Formation Date:
THEN we don't know their legal structure. We should show the calendar with the Annual Filing

WHEN a user **starts as Oscar** 
AND **does not** enter a Formation Date:
THEN do not show Annual Filing on the calendar because we don't know their formation date

## Design
[Desktop (1440px)](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9759%3A175099)
[Mobile (320px)](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9869%3A177982)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by skeeJay** [comment]
The UX within onboarding component of this needs design and definition. cc @carye3 @fiorella-io

**Comment by aaronvux** [comment]
@fiorella-io @carye3 please attach the winning design with the Figma link.

**Comment by fiorella-io** [comment]
Designs have been added

**Comment by aaronvux** [comment]
@skeeJay we can adjust the story the title and split the formation date piece out.

**Comment by skeeJay** [comment]
@aaronvux Thanks. If you could actually create a discovery ticket for it, it'll make sure we remember to prioritize some consideration of what the issue was by @Jesslax / @carye3 / @fiorella-io and how to design a fix. Thanks.

**Comment by aaronvux** [comment]
@mikewolfd not seeing the design Incognito

<img width="1440" alt="Screen Shot 2022-03-21 at 6 56 25 PM" src="https://user-images.githubusercontent.com/36163601/159376559-6b04a703-6cca-40bb-aa08-16463124c2c0.png">
.

**Comment by mikewolfd** [comment]
try again
![Screen Shot 2022-03-21 at 7 20 00 PM](https://user-images.githubusercontent.com/12499270/159378631-849e6d21-f5e8-4e83-82f1-4c63f7c46178.png)
?

**Comment by aaronvux** [comment]
@mikewolfd I'm seeing it now.  One thing I noticed though is if I change my legal structure to SP after I've been an LLC with a start date, I still see an Annual Report indicator on the calendar.

**Comment by aaronvux** [comment]
@mikewolfd If I go through onboarding as Oscar, input a Business State Date, finish onboarding, I don't get the calendar.  I'm getting the empty state.

@Jesslax cc

**Comment by aaronvux** [comment]
Looks good now.  Moving to deploy.
