### ISSUE TITLE
Dashboard:  Add Due Date & Program Status to Opportunities Detail Screen

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1794]
As Oscar, I need to be able to see due dates and statuses of Opportunities on the detail screens so I can understand the urgency at which I need to apply.

## Acceptance criteria

**Oscar Details Screens**
- Add Due Date Due 
- Add Status
- Fields can be displayed together or individually. 

## Designs
[Desktop (1440px)](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9704%3A175817)
[Mobile (320px)](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9869%3A178976)

## Notes

- [x] PO Approval
- [x] UX Review
- [ ] Content Review

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please attach the design

**Comment by fiorella-io** [comment]
Designs have been added

**Comment by aaronvux** [comment]
This looks good, but I can't find anything with both a status and a due date.  @carye3 @fiorella-io @Jesslax @CeciliaRam please review.

**Comment by aaronvux** [comment]
This will be pushed to staging, then deployed to prod after the reviews are complete so that the team can finish their reviews and business formation can move forward.

**Comment by carye3** [comment]
lgtm @aaronvux tho same, can't assess whether status and due date next to each other looks ok

**Comment by aaronvux** [comment]
@CeciliaRam Is there an opportunity that has both a status and due date?

**Comment by CeciliaRam** [comment]
@aaronvux https://docs.google.com/spreadsheets/d/1sV0lQ5BJbUoJK3w38bw_SuwaBeJNtFwf/edit#gid=77113362
Line 14 is an expired funding opportunity. Due date 12/31/96, status Closed. Everything else is open indefinitely with rolling applications

**Comment by aaronvux** [comment]
@CeciliaRam iI tried to find the Recycling Tax Credit, but I don't see it in the list.  My industry is construction.

**Comment by Jesslax** [comment]
@aaronvux the Angel Investor Tax Credit has a deadline. All the programs have a status listed, but I don't want all the statuses displayed to the user. Maybe only the first-come-first served label.

**Comment by Jesslax** [comment]
@aaronvux @CeciliaRam the Treasury tax credits, like the recycling tax credit is not in our cms yet, we still are waiting to hear back from Treasury before we upload them to the CMS
