### ISSUE TITLE
Dashboard: Change Width of Calendar and Opportunities Columns

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1804]
As Poppy, I need a better treatment of the width of the calendar and opportunities so that the opportunities are easier to read.

## Acceptance criteria
- Adjust the width of the calendar and opportunities column to match the design
  - Absolute Page Width
  - Calendar Width
  - Opportunities Width
- Opportunities will continue to be independently scrollable.

## Design
<img width="644" alt="Screen Shot 2022-02-22 at 4 03 31 PM" src="https://user-images.githubusercontent.com/36163601/155219002-f66a0dff-13e4-4938-9e8d-b4774492d5eb.png">

[Wide width w/ scroll bar](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9744%3A177249)

## Notes

- [x] UX Review
- [x] PO Approval

**Comment by namanaman** [comment]
@carye3 @fiorella-io From the wider Dashboard V2 design on Figma, I see there is 142px padding on the left and 92px on the right of the page. How much padding do we want here on the left/right of the absolute page?

**Comment by namanaman** [comment]
@carye3 @fiorella-io Actually I saw the updated design for the later styling ticket, I think that answers the question

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please review.

**Comment by fiorella-io** [comment]
Looks good. Thank you @namanaman!
