### ISSUE TITLE
Dashboard: Calendar List View on Mobile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1805]
As a mobile Oscar user, I need to see my the Calendar events on my Dashboard displayed as a list of upcoming tasks so I can easily understand the information on my Dashboard.

## Acceptance criteria
- Header copy will remain the same between desktop and mobile.  Jess/C to update as necessary.
- Display events as the Date and Task link.
  - Clicking the task link will take the user to the task page.
## Design
**Mobile**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9431%3A163741

## Notes
- [x] UX Review
- [x] PO Approval

**Comment by aaronvux** [comment]
Need to handle long task names in the design.

**Comment by FarazA22** [comment]
@aaronvux @carye3 

The header copy in figma changed from "My Calendar" to "Upcoming", the AC mentions it's the same. Can you clarify which one we are using? If it is the same, do we want to have two separate sections that C/Jess can update for the calendar header in the CMS (i.e. one for desktop, and one for mobile)?

Also, the AC mentions displaying the task status. Currently, the user does not have the ability to view/update their progress for filings. We only show the due date if it's available. If we plan to display the task status, we will need a ticket to make those changes / this will be blocked until that work is done.

Can you clarify how the UI would look when the filing name wraps?

**Comment by FarazA22** [comment]
@aaronvux Can you confirm the logic for the link. Based on the design, it is the Annual Filing Name + Year it is due (i.e. Annual Report 2022). Is the year necessary? How helpful is it for quarterly filings?

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
Looks good to me.  @carye3 @fiorella-io please review.

**Comment by carye3** [comment]
@namanaman @FarazA22  please add a grey line below "Upcoming" (similar to "Opportunities" below) and bottom-align the tooltip to the text of "Upcoming"
<img width="515" alt="Screen Shot 2022-03-10 at 1 43 14 PM" src="https://user-images.githubusercontent.com/62653834/157734369-2d30e918-b803-4bf1-98a9-ee3bfc0c5330.png">
