### ISSUE TITLE
??Apply for Your Cannabis Permit Task??

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1821]
## Acceptance criteria
- Dependency: Decide Your Cannabis License Type, Determine if You Are Eligible for Priority Status, Zoning Approval, Get your NJ Tax ID
- Copy: If you are looking to get a cannabis manufacturing, delivery or retail license, you need to apply with the Cannabis Regulatory Commission. Applications are reviewed on a rolling basis, you can apply at any time. Get a head start by viewing the[ application guide](https://www.nj.gov/cannabis/documents/businesses/personal-use/Application%20Guide.pdf).
  - Answer a few questions and we can tell you all the documentation you’ll need to apply for your license.

## Notes

- [ ]

**Comment by aaronvux** [comment]
@Jesslax is this task still relevant

**Comment by Jesslax** [comment]
I don't think so
