### ISSUE TITLE
Implement API to serve funding opportunities

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#1825]
Implement an API to read the funding opportunities from the content folder. 
This API is intended for displaying the funding opportunities on business.nj.gov, and will replace the existing Airtable integration in webflow

**Comment by aaronvux** [comment]
@dsueltenfuss @mikewolfd is there anymore info that needs to be added to this story in order to point it?

**Comment by dltinnovate** [comment]
Attached is the article and resources for Webflow's CMS API.

[Webflow Developers- CMS API](https://developers.webflow.com/#cms-api-reference)
