### ISSUE TITLE
Add Opportunities Count to Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1836]
As Oscar, I need to see a count of Opportunities so that I can quickly understand how many are available to me without having to scroll the list.

## Acceptance criteria

- Add Total Opportunities Count to the Oscar Dashboard next to the Opportunities Heading

## Design

**Desktop**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9703%3A173672

**Mobile**

## Notes

- [x] UX Review
- [x] PO Approval

**Comment by namanaman** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
This looks good.  @carye3 @fiorella-io please review.

**Comment by fiorella-io** [comment]
Looks good to me too.

**Comment by namanaman** [comment]
@carye3 Done!

**Comment by carye3** [comment]
ty @namanaman ! the grey line needs to be pulled in a bit more
<img width="490" alt="Screen Shot 2022-03-10 at 2 28 26 PM" src="https://user-images.githubusercontent.com/62653834/157739869-3f520c5c-a547-4efc-a8f1-39ad23bf5400.png">

**Comment by namanaman** [comment]
@carye3 Oops, that's fixed now

**Comment by carye3** [comment]
perf! lgtm
