### ISSUE TITLE
Add Hide Icon to Opportunities Cards & Hidden Opportunities Accordion

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1837]
As Oscar, I need the ability to hide Opportunities on my Dashboard so that I can focus on the Opportunities that are most important to my business.

## Acceptance criteria
- Add Hide icon to the Opportunities cards.
  - Clicking the icon will remove the card from the list and move it to the Hidden Opportunities accordion
- Add Hidden Opportunities Accordion
  - Closed By Default
  - Display Number of Hidden Opportunities
  - Opening the Accordion will display the Hidden Opportunities
  - Hidden Opportunities are ordered by Fundings first, then Certifications, alphabetical within each group
  - Add Unhide icon to the Hidden Opportunities Cards
- Display empty state in Opportunities column when all Opportunities have been hidden.
- Counter updates to display only the visible opportunities when the user hides or unhides the card.

## Design

**Desktop**

UnHidden:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9703%3A173672

Hidden:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9703%3A173914

Hover State:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9703%3A174251

**Mobile**

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@Jesslax @carye3 @fiorella-io should there be any order to how the hidden opportunities display? ie, should it still be certifications then fundings, like in the visible ones?

**Comment by aloverso** [comment]
@aaronvux @carye3 @fiorella-io I see the acceptance criteria "Display empty state in Opportunities column when all Opportunities have been hidden." but I can't find a design for this. What is the empty state supposed to look like?

**Comment by aaronvux** [comment]
@aloverso @carye3  Attached the sv
![Recommendations](https://user-images.githubusercontent.com/36163601/158609705-d2aa5e7f-e0d1-41e6-8785-bc5d95aabd14.svg)

![trophy-illustration](https://user-images.githubusercontent.com/36163601/158609923-b32ce944-ee0b-4cb7-8556-77e9db2f976a.svg)

Figma
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9759%3A175288

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@carye3 please review.  Looks good to em.

**Comment by carye3** [comment]
@aaronvux @aloverso looks great!

Flagging for @FarazA22 @fiorella-io we might need more feedback to the user showing where these opportunities are going (maybe a snackbar?) after they click hide
- [ ] Design Chore: Improve Hide Button User Feedback
