### ISSUE TITLE
Tasks displaying as Required even though they are not Required in Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1853]
These screens should not be required.

https://dev.navigator.business.nj.gov/tasks/town-mercantile-license
https://dev.navigator.business.nj.gov/tasks/get-insurance

**Comment by aloverso** [comment]
@Jesslax @aaronvux ready for reviews so that we can do this release

**Comment by Jesslax** [comment]
Looks good now, thanks!
