### ISSUE TITLE
Add Netlify preview for post-onboarding content

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#1854]
Be able to see what the post-onboarding question will look like in the Netlify CMS (ie, green box, etc)

**Comment by Jesslax** [comment]
Thanks @aloverso! Doesn't need to happen this sprint!

**Comment by aaronvux** [comment]
@aloverso @kmelefsky pulled this one into the sprint.

**Comment by aaronvux** [comment]
@aloverso @kmelefsky missed Jess's comment.  I'll leave it here for now and if it doesn't get done this sprint it's ok.

**Comment by FarazA22** [comment]
@aaronvux Ready for review.

**Comment by Jesslax** [comment]
@FarazA22 still displaying a bit off for me: 
![image](https://user-images.githubusercontent.com/78366346/157461554-943ff706-b018-4bbd-94b8-164107000433.png)

**Comment by kmelefsky** [comment]
moving to ready to deploy
