### ISSUE TITLE
Content: Tweaks to tasks

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1877]
1) Apply for a Certified Public Accounting License is missing "Application Needs" please add
2) Massage License is missing "Application Needs" please add

**Comment by CeciliaRam** [comment]
Tasks reviewed and edited. We will have to revisit the CPA license application needs. Consumer Affairs currently has it under review (we dont have access to it and they didn't have much to give us other than the requirements we have already listed)
