### ISSUE TITLE
Design highlighting Navigator on B.NJ.gov

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#189]
Activities include:

- [ ]

**Comment by Jesslax** [comment]
@skeeJay should we fold this into tkt 388? Or do we want to wait longer before we put the Navigator up on the site?

**Comment by skeeJay** [comment]
@Jesslax We need to wait before doing that. We can design with a place for it in mind though.

**Comment by Jesslax** [comment]
@skeeJay Sounds good
