### ISSUE TITLE
Favicon Not Displaying in Production

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1907]
Favicon Not Displaying in Production

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review
Icon was cached at the WAF level. It's been reset, and now displays correctly
You may need to do a hard reload and empty cache to have it show on your machine
![image](https://user-images.githubusercontent.com/3985977/156377309-89309909-6766-4f75-98fa-7af6136755ef.png)

**Comment by aaronvux** [comment]
@dsueltenfuss it didn't work unless I'm in a cognito window.  My concern about the cache clearing is that anyone who has already been to the site will not know to do that.

**Comment by dsueltenfuss** [comment]
@aaronvux  It will clear/reset over time for everyone.
The WAF team ahs adjusted the settings to no longer cache that favicon, so it will no longer cache there.
