### ISSUE TITLE
Improve Last Step in Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1909]
As a Navigator user, I need to have a better experience with my email address is being validated on the last step of onboarding so that I know what I did wrong.

## Acceptance criteria
- Use in-line validation to validate that Email and Confirm Email fields have an @ sign and "."
  - Email Addresses must match and be valid
- When clicking the Submit button, scroll the user to the top of the page if an error has occurred.
- Update Full Name validation message to "Full Name is required".
## Notes

- [ ] PO Approval
- [ ] UX Review

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
@FarazA22 not seeing the proper validation
<img width="736" alt="Screen Shot 2022-04-14 at 2 55 10 PM" src="https://user-images.githubusercontent.com/36163601/163457894-7998d381-55c1-49ae-ad9a-bd2f11655b33.png">

**Comment by FarazA22** [comment]
Note for discussion - Could content be updated to state 'please enter matching validate email'

**Comment by aaronvux** [comment]
@fiorella-io @carye3 please review. LGTM

**Comment by carye3** [comment]
LGTM @aaronvux @FarazA22
