### ISSUE TITLE
Update Business City Field to Use Location Dropdown in Business Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1919]
As Poppy, I need the Business City field to be more consistent with the fields around it so I can easily read it.

## Acceptance criteria

- Use the Location component for the Business City
- Update the profile with the selected location value if the user successfully moves to the next page.

## Notes

- [ ] PO Approval
- [ ] UX Review

**Comment by aaronvux** [comment]
Looks good.  @carye3 @fiorella-io please review

**Comment by fiorella-io** [comment]
Looks good to me too
