### ISSUE TITLE
Research and spec adding first three municipalities

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#192]
Activities include:

- [ ] Newark
- [ ] Jersey City
- [ ] Cherry Hill

Airtable:
https://airtable.com/tbl2UQwdYjegxRUXG/viwpMoKTJmf1Ngx5z?blocks=hide

Google Doc:
https://docs.google.com/document/d/1hAsnDnxjgYpqfBId6w_d2S3VAHfhWEzTxhDztqIVbv4/edit#heading=h.t7srdtb4shx0

**Comment by aaronvux** [comment]
Need to meet with Joe to discuss next steps.  Schedule time week of 8/23.

**Comment by aaronvux** [comment]
Review Google Doc and Airtable week of 8/23.
