### ISSUE TITLE
Update Business Name Search Functionality

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1920]
As Poppy, I need an improved experience in the Business Name Search step of Business Formation so that it is easy to find a name for my business.

## Acceptance criteria
- If there is a Business Name in the user's profile, pre-populate that value in the Business Name Search field.
- After a successful Business Name search, do not display the update profile link in the message
  - When the user clicks the, "Continue Forming My Business" button, save the Business Name to the user's profile.
- Clicking the Edit link in the Business Name field will take the user back to the Business Name Search step with the current business name populated in the field. The user must check the availability again.

## Notes

- [x] PO Approval
- [x] UX Review

**Comment by fiorella-io** [comment]
Everything looks good to me
