### ISSUE TITLE
Add Statutory Fee to Payment Step of Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1930]
As Poppy, I need to see the Statutory Fee on the Payment page so that I see an accurate amount when I pay on the NIC USA site for my Formation Documents.

## Acceptance criteria

- Add $6.50 to the Business Formation Filing document on the Payment page.
  - Total fee will be $131.50

## Notes
- [ ] PO Approval
- [ ] UX Review

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam This is a content change.

**Comment by FarazA22** [comment]
@aaronvux Should we move this to 'In Review' since no logic is required.

**Comment by aaronvux** [comment]
It's a placeholder.  I'd like to keep it in the current sprint column until we hear back from Treasury.  @skeeJay please include this in the touchpoint with treasury if we have to include the additional statutory fee in Production.

**Comment by skeeJay** [comment]
@aaronvux Does the answer for this come from NIC/Michael LeBlanc or Treasury/Pete Lowicki?
