### ISSUE TITLE
Entity ID is editable in Oscar Profile screen after forming and graduation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1963]
Steps:

1. Form a business.
2. Graduate
3. Go to Oscar Profile
4. Entity ID is editable

## Acceptance Criteria
- Make Entity ID a disabled field if the user has formed through the Navigator and then graduates to Oscar.

**Comment by aaronvux** [comment]
@aloverso here's the bug.  @kmelefsky moved this one into the sprint

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
Looks good.  Moving to deploy.
