### ISSUE TITLE
Add Checkbox To Signer Names

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1997]
As Poppy, I need I need a checkbox next to each signer name so that I can affirm I am a signer for legal purposes.

## Acceptance Criteria
- Add checkbox to each Signer Name
  - Default to Unchecked.
  - Display Validation Message when checkbox is not checked and when Signer Name is populated and the user clicks continue to move to the next page.

## Additional Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant

## Design

[Desktop](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10127%3A183342)
[Desktop / Error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10164%3A184019)
[Mobile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10177%3A185265)
[Mobile / Error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10177%3A185594)

## Notes
- [ ] UX Review
- [x] PO Approval

**Comment by carye3** [comment]
@aaronvux designs added

**Comment by aloverso** [comment]
@carye3 @fiorella-io what does this look like on mobile for Additional Signer rows - where does the trash can icon fit in on mobile?

**Comment by carye3** [comment]
ty @aloverso [here's a figma file](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10177%3A185594)

<img width="327" alt="image" src="https://user-images.githubusercontent.com/62653834/159013258-71d5afe6-f77c-41f2-8363-6306a2e26364.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/62653834/159013210-8c1a3949-c4d9-44ed-ab91-8eda3c18e67e.png">

**Comment by aloverso** [comment]
@carye3 I wanted to confirm that the `Signature*` label should show up for every additional signature row, labelling every checkbox, same as we have a new `Signer Full Name` label for each row? (as opposed to just labelling the column once at the top)

![image](https://user-images.githubusercontent.com/6563663/159031181-c71918ee-8698-43d1-a7b4-6a43791fb2dc.png)

**Comment by aaronvux** [comment]
@aloverso I believe we agreed that we would ignore the signer if both the name and checkbox are not populated and not include that field in the final list.

**Comment by aaronvux** [comment]
@aloverso thank you!

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
Looks good.  Moving to deploy.

**Comment by aaronvux** [comment]
@carye3 this is moving to staging and will be under the feature flag.  Moved this forward to keep things moving with Treasury, but please review.

**Comment by carye3** [comment]
Lgtm @aaronvux -- there are a couple design tweaks (below) but those can also wait till the next design iteration of these (tbd design review Monday)

<img width="656" alt="Screen Shot 2022-03-25 at 11 52 59 AM" src="https://user-images.githubusercontent.com/62653834/160156098-60302d7d-d561-4938-b3b1-757952457e6a.png">
