### ISSUE TITLE
Tooltip for Business Suffix and Start Date

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2001]
As Poppy, I need a way to get more information about Business Suffix and Start Date when forming my business through the Navigator so that I am well informed about information I am providing to the State.

## Acceptance criteria
- To the right of the labels, vertically aligned
- Add Tooltips to Business Suffix and Business Start Date
- Tool tip copy for Business Suffix: "The NJ Department of Treasury often refers to this as a "Business Designator""
- Tool tip copy for Business Start Date: "The NJ Department of Treasury often refers to this as an "Effective Date""

## Additional Acceptance Criteria
- Works in Mobile
- 508 Compliant
- Follow current implementation of the black question mark tool tip on the cosmetology license status task

## Notes
- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
Looks good to me.  @carye3 @fiorella-io @CeciliaRam please review

**Comment by carye3** [comment]
lgtm!
