### ISSUE TITLE
Design: Add NAICS code to Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2002]
Add NAICS code to Formation

As Treasury, I need to collect NAICS codes from business formation submissions in order to conduct analysis of business formation data.

As Poppy / Oscar, I need to reference my NAICS code when...?
- Government contractor persona?

## Considerations
- Dumber Version: add number yourself
- Dumb Version: Search field for identifying NAICS category
- Smart Version: Navigator identifies your NAICS automatically

**Comment by carye3** [comment]
@Jesslax just wanted to confirm the user story i wrote above... this has value primarily for Treasury, right?

**Comment by carye3** [comment]
with some edge use cases for poppy / oscar

**Comment by carye3** [comment]
Shouldn't add to onboarding. Should be able to detect if they chose an industry (figure that out via discussion with Jess, V, Neha); if they selected Generic Roadmap, there might need to be a question in their profile or Opportunities section.
