### ISSUE TITLE
Remove Business Name from Poppy Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2004]
As a Poppy, I don't want to input my business name during onboarding because it complicates the task and I might not know what my business name is.

## Acceptance Criteria
- Remove Business Name from Poppy Onboarding.
- Update step numbers.
- Update Poppy Roadmap to use the user's Full Name instead of Business Name.  Same as Oscar Dashboard.
- Jess to update the copy in the Profile for Business Name.

## Notes

- [ ] PO Approval
- [ ] Content Review

**Comment by aaronvux** [comment]
Removing Design tasks: 
- Research a better way to capture Business Name.
- Give confidence and comprehension to the user about the status of their Business Name.

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aaronvux still seeing the old roadmap header for Poppy.
AC:
- Update Poppy Roadmap to use the user's Full Name instead of Business Name. Same as Oscar Dashboard.

**Comment by aloverso** [comment]
@aaronvux  I thought that meant that the header should use the Full Name if the user hasn't set a business name. If you unset the business name you'll the full name header like Oscar Dashboard

**Comment by aaronvux** [comment]
@carye3 @Jesslax Do we want to keep the header consistent between Oscar and Poppy, even if the user adds a Business Name through the profile.  See Anne's comment above.

**Comment by Jesslax** [comment]
I think it should be the users full name, which is what I understand happens for Oscar

**Comment by aaronvux** [comment]
@aloverso can we make it so it always displays the user's Full Name please?

**Comment by aloverso** [comment]
@aaronvux fixed

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam Please review.  There's a bullet in the AC for copy to be updated in the Profile for Business Name.
