### ISSUE TITLE
SP/GP in Oscar Onboarding Should Not Be Asked for EID/Filing Date

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2008]
As Oscar, I need to be able to communicate if I am an SP or GP so that I don't think I need to input a Formation Date during Onboarding.

## Tasks:
-  Add Legal Structure question & dropdown if Oscar is selected in step 1 of onboarding: 
- If the user selects SP or GP, do not display Business Formation date & Entity ID question (Step 2) in onboarding.
- Update the step numbers correctly when step has been skipped.

## Designs
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10797%3A201987

## Notes

- [x] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Removed 4 point label from the ticket for Discovery.

**Comment by aaronvux** [comment]
Concerns about Ethan persona.  Revisit design in the next sprint.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io LGTM.  please review.

**Comment by fiorella-io** [comment]
LGMT
