### ISSUE TITLE
Design: Add Notifications to Profile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2019]
Design the ability to manage notifications from the Profile page for Oscar and Poppy.

**Comment by Jesslax** [comment]
@carye3 @aaronvux what is this?

**Comment by aaronvux** [comment]
@Jesslax I believe it was to add texting or email notifications

**Comment by Jesslax** [comment]
Hmm, okay, I think we can move this to unsure or delete. @aaronvux
