### ISSUE TITLE
User is able to add a member with an incomplete address and proceed with business formation flow

### ISSUE THREAD

**Issue by FarazA22** [newjersey/navigator.business.nj.gov#2073]
**Current Behavior:**

Given that I have an address saved to my Chrome Profile and I'm on the members modal (business formation / llc). When I select an address that has a shorthand code for my state in lower case, the state dropdown does not correctly autofill and I'm able to add the member with a missing state.

 
<img width="532" alt="Screen Shot 2022-03-21 at 4 21 52 PM" src="https://user-images.githubusercontent.com/72581979/159357639-2ac97ed3-04ce-460b-b47b-8ac4de1ef087.png">
<img width="536" alt="Screen Shot 2022-03-21 at 4 22 03 PM" src="https://user-images.githubusercontent.com/72581979/159357645-3c73b340-4da1-43fd-9ca6-73436de447b7.png">
<img width="495" alt="Screen Shot 2022-03-21 at 4 24 42 PM" src="https://user-images.githubusercontent.com/72581979/159357727-714808bc-b871-4d71-b3f2-f81c836772f3.png">

**Expected Behavior:**

There should be an error thrown if the state dropdown is not filled.

**Steps to Reproduce:**
1. Save an address to the chrome profile
2. Use the auto-complete feature to auto populate an address with a lower case state
3. Add the member to the members table.

**Comment by FarazA22** [comment]
@aaronvux Found a bug.

**Comment by aaronvux** [comment]
@FarazA22 I can reproduce this.  @skeeJay Should we pull this into the sprint?

**Comment by aaronvux** [comment]
@FarazA22 I type the letter d in the dropdown but don't click anything in the list, then click Add Member button, I can still progress without a value in the state field.

**Comment by FarazA22** [comment]
Fixed

**Comment by aaronvux** [comment]
Working now.  Thanks @FarazA22
