### ISSUE TITLE
UX Updates to Guest Checkout

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2076]
One more request: 

**Clicking on restricted detail screen brings up registration modal**. I'm noticing that you only get a modal after entering a restricted detail screen (eg forms), but if you'd mistakenly closed it, you are no longer provided with feedback with why that detail screen is restricted.
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/62653834/159342597-5bc486b7-3c9c-46d6-96f9-c1df59e88146.png">

- Remove icon from mobile <img width="498" alt="Screen Shot 2022-03-21 at 2 27 12 PM" src="https://user-images.githubusercontent.com/62653834/159340358-8000cdf1-3c58-4de9-813f-afff72dae949.png">

**Comment by mikewolfd** [comment]
@carye3 that icon has been removed from mobile though?

In regards to the first point, that would require a design, like what would you prefer to happen?
