### ISSUE TITLE
Update "Apply for Your Conditional/Annual License" Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2082]
As Poppy, I need the ability to see specific information on the Apply for Your Conditional/Annual license task so that I understand the requirements correctly.

## Acceptance Criteria

**Apply for Your Cannabis Conditional/Annual License** (TWO SEPARATE TASKS)
**Business Size Section**
- Are you a microbusiness?
  - Radio Button: Yes, I’m a microbusiness or  No, I’m a standard business (Contextual Links) 
 
**Priority Status Section**
- Based on your preferences in Determine if You Are Eligible for Priority Status, you are eligible as the following:(auto-populate from previous question if there is a value)
  - Multi-select buttons: Diversely-owned business, Impact Zone business, social equity business (SBE), include Contextual Links
  - Pre-populate from previous Priority Status task selections
  - If the user selects a Priority Status that they did not previously choose, display the Eligibility modal.  Clicking I am eligible will close the modal and leave the checkbox checked.  Clicking the link or I'm not sure button will send the user back to the Priority Status task with the checkbox unchecked.
  - If None of the Above was selected, do not show checkboxes.  Display copy: "You did not select any priority status designations."

NOTE on checking/unchecking priority status manually: (per convo with @aaronvux @fiorella-io @aloverso)
Every time a user visits the page, it will re-calculate which checkboxes should be checked based on the Determine Your Priority Status task. If a user manually checks or unchecks any, it will change appropriately, but will not save that override.
 
**Apply for Your Cannabis Conditional/Annual License Question Selection Logic**
- When the user clicks the View Requirements button, accordion section displays with the logic below:
- If the user selects Standard Business:
  - Display specific content for Standard business: (Content Goes Here)
- If the user selects microbusiness, display:
  - Display specific content for Microbusiness:  (Content Goes Here)
- If the user selects Diversely-Owned Businesses display:
  - Display specific content for Diversely-Owned Business:  (Content Goes Here)
- If the user selects Impact Zone Businesses display:
  - Display specific content for Impact Zone Businesses:  (Content Goes Here)
- If the user selects Social Equity Businesses display:
  - Display specific content for Social Equity Businesses:  (Content Goes Here)

**Content Mapping**
- Content will be mapped to the appropriate accordion in Step 2.  Accordions in step 2 are a separate story.

## Design
Desktop Step 1 - Status Pre-populated from Previous Task 
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11545%3A185437

Desktop Step 1 - All Statuses Selected
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11545%3A185758

Desktop Step 1 - Eligibility Modal
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11545%3A186331

Desktop Step 1 - No Priority Status
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11545%3A186081

Desktop Step 2 - View Requirements
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11545%3A186363

## Analytics
**ADD: Both Conditional and Annual**
cannabis_license_form_microbusiness_question/submit/yes_I_m_a_microbusiness
cannabis_license_form_microbusiness_question/submit/no_I_m_a_standard_business
cannabis_license_form_priority_status_diversity_checkbox/submit/diversely_owned_business
cannabis_license_form_priority_status_impact_checkbox/submit/impact_zone_business
cannabis_license_form_priority_status_social_equity_checkbox/submit/social_equity_business
cannabis_license_form/click/view_requirements

**Comment by aaronvux** [comment]
REmoved:
- If conditional license is selected add:
  - Proof that each owner of the conditional license has for the immediately preceding taxable year, an adjusted gross income of no more than $200,000, or no more than $400,000 if filing jointly with another individual
- If annual license is selected add,
  - A site plan of the proposed location, including a floor plan and a description of the suitability of the location, which may include renderings, architectural plans, or engineering plans
  - Evidence of compliance with local codes and ordinances for the proposed location
Zoning approval, which shall consist of a letter or affidavit from appropriate municipal officials that the location will conform to municipal zoning requirements allowing for activities related to the operations of the proposed cannabis cultivator, cannabis manufacturer, or cannabis retailer, as will be conducted at the proposed cannabis business premises, and any variances granted concerning the operation of a cannabis business.
  - Proof of local support for the license applicant that is compliant with Section VIII of the [Notice of Application Acceptance](https://www.nj.gov/cannabis/documents/businesses/personal-use/Final%20Notice%20of%20Application%20Acceptance.pdf), and which shall be demonstrated by a resolution adopted by the municipality's governing body, or where the municipality has no governing body, a written letter of support from the municipality’s executive;
  - Documentation demonstrating that the license applicant will have final site control of the premises upon approval of the application;

**Comment by aaronvux** [comment]
@aaronvux most likely need to add accordion functionality to this story unless we just show a massive list on the requirements step.

**Comment by aloverso** [comment]
hey @fiorella-io I noticed that the modal design here doesn't match all our other modals, can we re-use our existing modal design with the grey bar on the bottom?

![image](https://user-images.githubusercontent.com/6563663/164772327-54734f4e-0eda-4cc9-816b-41757276fafd.png)

**Comment by fiorella-io** [comment]
@aloverso please use our existing modal with the grey bottom and disregard this design.

**Comment by aloverso** [comment]
@Jesslax @CeciliaRam where can I find the content for the second tab?

**Comment by Jesslax** [comment]
@aloverso the copy is in the existing file:
For conditional: https://dev.navigator.business.nj.gov/tasks/conditional-permit-cannabis
For annual: https://dev.navigator.business.nj.gov/tasks/annual-license-cannabis
The dynamic headers are bolded already, i.e the copy reads: Social Equity Businesses Only: A [notarized statement](https://www.nj.gov/cannabis/documents/businesses/personal-use/Certification%20of%20SEB%20FINAL%2012.13.21.pdf) by the owner(s) that they meet the criteria for a and documentation (such as a tax return) to prove residency) In that case, the header would be Social Equity Business, and the checkbox and related copy is the content after the :

**Comment by aloverso** [comment]
thanks. in what ways are the annual/conditional license content different?

**Comment by aloverso** [comment]
@aaronvux does clicking "view requirements" to get to the 2nd tab automatically update status to "in-progress" like the previous cannabis story?

**Comment by aaronvux** [comment]
@aloverso I'm not sure.  @Jesslax @carye3 @fiorella-io any preference to auto-change the task status here?

**Comment by aloverso** [comment]
@skeeJay regarding the analytics here, when do these checkbox events fire?
- anytime we change the checkbox state to be checked, including on first render when the app checks them automatically
- anytime a user attempts to check a box, right before the modal opens
- only if the user clicks the 'yes i am eligible' button on the modal when triggering a checkbox

**Comment by fiorella-io** [comment]
@aaronvux @aloverso Let's auto-update the status when they click on "View Requirements" to "In Progress" to keep it consistent

**Comment by aloverso** [comment]
@aaronvux this is ready for review

@Jesslax @CeciliaRam right there is just placeholder text in the standard business contextual info, that needs to be filled in

**Comment by skeeJay** [comment]
@aloverso Did you get an answer on your analytics question? Our guideline is that the analytics for each event should only be tracked on "final" submission, so I believe the actual answer is that each one should only be recorded if the box is checked when the final "view requirements" CTA is clicked (hence the fact that the second parameter for each event is specified as "submit," referring to the action on the form, and not "click" as an action on the checkbox). cc @aaronvux to confirm.

**Comment by aaronvux** [comment]
@aloverso When I select none of the above from the Priority Status task, the AC says to not display the checkboxes in this task.  @Jesslax does the Microbusiness question need to be required?  It's not currently.    @fiorella-io @CeciliaRam @Jesslax please review.

**Comment by aaronvux** [comment]
@aaronvux I the green section is should span the section.

<img width="714" alt="Screen Shot 2022-04-26 at 9 18 27 AM" src="https://user-images.githubusercontent.com/36163601/165309000-0c8a630b-5e61-4df0-b708-c9209ba07379.png">

**Design**
<img width="761" alt="Screen Shot 2022-04-26 at 9 20 01 AM" src="https://user-images.githubusercontent.com/36163601/165309445-646af9c2-3537-4bfa-9943-9fe2d9958314.png">

Also, I think we missed the counts in the AC.  Is this a big deal to add?

**Comment by fiorella-io** [comment]
@aloverso please adjust the following:

1. Add hr divider line before "Business Size"
![image](https://user-images.githubusercontent.com/91498500/165353791-2ecc75ea-16cf-457e-a707-1c1a537e588b.png)

**Comment by aloverso** [comment]
@aaronvux @fiorella-io @skeeJay 

- fixed the hr divider line
- fixed the green box styling
- fixed/added the analytics
- fixed the "none of the above" checkbox display

@aaronvux I do think counts need to be a separate story. It has a non-zero complexity that I'd have to think about how to implement it

**Comment by fiorella-io** [comment]
@aloverso Ce noticed that once you are on the requirements page, the "Priority status Application" and the "Priority Status Application Needs" accordion are closed by default, it should be opened for accessibility.

**Comment by aloverso** [comment]
@fiorella-io Sure, I can change that, np.

As an aside, the only thing I had to go off of was the linked design for Tab 2, which displayed all accordions besides the General one as closed-by-default, which is why they are closed-by-default in the app. Not a problem to fix. But the dev team wanted to bring this up at retro tomorrow, so wanted to flag this as an example of how we need more detailed AC for situations that are not clearly depicted in the designs, such as their default open/closed state, or even the content of those accordions (which is not shown in the designs since they're closed)

**Comment by aloverso** [comment]
@fiorella-io fixed!

**Comment by aaronvux** [comment]
> @fiorella-io Sure, I can change that, np.
> 
> As an aside, the only thing I had to go off of was the linked design for Tab 2, which displayed all accordions besides the General one as closed-by-default, which is why they are closed-by-default in the app. Not a problem to fix. But the dev team wanted to bring this up at retro tomorrow, so wanted to flag this as an example of how we need more detailed AC for situations that are not clearly depicted in the designs, such as their default open/closed state, or even the content of those accordions (which is not shown in the designs since they're closed)

@fiorella-io @aloverso I remember specifically asking about this in grooming and we decided they would be closed by default, hence the AC.

**Comment by fiorella-io** [comment]
@aloverso Actually only one section should be expanded by default, and the rest closed. Sorry for the confusion!

**Comment by aaronvux** [comment]
@aloverso thanks Anne.  Looks good!

**Comment by Jesslax** [comment]
@aaronvux all copy edits have been made, I'd like to look at it one more time in dev.

**Comment by Jesslax** [comment]
Goot to go!
