### ISSUE TITLE
Update: Submit Your Cannabis Conversion License Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2083]
As Poppy, I need the ability to submit my license for conversion from a Conditional license to an Annual license so that my business can operate under an Annual license.

## Acceptance Criteria
- Convert existing bulleted list in the task to checkboxes.
- Save checkbox states for registered users
- Display registration modal when guest user lands on the page.

## Design 

https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10639%3A194997

**Comment by aaronvux** [comment]
@Jesslax do we need a design for this?

CC @carye3 @fiorella-io

**Comment by Jesslax** [comment]
@aaronvux just needs the check boxes

**Comment by aaronvux** [comment]
@aaronvux might need new story for saving checkbox states.  New story for accordions on requirements step.
