### ISSUE TITLE
Spike: Research getting License expiration data from Consumer Affairs, to put renewal on Oscar calendar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2094]
- Research getting License expiration data from Consumer Affairs, to put renewal on Oscar calendar.

**Comment by aaronvux** [comment]
Dev team needs to speak with Cheryl about what the possibilities are to obtain this information.

**Comment by aaronvux** [comment]
@aloverso added inspection date to this research.

**Comment by aloverso** [comment]
@aaronvux we already asked them about inspection date: "Inspections may or may not be planned; anyway they are not entered anywhere."

**Comment by aaronvux** [comment]
My bad @aloverso.  I forgot that we already asked. Thank you!
