### ISSUE TITLE
Add Accordions to Step 2 of "Apply for Conditional/Annual Cannabis License" Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2111]
## Acceptance Criteria
- Create 3 Accordions (Labels to follow) that will display content mapped from Step 1 of the Cannabis License Task
- General Requirements Accordion will be open by default.
- Each accordion will stay open until the user closes it. 

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10798%3A203901

**Comment by aloverso** [comment]
@aaronvux ready for review
