### ISSUE TITLE
Formation Signer Name Checkboxes

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2115]
As Poppy, I need I need a checkbox next to each signer name so that I can affirm I am a signer for legal purposes.

## Acceptance Criteria
- Remove Checkbox validation message for each signer field (message will fire when the user tries to move forward)
- Inline validation will remain on each signer input field
- Single Header Column For Signer Full Name and Sign.
- Update Signature label to Sign
- Fix alignment issues in mobile to match the design.

## Additional Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11113%3A214925

## Notes
- [x] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
This story will be updated after Design Review.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io follow up on design for different scenarios.

**Comment by aaronvux** [comment]
LGTM.  @fiorella-io @carye3 please review.

**Comment by fiorella-io** [comment]
LGTM too!
