### ISSUE TITLE
Implement Site is Down for Maintenance Page

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2130]
As a user, I need to understand why site is inaccessible and for how long while it is under maintenance.

## Acceptance Criteria:
- Display the attached image when the Navigator is down for maintenance.

## Design

https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11207%3A228461

**Comment by carye3** [comment]
@dsueltenfuss

**Comment by aaronvux** [comment]
@dsueltenfuss Design attached for site maintenance.

**Comment by fiorella-io** [comment]
Looks good

**Comment by aaronvux** [comment]
Mobile layout needs some work so the image and content are not being cut off.  Font needs to match the design.  Also update the copy to, "We'll be back soon."

**Comment by aaronvux** [comment]
Looks good now!  Fiorella also approved.
