### ISSUE TITLE
Add Side Nav and New Sections in Profile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2150]
As a Navigator user, I need to have my Profile organized into sections with a side navigation so that I can easily read content on the page.

**NEED TO REVISIT DIFFERENCES AND FUNCTIONALITY FOR POPPY AND OSCAR**

## Acceptance Criteria
- Create Side Navigation
  - Business Information
  - Reference Numbers
  - Reference Documents
  - Notes
- Create New Content Sections as their own page
  - Business Information
  - Reference Numbers
  - Reference Documents
  - Notes

## Designs
[Oscar Profile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10175%3A185539)
[Poppy Profile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11289%3A239327)
[Oscar Profile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10175%3A185947) (Only for Poppy's that formed their business)
[Mobile Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10175%3A185698) (editable Fields)
[Mobile Designs](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10175%3A186107) (Post Business formation)

## Additional Acceptance Criteria
- 508 Compliant
- Follow Design
- Works in mobile

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
Lgtm! Sticky side nav is only thing missing from desktop
