### ISSUE TITLE
biz.nj:  New Licensing Page Implementation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2174]
## Designs
[Desktop 1440px](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10938%3A207104)
[Mobile 320px](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10956%3A208351)

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please add designs when complete

**Comment by fiorella-io** [comment]
I've just added the designs

**Comment by dltinnovate** [comment]
Finished implementation and QA'd on 4/26.
