### ISSUE TITLE
Design: Guest Mode Improvements

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2222]
Simply the registration snackbars and registration modal.

Reevaluate behavior of nudges and snackbars, update interaction with blocked Tasks

## Tasks:
- [x] Discuss how frequently snackbar shows (4.14: show once, then in sidebar)
- [x] Review issues where registration snackbar overlaps with other snackbars

## User Story 1
As a user, I need to be reminded that I will lose my account information if I don't register in order to act accordingly.

- **Design options:**
  - Exit intent snackbar / modal
  - "Remind Me" option in snackbar
  - Permanent banner (below beta bar) at top

**Comment by carye3** [comment]
4.12: Discussed with Aaron, Fiorella and agreed that snackbar shows once, then in sidebar (see gradual graduation). No changes to restricted forms.
