### ISSUE TITLE
Feedback: Add Feedback Button to Beta Bar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2243]
As a Navigator user, I need a better way to provide feedback and get help so that I can help improve the navigator and get information for my business.

## Acceptance Criteria
- Add "Have some feedback" button.
  - Clicking the button will open the modal window
- The modal will only contain Provide Feedback & Speak with a Business Expert options. 
  - Clicking Provide Feedback will close the modal and open the survey.
  - Clicking the Speak with a Business expert will close the modal and open Intercom.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- [Feedback Button Desktop](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10984%3A209949
)
- [Feedback Button Mobile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11213%3A228785)
- [Modal Desktop](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=10984%3A210236
)
- [Modal Mobile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11213%3A229457)

## Analytics
Add feedback button to google analytics

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@fiorella-io @carye3 Where does the feedback button appear in mobile?  Can you please add the mobile designs for the button and modal?

**Comment by fiorella-io** [comment]
@aloverso Good call. Let me adjust the designs and find SVG icons we can use instead. I'll ping you when it's ready

**Comment by fiorella-io** [comment]
@aloverso The designs are ready! You can use the same links.
For the "Share your feedback" button use the secondary buttons style
<img width="314" alt="image" src="https://user-images.githubusercontent.com/91498500/164052917-b688f5c4-1892-4841-bebe-0e90b0cee2fb.png">
https://newjersey.github.io/njwds/components/detail/buttons--secondary.html

For the feedback buttons, you can view the hover, active and disabled states [here](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs-(Sprint-1-32)?node-id=11810%3A202488).

**Comment by aloverso** [comment]
@skeeJay what analytics events do we want for this story?

**Comment by skeeJay** [comment]
@aloverso I am thinking it will be easier to spec/define analytics for all of the feedback stuff as its own user story after all of this, #2245, #2246, and #2247 are complete. Is that an okay approach?

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by fiorella-io** [comment]
@aloverso Is the "Speak with an NJ-Based Business Expert" button suppose to work yet? It is not opening the intercom. Other than that, everything else looks good!

**Comment by aloverso** [comment]
@fiorella-io is the intercom button showing up for you? some of the older test accounts have issues with intercom. log out and see if it works then? it works for me

**Comment by aaronvux** [comment]
@aloverso intercom is not opening for me in mobile.  Works in desktop.

**Comment by aloverso** [comment]
@aaronvux can you send a screenshot? it works for me on mobile

**Comment by fiorella-io** [comment]
@aloverso After I created a new account, I can see the intercom on both desktop and mobile. But on my old account, after I logged out and logged back in, it appears and then disappears instantly.

**Comment by aaronvux** [comment]
It worked for me oddly on mobile after I went to prod.  I think we can push this and test again once it's in Production.

**Comment by Jesslax** [comment]
Just saw this dev, looks great! It did not open intercom for me. Also, can the survey open in a separate window?

**Comment by aaronvux** [comment]
Moving to deploy and retest Intercom in Production.
