### ISSUE TITLE
Feedback: Add "Report an Issue" to Feedback Modal

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2246]
As Navigator User, I need the ability to report an issues or bugs I experience so I can get help and fix things that are broken in the Navigator.

## Acceptance Criteria
**Feedback Modal**
- Add Report an Issue to Feedback Modal once onboarding has been completed.
- Clicking the option displays Report an Issue Form with 2 questions (see design)
  - Inline validation on both text fields. "This field is required."
- After clicking submit, display Thank you message.
- Add Report an Issue bar and button at the bottom of the page (see design)
  - Clicking the button will open the bug form.
  - After submission, the success message will display.
  - Clicking Submit Another Issue will open the full feedback modal.

**Storage**
- Create an Airtable to store reported issues.  
  - Create two tabs (Issues and Features)

**Airtable Columns**
- Context
- Detail
- Date & Time
- Email
- Persona
- Industry
- Page Report was initiated on.
- Device
- Browser
- Screen Width

**AIrtable is Down**
- Display inline error message on the form (see design)

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
Desktop Report an Issue Form
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=10984%3A210342
Desktop Thank You Modal
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=10984%3A210974

<img width="1044" alt="Screen Shot 2022-05-11 at 1 26 10 PM" src="https://user-images.githubusercontent.com/36163601/167910809-74aee24a-e46d-446c-9fb9-c3a950a6a286.png">

Desktop - Bottom Bug Bar
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=10984%3A209949

Mobile - Bottom Bug Bar
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11213%3A228785

## Analytics
- Track the page the issue has been reported from

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux @fiorella-io @carye3 
The AC mentions `Add Report an Issue bar and button at the bottom of the page (see design)`. The design for the AC do not exist.

**Comment by aaronvux** [comment]
@FarazA22 same character limit as feature input.  Added the designs for the bug bar.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io is the bug bar floating or at the bottom of all the content on the page?  See Faraz's comment.

**Comment by FarazA22** [comment]
@carye3 Should the bug bar appear above the legal message bar or below it within the footer section?

@aaronvux Once the button on the bug bar is clicked, does the `let us know what you think` modal appear or the bug modal? Then, when the bug is submitted and the user clicks 'submit another request' on the thank you modal, which modal are they routed too? 

The simplest/ most consistent solution is to follow the same flow (when the user clicks the feedback button at the top to report a bug).

**Comment by carye3** [comment]
Above @FarazA22 (designs updated) -- ty!

**Comment by aaronvux** [comment]
@FarazA22 Updated AC to open bug form directly from the bug bar.  Success message will follow current functionality.

**Comment by FarazA22** [comment]
@skeeJay @aaronvux Can you provide the specific analytics spec for this story? We are providing the page the user was on within the AirTable.

**Comment by aaronvux** [comment]
@FarazA22 I think we are good for on analytics for this one since we are tracking the page user is on already.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
LGTM.  @carye3 @fiorella-io @CeciliaRam please review.

**Comment by aaronvux** [comment]
@fiorella-io yes.  I would think both validations should fire.

**Comment by FarazA22** [comment]
@aaronvux Fixed, should be in dev within the next 20 minutes.

**Comment by aaronvux** [comment]
@FarazA22 thanks.  Moving to deploy.
