### ISSUE TITLE
Feedback: Add "Request a Feature" to Feedback Modal

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2247]
As a Navigator User, I need the ability to request features so that I can get information to support my business.

## Acceptance Criteria
**Feedback Modal**
- Add Request a Feature to the Feedback modal after onboarding has been completed.
  - Inline validation on text field.  "This field is required."
- Clicking the option displays Request a Feature Form with 1 question (see design)
- After clicking submit, display Thank you message.

**Storage**
- Write user submitted content to Feature Tab in Airtable

**Airtable Columns**
- Detail
- Date & Time
- Email
- Industry
- Persona
- Page Report was initiated on
- Device
- Browser
- Screen Width

**AIrtable is Down**
- Display inline error message on the form (see design)

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop Modal
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11817%3A226804
- Desktop Feature Request
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=10984%3A210264
- Desktop Thank You Modal
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=10984%3A210418 
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12312%3A250623

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux @fiorella-io @carye3 
- I'd like to add logic that prevents the submission of the feature request if the input is empty. Any concerns? Should the app give the user feedback if the request is not submitted due to an empty input field?
- Is there a max character size for the input field?

**Comment by fiorella-io** [comment]
@FarazA22 
1. I agree to not allow users to submit an empty form
2.  I'm not sure what the character limit should be? 400? @aaronvux @carye3 
3. Yes, it should go to the main Feedback modal

**Comment by FarazA22** [comment]
@aaronvux Can you provide the location of the AirTable we are using for this ticket. I've only been given access to the `State Financing Programs Database` table. It would be great if you can grant me access to all the tables the dev team have used.

**Comment by aaronvux** [comment]
@FarazA22 I thought we were creating the airtable as a part of this ticket.

**Comment by aaronvux** [comment]
@Jesslax @skeeJay @fiorella-io See Faraz's comment above.  We aren't collecting email address on the front-end but we are storing it on the backend.  

Unless we want to add email as a field, the column in the airtable will be blank for guest mode users. Are we ok with this?

**Comment by FarazA22** [comment]
We should follow the same paradigm we are currently using where the option to submit feedback is only visible once onboarding has been completed.

**Comment by aaronvux** [comment]
@FarazA22  ahh right.  So, we would continue not to show the survey, feedback or bug report until they hit the roadmap or dashboard.  That way anyone can make a report since we can pass their email and name from onboarding. Updated the AC.

**Comment by FarazA22** [comment]
@aaronvux 
I'm able to populate airtable with the following. Please let me know what fields you want. The more detail we are the more granular we can be with identifying the device, the downside is that filtering within airtable will not be as beneficial. You could of course export the airtable and parse the data. 

if browser
- name (i.e. Chrome)
- version (i.e. 101.0.4951.64)
- major (i.e. 101)
  - We can create a unique string like (Chrome 101.0.4951.64)

if Device and a Computer
- name (i.e. Mac OS or Windows)
- version (i.e. 10.15.7 or XP)
  - We can create a unique string like (Mac OS 10.15.17)

if Device and other device 
- type (i.e. mobile)
- vendor (i.e. Apple)
- model (i.e. iphone)
  - We can create a unique string like (Apple Iphone Mobile)

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
Received an error.

<img width="775" alt="Screen Shot 2022-05-20 at 3 50 31 PM" src="https://user-images.githubusercontent.com/36163601/169601254-1fe01ee2-51f7-4c2c-8f7a-faea0a8b644a.png">

**Comment by FarazA22** [comment]
@aaronvux fixed

**Comment by aaronvux** [comment]
@Jesslax @carye3 @fiorella-io @CeciliaRam  LGTM, please review.

**Comment by fiorella-io** [comment]
Looks good

**Comment by carye3** [comment]
Functionally it lgtm, added some formatting issues for mobile in #1899

**Comment by Jesslax** [comment]
lgtm

**Comment by CeciliaRam** [comment]
just had a chance to check - lgtm
