### ISSUE TITLE
Add Feedback Options to Intercom

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2248]
As a Navigator User, I need I need to be able to provide feedback through Intercom so I can so I have easy access to the Feedback options.

## Acceptance criteria
- Display when Intercom is opened via the icon in the lower right hand corner.
- Display the following 4 options:
  - Provide Feedback
  - Report an Issue
  - Request a Feature
  - Speak with a Business Expert

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop Intercom
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11817%3A226840
- Mobile

## Analytics
TBD

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@dltinnovate can you review this ticket please and let us know what is possible in Intercom.

**Comment by aaronvux** [comment]
spoke with @dltinnovate.  We may want to reconsider how we implement this feature. 

1.  Pop-up outbound custom bot through Intercom that asks users if they want to do the survey or request a feature.
2. Add URL link for bugs to current technical issues feature in Intercom, possibly not a great UX for the user.
3. Do nothing, have BAC report issues to the team and add to airtable.

**Comment by dsueltenfuss** [comment]
@aaronvux is this a development issue? I thought we determine Intercom changes were something @dltinnovate needed to implement

**Comment by aaronvux** [comment]
@dsueltenfuss we weren't sure if dev would need to do anything for this one.  I think we need to make a decision if we want to move anything forward for this one.

**Comment by aaronvux** [comment]
@dltinnovate @skeeJay do we want to do anything with Intercom?  I'm feeling like we can move this to the unsure column.
