### ISSUE TITLE
Map Industry to Sector Automatically When Poppy Graduates to Oscar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2249]
As Poppy, I should not have to answer the industry question when so I don't have to repeat information I have already given.

## Acceptance criteria
- Do not display the Industry question for Poppy in the graduation modal if they selected any industry other than, "Any Other Business Type".
- Continue to display the Industry question when "Any Other Business Type" is selected.

## Mapping
@CeciliaRam please attach the mapping

## Approvals
- [x] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux @Jesslax reading the acceptance criteria, it sounds like we should hide the Sector dropdown in the graduation modal for all Poppy industries (except the generic/"all other" industry)

But looking at the industry mappings we have, we have several industries that map to the "Other Services" sector. Like Cleaning Aid, Cosmetology, Janitorial, etc. 

So for those industries, should we default them to the "Other services" sector _and_ NOT show the Sector dropdown? Or does the AC mean that we should not show the sector dropdown if they have a sector that's not "other services"?

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@carye3 @fiorella-io LGTM.  please review.

**Comment by fiorella-io** [comment]
Looks good!
