### ISSUE TITLE
Design bug: grey box alignment on Search Licenses task

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#2282]
for Search Licenses task, the grey box on the bottom does not line up with the box border

![image](https://user-images.githubusercontent.com/6563663/161826002-79e45233-1571-440e-8c68-466cacc9f26d.png)

**Comment by aloverso** [comment]
@aaronvux @carye3 just noticed this one, to be prioritized

**Comment by aaronvux** [comment]
@FarazA22 LGTM
