### ISSUE TITLE
Pass User Email and Name to Intercom

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#2320]
As a BAC team member I need the Navigator to pass user email and full name to Intercom so that information can be pre-populated our tracking system.

## Acceptance Criteria
- Pass Full Name and Email Address to Intercom once the Navigator Roadmap or Dashboard loads.
- Save Full Name and Email Address in the Intercom tracking system.

## Additional Acceptance Criteria
- Document all fields that can be passed to Intercom from the Navigator

## Approvals
- [ ] BAC Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux this should be prioritized, this is the Intercom story that Joe discussed on standup yesterday

@dltinnovate if possible, if you could fill in the As... I need... so that... to explain the why behind the story, and what value this will provide when completed.

**Comment by dltinnovate** [comment]
As a BAC representative, I need to see the email address and name of the navigator users in Intercom. If users have an email, Intercom will forward them the response from BAC even after they've left the site or closed the chat. Given that some answer can take a few hours to address, this is critical to them getting answers to their questions. Under the current system, BAC cannot input an email address in the system for them like they can for 'visitors' to the main site.

**Comment by aaronvux** [comment]
@dltinnovate please review the AC when you get a chance

**Comment by dltinnovate** [comment]
@aaronvux This looks great! In terms of passing anything else... there might be some additional use cases as we explore more features in the coming months, but for now this is all BAC needs to improve existing customer service experience. 

Would it be possible to get a list of possible information that could be passed through to Intercom?

**Comment by aloverso** [comment]
@aaronvux @dltinnovate ready for review

For the additional criteria, here's the documentation of what intercom accepts: https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#section-mapping-of-javascript-attributes-to-intercom-dashboard-and-api

most of the rest doesn't seem so useful to us

**Comment by aaronvux** [comment]
@aloverso this looks like it's working.  I saw my first name and my email address in Intercom.  Sent a message through Intercom to confirm, but not sure if messages are sent to BAC in dev.
