### ISSUE TITLE
Update: Add Due Dates to Opportunity Cards (MVP)

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2393]
As Oscar, I need to see due dates on Opportunity Cards on the Dashboard so that I know the urgency for when my application is due.

## Acceptance Criteria
- Add Due Date to Opportunity Cards (see design)
- Display either Due Date or First Come First Serve 
- If no Due Date or First Come First Serve exists, display the current implementation. 

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11581%3A196672

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
@CeciliaRam can you test this please and let me know opportunities that have a due date and first come first serve

**Comment by Jesslax** [comment]
Can we add a space between Date: and the date, so it looks like this "Due: 07/01/2022"

@dsueltenfuss @aaronvux once we change the language of "open" to "rolling application" can we display that too?
