### ISSUE TITLE
Design: Formation - C-Corp

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2401]
### Existing fields (to keep with no changes): 
- Start Date
- Business Address
- Registered Agent 

 
### Existing fields (No change in location, just need new info)
- Suffix: Incorporated, Corporation, Company, Limited, Inc, yty, Co, Ltd.
- Members: C-Corps have Directors instead of members. Need their names and addresses (up to 10). **1 Director is required**. 
- Signer: C-Corps call it an incorporator. Need the name and address of each incorporation (up to 10). **1 incorporation is required**.
- Signature Box: Only the incorporator(s) need to check the signature box
 
### New items: 
- Business purpose (Optional)
- Provisions/ Additional Info for a For-Profit C Corp (can add up to 10/**12?** provisions) (Optional)
     -  **2 text areas need to show by default:???**
     - **Designation for the class of shares. Text area with 400 character limit**
     - **Board authority to classify the shares. Text area with 400 character limit**
     - Any additional Provision is a new text area with a 3,000 character limit
- Stock (no limit on the number of shares, can be 0.) 
    - Placement: Would make the most sense to put it under page 2 (business)
    - Input field (for a number - up to 6 digits?)

### Rearrange information for LLC and LLP
- Step 1: Name 
- Step 2 Business: Business info, Location, Business Purpose, Provision
- Step 3: Contacts: Registered agent, Members/Directors/Incorporators, Signers 
- Step 4: Review
- Step 5: Billing

**Comment by fiorella-io** [comment]
@aaronvux can you check what information is being received by treasury for provisions? We see two provisions at 400 character limit and the rest at 3,000.

**Comment by aaronvux** [comment]
@fiorella-io I only see 400 character limit in the API documentation.  Where are you seeing the 3,000 limit?

<img width="962" alt="Screen Shot 2022-04-14 at 8 42 02 AM" src="https://user-images.githubusercontent.com/36163601/163393185-b551b539-8b50-4632-8c6d-a9c590eae5b0.png">
