### ISSUE TITLE
Content: Add HVAC Industry

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#2403]

**Comment by CeciliaRam** [comment]
Roadmap is in dev. 
Ticket not marked closed yet bc we're checking on tasks for this roadmap that are showing in netlify but aren't showing in dev (2 tasks in step 3)

**Comment by CeciliaRam** [comment]
Task issues are resolved, roadmap looks good in dev. Closing ticket.
