### ISSUE TITLE
Add Optional "Business Purpose" to Formation for All Legal Structures

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2442]
As Poppy, I need the ability to upload Business Purpose information when I form my business with the state so that I can have accurate records.

## Acceptance Criteria
- Add Business Purpose to Formation Business Step and available for all other legal structures.
- Do not pass empty text fields to the API.
- Collapsed By Default
- User must click Add Business Purpose link to display free text input field
  - Limit 300 Characters
  - Display character counter and update as the user inputs information
  - Clicking the trash can icon will remove the free text field and any information in the field.
  - If free text field is removed, revert to default display.
- Add Business Purpose to Review Section
  - Edit link takes the user back to the Business Purpose task

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
**Default**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227646
**Expanded**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227730
**Review**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227341
- Mobile
**Default**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238030
**Expanded**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238102
**Review**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238208

## Analytics
TBD

## Approvals
- [ ] Content Review
- [x] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux can we remove the "trash can" acceptance criteria? I thought we were just removing it via the Remove Business Purpose button and that the trash can wouldn't exist anymore

**Comment by aaronvux** [comment]
@aloverso we removed the button and went with the trash can approach during grooming if I remember correctly.  The Remove Business Purpose button is not in the design or AC.
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227730

**Comment by aloverso** [comment]
@aaronvux I see. That's a different design than the one that was linked there earlier this morning, which did not have a trash can and did have the Remove Business Purpose text. I can go back and change what I've done, but for the future, it's not fun to have the design change while the story is already being worked on.

What is supposed to happen on mobile? Here I see both the trash can _and_ the Remove Business Purpose button? 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/6563663/166506131-3bd28695-a823-41aa-acc5-ca80601df3f0.png">

**Comment by aaronvux** [comment]
@aloverso I didn't change anything.  It looks like that link matches what's under the expanded design section for desktop.  In mobile, I believe it's just the trash icon.  @carye3 please confirm.

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aloverso** [comment]
The flip side is that the API error message gives users a link where they can request to be able to use the reserved words. We wouldn't be able to do that in our inline validation error message, so perhaps forcing users and being unable to move forward if you use them would be actually detrimental to their experience, because they would never get a chance to be given that link

<img width="635" alt="image" src="https://user-images.githubusercontent.com/6563663/166743855-72ae9a95-b903-4a34-9d68-6d9ba2d1421c.png">

**Comment by aaronvux** [comment]
@aloverso will the API error list all of the restricted words if they are used in combination?  I think the API error will be ok for now to push this to Production once reviewed.  @Jesslax @skeeJay thoughts?

**Comment by aloverso** [comment]
@aaronvux No, it only shows one restricted word at a time

**Comment by aaronvux** [comment]
LGTM.  @carye3 @fiorella-io @carye3 @Jesslax please review.

**Comment by fiorella-io** [comment]
@aloverso Can we left-align the "Add Business Purpose" link. Adjust the heading to H3 font-size 22px to match "Business Name and Legal Structure". We'll fix the other headings during our dev/design sync. 
![image](https://user-images.githubusercontent.com/91498500/166815493-aca20d4d-abf2-447c-a84c-8908b1cedf60.png)
![image](https://user-images.githubusercontent.com/91498500/166815566-13a8faeb-28d4-462c-a105-0fe48ad3780c.png)

**Comment by Jesslax** [comment]
I don't see room for highlighted copy: 
![image](https://user-images.githubusercontent.com/78366346/166806592-ae160c6f-0f70-466b-8f0d-516b7c9aa783.png)

**Comment by fiorella-io** [comment]
Looks good. Thank you @aloverso!

**Comment by Jesslax** [comment]
perfect, thanks!

**Comment by aaronvux** [comment]
Need Jessica at Treasury to verify they are receiving the data from NIC.
