### ISSUE TITLE
Update Guest Mode Snackbar Display

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2448]
As a Navigator User, I only want to be informed by a Snackbar to register on myNJ 1 time so that I don't get annoyed and stop using the application.

## Acceptance Criteria
- Only display the Registration Snackbar the 1st time they land on the Roadmap and Dashboard
- Do not display the Registration Snackbar again if the user navigates back to the Roadmap and Dashboard.
- If the Registration Snackbar is closed and user is not registered, display the registration card in the right hand column.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
- Mobile

## Analytics
TBD

## Approvals
- [ ] Content Review
- [x] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux Based on how the AC is currently written, the register card will not appear in the sidebar since it's triggered when the user manually closed the snackbar. We should also update the AC to include the registered card open return.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
LGTM.  @fiorella-io @carye3 please review.

**Comment by fiorella-io** [comment]
LGTM!
