### ISSUE TITLE
Update "Register for State Taxes" Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2449]
As Poppy, I need to be able to see NAICS Code and EIN information on the Register for State Taxes task so that I can be well informed.

## Acceptance Criteria
- Update "Register for State Taxes" task: Add “Determine NAICS Code” task as a dependency
- If the NAICS Code is available in the profile data, display the code next to the NAICS bullet on the register for state taxes task. 
- Update “Register for State Taxes” task: Change NAICs code as a link that takes user back to “Determine Your NAICS Code” task.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aloverso not seeing the NAICS code dependency in the task.

**Comment by aloverso** [comment]
@aaronvux I am seeing the dependency. Are you sure your NAICS code task isn't listed as completed? Tasks don't show up in the dependency alert if the user has already completed them.

**Comment by aaronvux** [comment]
@aloverso ahh thank you so much. I totally didn't think of that.  I see it now.  Looks good!  @Jesslax @CeciliaRam please review.
