### ISSUE TITLE
Add Optional "Provisions" to Business Formation for All Legal Structures

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2456]
As Poppy, I need to be able to add Provisions/Articles while I'm forming my business so that I have accurate records of my business.

## Acceptance Criteria
- Add Provisions/Articles to Formation Business Step and make available for all legal structures
- Do not pass empty text fields to the API.
- Collapsed By Default
- User must click Add Provisions/Articles link to display free text input field
  - Limit 300 Characters per text field.  Max 10 fields.
  - Display character counter and update as user inputs information
- Clicking the Add New Provision/Articles link will add another free text input field, same character limit and functionality from above.  Limit to 10.
  - Hide Add New Provision/Articles when 10 text fields have been added. 
- Clicking trash can icon will remove the associated free text field and any information that was input.
  - If the last free text field is removed, revert to default display.
- Add Provisions/Articles to Review Section
  - Number each article in the order they were input on the Business step and display all the information.
  - Edit link takes the user back to the Business Purpose task
 

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
**Default**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227646
**Expanded**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227730
**Review**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227341
- Mobile
**Default**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238030
**Expanded**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238102
**Review**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A238208

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aloverso Provisions is allowing me to add 400 characters into the Provision.  AC says 300.

**Comment by aloverso** [comment]
@aaronvux I assumed that was a typo? It's 400 characters in the designs and also in NIC's API spec

**Comment by aaronvux** [comment]
@carye3 @fiorella-io @Jesslax @CeciliaRam please review.  Looks good and data is flowing to NIC properly.  Need to discuss character limits and Jessica at Treasury needs to verify the data is getting populated correctly for Treasury.

**Comment by aaronvux** [comment]
@aloverso I was able to successfully submit 10 - 3000 character provisions
