### ISSUE TITLE
Add NAICS Code Task to Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2463]
As Poppy, I need the ability to associate a NAICS Code to my business so that I have accurate records.

## Acceptance Criteria
- Add Determine your NAICS Code task to Plan
  - Required Task
- Displays content with links to Siccode.com and Naics.com with Input Box and Save NAICS code button.
  **Display Registration modal if not logged in when Save button is clicked.
  Save value upon successful registration and redirect back to the page.**
- Validate input box is 6 digits when the Save NAICS button is clicked.
  - Inline Validation message: NAICS code must be 6 digits.
  - Clicking the button displays success message with contextual link.
  - Display NAICS Code with edit link.
  - Clicking the Edit link displays previous content and user input value with links to Siccode.com and Naics.com, input box, and save button.
- Display Why do I need a NAICS code section
  - Link to Register for State Taxes and Employer Purposes

## Additional Acceptance Criteria
- Store NAICS code with user Profile Data
- Automatically change status to Completed WHEN a NAICs code has been saved
- Automatically revert back to In-Progress if the Edit link is clicked.
- 508 Compliant
- Follows Design
- Works in Mobile
- All Static Text should be editable in Netlify.

## Design
- Desktop
**Default**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12311%3A248897
**Success**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12311%3A249048
- Mobile
**Default**
Need mobile
**Success**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12311%3A249567

## Analytics
dimension8: “Six Digit NAICS Code”/[6-digit NAICS code]

## Approvals
- [x] Content Review
- [x] UX Review
- [x] PO Approval

**Comment by aaronvux** [comment]
- Automatically change status to In-Progress WHEN Siccode.com or Naics.com links are clicked.   Create another story for this and implement across the site.

**Comment by aloverso** [comment]
@Jesslax is this task required on every roadmap? or is it dependent on industry / legal structure at all?

**Comment by Jesslax** [comment]
@aloverso required for all because all businesses need NAICS code to reg for taxes

**Comment by aloverso** [comment]
@aaronvux @carye3 @fiorella-io is there any way to remove / unset your NAICS code in this design? If we're displaying validation/error text if they try to click Save when their NAICS code is not 6-digits, then there's no way to unset it to be empty once they've saved it - only to change it

**Comment by aaronvux** [comment]
@aloverso, I think we can find a solution for this, but it might be a bit of an edge case.  @Jesslax do you feel like going back to no NAICS code after saving one is something we should handle before this story goes live?

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by fiorella-io** [comment]
During stand-up, we decided to leave as is. If a user enters and saves a NAICS code, they can't clear it out, only edit it. 

@aloverso Everything looks good on desktop and mobile.

**Comment by aaronvux** [comment]
@aloverso looks good to me!  @Jesslax please review.

**Comment by Jesslax** [comment]
@aloverso where do I go to change the copy in the grey box?

**Comment by aloverso** [comment]
@Jesslax it's all in the Config section of the CMS - a new accordion for NAICS code

**Comment by Jesslax** [comment]
All set, ready to go, thanks
