### ISSUE TITLE
NAICS Code Report

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2466]
As an Innovation Team member, I need to be able to see what NAICS codes are being utilized the most so that I can be well informed on the types of businesses that are being created in NJ.

## Acceptance Criteria
- Create a report that queries the NAICS codes being stored with User Profile Data
- Automatic Email or Manually run?

**Headers**
- Report Name
- Date Range

**Columns**
- NAICS Code
- NAICS Code Description
- Count
- New Records within the date range?

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by skeeJay** [comment]
Added Custom Dimension 8 to the analytics spec. cc @dsueltenfuss @mikewolfd @aaronvux  https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

**Comment by aaronvux** [comment]
@kmelefsky need to discuss this at planning to make sure we are all in agreement.
