### ISSUE TITLE
Add NAICS Code to User Profile

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2467]
As Poppy, I need to be able to view my NAICS code through my Profile so that I can see important information I have input into the Navigator.

## Acceptance Criteria
- Add NAICS Code field in Poppy Profile only.
- Clicking the Add link takes the user to the NAICS code task.
- Display read only field once it's populated from the NAICS code task.
- Clicking the Edit link takes the user to the NAICS code task.
- Jess/C to add copy for the field.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
**Desktop**
- (https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11316%3A245005
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12921%3A256520

- [Mobile](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12535%3A255768)

<img width="791" alt="Screen Shot 2022-05-16 at 1 09 50 PM" src="https://user-images.githubusercontent.com/36163601/168646775-2259b055-d0bb-47d1-967a-d93b0830ca70.png">

<img width="778" alt="Screen Shot 2022-05-16 at 1 10 02 PM" src="https://user-images.githubusercontent.com/36163601/168646773-776a104e-8779-4378-b4a1-2faeaf49abb4.png">

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux Is this a disabled field? I remember some conversations about only wanting the NAICS to be editable in the task, is that still true?

**Comment by aloverso** [comment]
@aaronvux sure, I can wait for the designs.

**Comment by aloverso** [comment]
@aaronvux @Jesslax @fiorella-io the designs don't match the screenshots here... are we including something for "Explanation will go here" or is it no longer included?

**Comment by aaronvux** [comment]
@aloverso Please do not include, "Explanation will go here".

**Comment by aaronvux** [comment]
@Jesslax @carye3 @fiorella-io please review.  LGTM

**Comment by fiorella-io** [comment]
LGTM!
