### ISSUE TITLE
Add Business Name to Graduation Modal

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2469]
As Poppy, who hasn't formed through the Navigator, I need to input my business name into the graduation modal so that my important information about my business is stored in the Navigator.

## Acceptance Criteria
- Do not display Business Name for users who have formed through the Navigator. 
- Add Business Name input field as the first field to the Graduation Modal for users who have not formed their business through the Navigator.
  - Required Field
  - "Business Name is required."

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
- Mobile

## Approvals
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
LGTM
