### ISSUE TITLE
Update Certified Public Accountant with new Industry Value & Follow Up Question to Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2483]
As Poppy, I need to have a better description of the CPA industry and see relevant tasks so that I can create my business quickly.

## Acceptance Criteria
- Change the name of the Certified Public Accountant industry in the Industry dropdown to: "Accounting, Bookkeeping, and Tax Preparation"
- Once this industry is selected, display question: "Are you a looking to offer Public Accounting Services?"
  - If yes, inject CPA tasks: Apply for a Certified Public Accounting License and Register Your Accounting Firm With the State

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
- Mobile

## Analytics
onboarding_cpa_question/submit/yes_i_offer_public_accounting
onboarding_cpa_question/submit/no_i_dont_offer_public_accounting

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
@dsueltenfuss I think we need to add the analytics to this be for it can be approved. It needs to be added to the tracking doc.

**Comment by dsueltenfuss** [comment]
I added analytics for when the 'yes' answer was selected. 
onboarding_cpa_question - submit - yes

**Comment by aaronvux** [comment]
@Jesslax Do we want the follow up question to default to NO or should it be blank and the user has to pick.  If blank, we will need to add a validation.

**Comment by aaronvux** [comment]
@Jesslax Do we want to track the no click?  Comes back to my previous question about default behavior

@skeeJay added these to analytics:
onboarding/industry/accounting/cpa_services/yes/click/next
onboarding/industry/accounting/cpa_services/no/click/next

**Comment by skeeJay** [comment]
@aaronvux I'm not sure I understand these new events you've specced. Events need three parameters, like Dave's formulation above, not six.

**Comment by aaronvux** [comment]
I didn't see Dave's comment, sorry.

**Comment by dsueltenfuss** [comment]
@aaronvux I just pushed the improved analytics onboarding_cpa_question/selected/offering_public_accounting_services

**Comment by dsueltenfuss** [comment]
@aaronvux I added the second analytic and updated the names
