### ISSUE TITLE
Gradual Graduation (MVP): Add Sidebar to Poppy Experience with Appropriate Prompt Cards

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2502]
As Poppy, I need to have a better experience that allows me to see information that helps me graduate to Oscar so my business can become operational more easily.

## Acceptance Criteria
- Add Content Column to Poppy Roadmap landing page.
  - Display welcome card and content 
  - Welcome content cannot be closed.
- Display Snackbar for Registration
- Once Snackbar is closed, display registration content.
  - Clicking the link will bring the user to myNJ.
- After successful registration, display You're Registered content in Content Column.
  - Clicking close icon will remove the content from the column.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A232935
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A239964
**Prototype**
https://www.figma.com/proto/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?page-id=11551%3A187892&node-id=11915%3A236185&viewport=241%2C48%2C0.16&scaling=min-zoom&starting-point-node-id=11915%3A236185

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Need to prioritize this with updating the registration snackbar displaying story.

**Comment by CeciliaRam** [comment]
@aaronvux (@Jesslax )
"Clicking the link will bring the user to myNJ." - will that take any user info from onboarding over to MyNJ?

**Comment by aaronvux** [comment]
I don't believe so.  We don't pass anything currently

**Comment by Jesslax** [comment]
@aaronvux @aloverso dont we pass the name and email? Just wanted to make sure that would continue

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam you're right.  We pass name and email. @aloverso cannot we not pass the other fields so we can avoid the myNJ UI all together. 

My assumption that we would continue to pass this info to myNJ from the new registration link.

**Comment by aaronvux** [comment]
@kmelefsky Discuss removing links in content bar for form your business and register for taxes for 16th minute.

**Comment by FarazA22** [comment]
@carye3 @fiorella-io
For pages where we use a wide page layout, should the legal message and footer align with the header and nav bar? I think they should be. I've attached a screenshot of what it would look like.

<img width="1070" alt="Screen Shot 2022-04-28 at 1 13 26 PM" src="https://user-images.githubusercontent.com/72581979/165809048-bb7b8535-b44e-4c9f-ad9d-87c5ae8b4365.png">

**Comment by FarazA22** [comment]
@aaronvux 
The registration card is displayed after the user closes the registration snackbar. Within #2448 we are planning to only display the registration snackbar once. If the user navigates to a different page, then returns to the roadmap, neither the snackbar or the card will be displayed. 
- Should the registration card always be displayed and not rely on the snackbar? Do we need the snackbar?

**Comment by aaronvux** [comment]
@FarazA22 It should display after the snackbar is closed, but not rely the snackbar to be displayed again.  Once it shows, it should continue to display.

**Comment by FarazA22** [comment]
@aaronvux  Since the ticket to only display the snackbar once is planned for the next sprint, can we update the AC for this ticket to display the registration card after the snackbar is closed. It's A LOT simpler to implement logic that renders the registration card if the snackbar is not displayed. We can discuss further if you need more detail from me.

**Comment by aaronvux** [comment]
@carye3 Spoke with Faraz.  The current implementation of the registration card disappearing and the snackbar reappearing when navigating back is fine for now.  We should consider pulling in #2448 to get the desired behavior.

**Comment by skeeJay** [comment]
@FarazA22 Out of curiosity, after this is implemented, will Poppy and Oscar both have the same URL? (If so, what is it, `/dashboard`?) Or do they continue to go from `/roadmap` to `/dashboard` when they graduate?

**Comment by FarazA22** [comment]
@skeeJay No routing changes were made - when Poppy graduates, they will be routed from `/roadmap` to `/dashboard`.

**Comment by FarazA22** [comment]
@aaronvux Ready for review. Also, once the user closes the 'register now' toast, the registration card will always appear.

**Comment by aaronvux** [comment]
@FarazA22 This looks great!  @carye3 @fiorella-io @Jesslax Please review. 

The only thing that is a little weird is the For You card in mobile.  It's below the graduation button.  I thought we were changing the placement of this?

**Comment by fiorella-io** [comment]
@FarazA22 We need to add a border radius of 6px to the card and its shadow
![image](https://user-images.githubusercontent.com/91498500/167863632-1b09c218-94c6-4890-9f68-d09f2e8735ef.png)
![image](https://user-images.githubusercontent.com/91498500/167863691-55069852-4636-461d-b0da-13447079126c.png)

**Comment by fiorella-io** [comment]
@FarazA22 I've just updated the design links. There were not pointing to the final page. Can you adjust the content to match the new [Desktop link](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12037%3A233246)? The previous link had not been reviewed by Jess and Ce.

**Comment by fiorella-io** [comment]
@FarazA22 @aaronvux @carye3 Do we want to show both success registration messages?
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/91498500/167868059-ed94b112-7b7d-47e1-b3aa-a8c61acab89c.png">

**Comment by FarazA22** [comment]
@aaronvux Per the design, the sidebar content should render below the main content (similar to what happens on the dashboard). I noticed the content has changed. Wondering if the welcome content will stay the same for all Legal Structures? We currently have two different markdown files, one for GP/SP and one for all other legal structures. The content changes can be updated via the CMS, let me know who should make the updates.  

@fiorella-io I'd prefer using USWDS Utilities for styling. Could we apply a radius of 4px or 8px instead of 6px?

**Comment by fiorella-io** [comment]
@FarazA22 can we make sure the headings inside the cards are H3 for "Welcome", "Register to Save Your Progress" and "You're Registered!" so it's not the same size as "For You" for hierarchy.

**Comment by FarazA22** [comment]
@fiorella-io the welcome card is now available, can you check again. I also changed the h2 to a h3

**Comment by fiorella-io** [comment]
Looks good. Thank you so much! @FarazA22

**Comment by aaronvux** [comment]
@skeeJay @Jesslax are we good to move this to deploy?

**Comment by skeeJay** [comment]
@aaronvux @Jesslax It's okay with me.

**Comment by Jesslax** [comment]
LGTM
