### ISSUE TITLE
Move Registered Agent from Business to Contact Section in Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2557]
As Poppy, I need to have the Registered Agent information display on the Contacts section of formation so that logical information is grouped together.

## Acceptance Criteria
- Move all Registered Agent Functionality from the Business section to the Contacts section of Formation (see design)

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11856%3A227851

## Approvals
- [x] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@kmelefsky needs to be pointed at planning

**Comment by fiorella-io** [comment]
Looks good
