### ISSUE TITLE
Update "Open" Copy on Funding Tasks for Oscar to "Rolling Application"

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2567]
As Oscar, I need to understand that funding opportunities have a status of Open are actually Rolling Applications so that I don't get confused.

## Acceptance criteria
- Update "Open" copy to "Rolling Application" on the funding cards and tasks for Oscar

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Need to repoint at planning.

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review

**Comment by aaronvux** [comment]
@Jesslax please review
