### ISSUE TITLE
Design: industry-specific onboarding links

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2577]
/auto-fill Industry for onboarding: passing parameter from an industry-specific Landing Page

## Design Tasks
- [ ] All: Entry Points
  - Possible Locations
    - Navigator Landing Page? Maybe too crowded
    - B.NJ Homepage
    - B.NJ Industry starter kits
  - Styling
    - Link
    - Banner
    - Tile
- [ ] MVP
  - Remove industry dropdown from onboarding
- [ ] Post-MVP
  - Onboarding questions in sidebar
  - Get sent directly to roadmap

**Comment by carye3** [comment]
Per design review 5.2.22: this will be designed after / is dependent on Deferred Onboarding ("For You" sidebar) stories

**Comment by carye3** [comment]
@skeeJay @aaronvux fyi we agreed during design review to postpone this till after "deferred onboarding" stories (gradual graduation)

**Comment by Jesslax** [comment]
@carye3 this seems out of date, should we close?
