### ISSUE TITLE
Design: Profile Message for Uneditable Business Name

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2615]
As a generic user, if i want to edit my business name in my profile after forming my business, I need to know why it is uneditable.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/62653834/165826774-d891fa04-5c83-4e42-b38a-ebfe4c541103.png">

**Comment by Jesslax** [comment]
@carye3 has this been addressed?
