### ISSUE TITLE
Use municipality name (not displayName) for Members address in Business Formation

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#2636]
**Steps to Reproduce:**
1. Select "Hampton Borough  (Hunterdon County)" as your municipality
2. Go through business formation
4. Add a member, click checkbox for Use Business Address
5. See that the member address lists as "Hampton Borough  (Hunterdon County)" (this is wrong)
6. Try to submit
7. Get an error that the address city is longer than 30 chars

We should be displaying and submitted "Hampton" instead

**Comment by aloverso** [comment]
@aaronvux @Jesslax ready for review

**Comment by Jesslax** [comment]
![image](https://user-images.githubusercontent.com/78366346/166063446-721617bb-cb8d-4c03-a181-a1d318e911fa.png)
Should this just be displaying Hampton? Also would the same problem occur for Hampton Township and some of the other longer city names?

**Comment by aloverso** [comment]
it still displays the whole name, so that people know which one to select, but if you go to the Members modal, you'll see it autofills only as "Hampton"

**Comment by aaronvux** [comment]
@aloverso This is working for me.
