### ISSUE TITLE
Do not Display Reference Documents in Profile for SPs and GPs

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2649]
As Poppy with an SP or GP, I should not see the reference documents section in my profile so that I don't get confused.

## Acceptance Criteria
- Do not Display Reference Documents in Profile for SPs and GPs

## Approvals
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux this is ready for review
