### ISSUE TITLE
Spike: Make all Copy Searchable in Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2650]
As a Content Editor, I need the ability to search all copy in Netlify so I can work quickly.

## Acceptance Criteria
- Research making all copy searchable in Netlify.

**Comment by aloverso** [comment]
@aaronvux @Jesslax @CeciliaRam 

After some research, it's clear that this functionality isn't available from Netlify. So to complete the spike, I made a first attempt at writing our own search page that could take a query and direct you to the where you can find that text in the Netlify config and values.

Right now it only works for the "General Config" section but hopefully this is an example of what kind of thing we could build for Jess & Ce without too much pain. It took just an hour or so to put together. If it's useful, we could add a story to make it work across the rest of the Netlify content files.

The page is available at https://dev.navigator.business.nj.gov/mgmt/search with our usual admin password

![image](https://user-images.githubusercontent.com/6563663/171925994-f54d05c3-314c-4195-bca7-d27b6a48bd2b.png)

**Comment by aaronvux** [comment]
@aloverso Thanks!

**Comment by kmelefsky** [comment]
@Jesslax & @CeciliaRam review please

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam I used this yesterday and it was useful to me.  Please give your feedback.
