### ISSUE TITLE
Reorganize Cannabis Folders in Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2651]
As a Content Editor,  I need to have the Cannabis content reorganized so I can easily make updates.

## Acceptance Criteria
- All Cannabis Priority Status Task Content in one folder
- All Apply for Cannabis Conditional/Annual License Task in one folder

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by Jesslax** [comment]
Is it possible to put in their respective new folders the files in the task folder?

**Comment by aloverso** [comment]
@Jesslax sure, I can add the tasks to those folders. However, I can't remove them from the task folder, so they'll just exist in two places and you can edit them in either
