### ISSUE TITLE
Import NAICS Codes mapping to NAICS Code Name Description

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2680]
As a Navigator user, I need to have the NAIC Codes that are mapped to Name Description imported so I can easily understand what the codes represents.

## Acceptance Criteria
- Import mapped NAIC Codes with their NAIC Name Description
- Imported data is available for consumption and presentation in the Navigator and biz.nj
- Display the code and description on the NAICs code task.

## Approvals
- [ ] PO Approval

**Comment by Jesslax** [comment]
@mikewolfd is this all listed somewhere in netlify so I can easily double-check?
