### ISSUE TITLE
Redirect users back to their current page after they register

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2712]
As a Navigator user, I need to be redirected back to my current task page after I register on myNJ so that I land back on the page I was working on.

## Acceptance Criteria
- Redirect users back to their current page after they register leveraging the splash page

## Additional Acceptance Criteria

- 508 Compliant
- Follows Design
- Works in Mobile

## Design

- Desktop
- Mobile

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Create separate ticket for implementing a landing page in support of redirect for this ticket.

**Comment by mikewolfd** [comment]
Landing Page ticket?

**Comment by aaronvux** [comment]
dependent on splash page ticket.  #1739
