### ISSUE TITLE
Priority Status Selection Feedback

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2742]
As a Poppy, I need to know what characteristics of my business correspond to what priority status designations in order to understand what I'm eligible for.

## Acceptance Criteria:
- Display feedback bar when a checkbox is clicked.
  - Display all eligibility in single bar that corresponds to the checked boxes.
- Remove feedback bar if no checkboxes are clicked.

## Additional Acceptance Criteria
- Works in mobile
- 508 Compliant
- Follows Design

## Design:
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11477%3A181215
<img width="905" alt="Screen Shot 2022-05-11 at 11 11 58 AM" src="https://user-images.githubusercontent.com/62653834/167885017-c2350b10-eb4f-46e3-96b7-37d03017d917.png">

## Approvals
- [ ]  UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@aaronvux -- yep feedback appears as soon as checkbox clicked. There's only one alert bar  (see screenshot for when there are multiple eligibilities)

**Comment by aaronvux** [comment]
First three checkboxes map to Diversely-Owned Business, 4-6 checkbox map to Impact Zone Business and 2nd and 3rd to last checkbox map to Social Equity Business and the last checkbox does not see anything
