### ISSUE TITLE
Add Show More/Show Less Link to NAICS code recommendations larger than 10

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2748]
As Poppy, I need a consolidated list of NAICs code recommendation so I don't get overwhelmed.

## Acceptance Criteria
- Display a 10 recommendations and "Show More" link at the bottom of the list when more than 10 recommendations are being served.
- Clicking the Show More link will expand the list and display all recommendations with "Show Less" at bottom
- Clicking the Show Less link will collapse the list to 10 and display the Show More link.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by mikewolfd** [comment]
Designs?

**Comment by aaronvux** [comment]
@mikewolfd I thought we said we didn't need designs for this since they are just links

**Comment by aaronvux** [comment]
Needs design.

**Comment by dsueltenfuss** [comment]
@aaronvux should this be removed from pre-grooming until the designs are completed?

**Comment by aaronvux** [comment]
@carye3 are you or fiorella working on this one?
