### ISSUE TITLE
A/B Testing Analytics: Wrong Values Reported to Custom Dimension

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#2764]
Prospective and Existing values are getting reported along with the A/B testing custom dimension. 

Prospective and Existing values should not be reported alongside. 

<img width="903" alt="Screen Shot 2022-05-11 at 10 52 40 AM" src="https://user-images.githubusercontent.com/78366346/168136811-79efc027-423a-4dc9-a500-3c218407f67e.png">

**Comment by aloverso** [comment]
@skeeJay @Jesslax this should be fixed. For what it's worth, the "Prospective"/"Existing" values are just duplicates and can be safely ignored / deleted. The A/B breakdown is still accurate, we were just sending extra (incorrect) data here by mistake, but no data was getting lost or unreported.
