### ISSUE TITLE
Update Profile Box on Left Side of Poppy Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2818]
As a Poppy, I need a more streamlined Profile section on the Roadmap so I'm not overwhelmed with content.

## Acceptance Criteria
- Display business name as Profile link if the user is registered and has a business name saved to their profile, current date (Local NJ Date) on the right with ET designation
  - If user is in Guest mode, display "Guest Account" link & date 
  - If no Business Name exists and the user is registered, display "Business Profile" link & date 
- Remove Profile block
- Remove Copy block

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
**Poppy**
- Desktop - Registered
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12623%3A262580

- Desktop - Unregistered
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13498%3A177017

## Analytics
roadmap_profile_edit_button/click/go_to_profile_screen

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Spoke to EJ, split Oscar update to separate ticket.

**Comment by carye3** [comment]
We need to have slightly different copy for Guest Mode:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/62653834/170735468-6a9c53cf-269d-4264-9571-eb0a607cf190.png">

@CeciliaRam does this look good? Figma: [desktop](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13498%3A177017) and [mobile](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13502%3A176917)

**Comment by aaronvux** [comment]
@FarazA22
1. I'll update the AC to include the unregistered user.
2. I don't think we need to include the designator as we will only know if they go through formation.  
3. Reuse the roadmap_profile_edit_button analytics on the link.  Not sure about the return_to_onboarding.  I'll check it out.

**Comment by FarazA22** [comment]
@aaronvux Are we now using the 'ET' designation?

**Comment by aaronvux** [comment]
@FarazA22 ET.  Updated AC.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
LGTM. @carye3 @fiorella-io please review

**Comment by carye3** [comment]
lgtm! @aaronvux
