### ISSUE TITLE
Move Graduation Box into Sidebar

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2820]
As Poppy, I need to see the graduation card in the content column so I can easily graduate to Oscar when I'm ready.

## Acceptance Criteria
- Move graduation card into the content column
- Update styling and content (see design)

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12574%3A261495
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12612%3A262328

## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux pre-grooming note - Is there any desired order for these cards? Since we already pointed the "X% completed" story as well. Will this always display at the bottom or something?

**Comment by aaronvux** [comment]
Positioning can be moved by content administrators.
