### ISSUE TITLE
Update Industry Dropdown in Poppy Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2822]
As Poppy, I need a better experience when selecting my industry during onboarding so that I can move through the task quickly.

## Acceptance Criteria
- Display new industry field
  - Radio button scrollable list with five options visible
  - Display "All Other Businesses" as first option (special styling)
  - Search box: the list will update with matching options as the user types (same as current implementation)
  - Display (user value) falls under the industries below beneath the search field
  - Clicking anywhere in the list value will activate the radio button
  - Clear icon in search field?
  - Hover states in the list?
- After a list value is selected, display follow up question below the list.
- If the Next button is clicked without the industry field or follow up question selected, display inline error and snackbar
  - Industry is a required field. Please make a selection below.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12556%3A256304
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13085%3A264620

## Analytics
Time on task?
## Approvals
- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@carye3 @fiorella-io can you update the design for this please to show the All Available Businesses as the first option with special styling?  Separated by a line?

**Comment by carye3** [comment]
Designs updated @aaronvux 

@FarazA22 can you prioritize this update please?

**Comment by aaronvux** [comment]
@carye3 Thanks!  @FarazA22 this isn't in the current sprint, next one.

**Comment by carye3** [comment]
> @carye3 Thanks!  @FarazA22 this isn't in the current sprint, next one.

@aaronvux jess has said she wants this change done asap. Right @Jesslax ?

**Comment by aloverso** [comment]
@aaronvux pre-grooming notes: 
- what is the value of adding a radio button to a dropdown list? I've never seen a UI that combines these two elements into one. Can we clearly state the user value of adding this kind of complexity?
- I'm a little confused by "Clicking anywhere in the list value will activate the radio button and remove the other list options" - if we remove the other list options, how will a user change their selection?

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please see Anne's comment above.

**Comment by FarazA22** [comment]
@aaronvux 
Radio button scrollable list with five options visible - the height of the list dynamically changes based on height of the browser. I don't think we should change that behavior.

Display "All Other Businesses" as first option (special styling) - apart from special styling (bolded underline) this piece is done. There are some challenges/ high complexity with adding the bolded underline for a single list item. We want to push back on the design 

Display (user value) falls under the industries below beneath the search field - this is dynamic based on browser and location of input. The list will render within the viewport. What's the value in always having it below.

Hover State and clear functionality exist
