### ISSUE TITLE
Content: Consistent contextual information

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#2889]
In formation screen make the following words contextual information and work with dev to remove tool tip:

- Legal Structure
- "Business designator"
- Effective date

**Comment by CeciliaRam** [comment]
Contextual info has been created:
https://dev.navigator.business.nj.gov/mgmt/cms#/collections/contextual-information/entries/effective-date
https://dev.navigator.business.nj.gov/mgmt/cms#/collections/contextual-information/entries/business-designator
https://dev.navigator.business.nj.gov/mgmt/cms#/collections/contextual-information/entries/legal-structure-learn-more

will work with dev team next to replace tooltips for contextual info

**Comment by CeciliaRam** [comment]
Opened issue #2997 in delivery board for Dev (at Dev's request)
