### ISSUE TITLE
Content: Add new DOL funding programs to database

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#2892]
GAINS
PACE
YTTW

**Comment by kadamson-fearless** [comment]
@Jesslax all three projects are in review! all three don't have learn more links since dol hasn't updated any documentation for the grants

**Comment by Jesslax** [comment]
Great first pass @kadamson-fearless !

Note: We always spell out New Jersey

YTTW: 1) we need a link for what is a "registered apprenticeship" the first time we have it so users can easily figure out what that is, or contextual info if there is no good link
2) I don't think Trade Associations needs caps unless its a particular definition, in which case we need contextual information or linked to
3) Notice of grant opportunity - proper noun, needs a link or contextual info to explain what we are talking about.
4)in this case the benefit to the user is unclear, HOW MUCH can they get a grant for? is it reimbursable? so we will need to email the agency partner for more information. 

GAINS: 1) USDOL Registered Apprenticeship- needs link 2) we don't use punctuation at the end of bullet points (style guide things you'll learn over time.) 3) same comments about links as above 4) same comment about the benefits

PACE: 1) same points as above 2) lets sync on the description because I think opportunity to streamline some of the copy.

If there is any information you'd like to ask of DOL to help fill in blanks of information - email the list of questions and I will reach out.

**Comment by kadamson-fearless** [comment]
@Jesslax Looks like I found good links for everything and I got the grant $$ for each of the three programs.

**Comment by Jesslax** [comment]
Update: Waiting for feedback from Angie before publishing

**Comment by kadamson-fearless** [comment]
@Jesslax went ahead and updated with the info from Angie. Ready for review.

**Comment by kadamson-fearless** [comment]
GAINS published. 
Publish YYTW on Oct. 7
Publish PACE on Nov. 1

**Comment by Jesslax** [comment]
@kadamson-fearless looks like you can publish YYTW
You can close this tkt if all your information is up and ready to go.
