### ISSUE TITLE
Dakota - Remote Seller

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2913]
As Dakota with a Remote Seller Business, I need to be able to access the Navigator so that I can successfully operate in the State of NJ.

## Acceptance Criteria
**Update step 1 of Onboarding** 
  - Required Field Validation when clicking Continue button
  - 3 radio button options 
  - Starting a New Jersey-based business
  - A New Jersey business already up and running
  - A foreign (out-of-state) business starting in New Jersey
  
**Update step 2 of Onboarding**
 - 2 checkboxes
  - Required Field Validation when clicking Continue button
   - I have more than 200 separate taxable transactions in New Jersey in the current or prior calendar year
  -- Identifies user as Remote Seller
  - My taxable transactions in New Jersey exceeded $100,000 in the last calendar year
  -- Identifies user as Remote Seller
- Clicking either option displays the feedback snackbar with Remote Seller contextual link named "remote-seller".

**Skip to last step of onboarding**
- Once continue is clicked on Step 2, skip to last step of onboarding.

**REMOTE SELLERS ROAD MAP**
- Display only one step
- Hide Profile box.
- Modified Task: "Register-for-Taxes-foreign
- Modified Task: "Research-Insurance-Needs-Foreign"
- Do not display graduation card

**PROFILE**
- Display NJ TAX ID
- Notes section.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
**Desktop - Step 1**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12922%3A282414

**Desktop - Step 1 Snackbar**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11861%3A230517

**Desktop - Remote Seller/Workers Roadmap**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13038%3A269599

## Approvals

- [ ] Content Review
- [x] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@carye3 @fiorella-io @Jesslax we currently have an error message for Step 1 of onboarding, if they try to click Next without selecting an option: "Please select whether you have an existing business."

What should the error text change to, now that the question is different?

**Comment by fiorella-io** [comment]
@Jesslax @CeciliaRam Perhaps it should be more generic like "Please make a selection to continue"?

**Comment by aloverso** [comment]
@carye3 @fiorella-io are there designs for what the error looks like if the user tries to move past step 2 (the out-of-state business checkboxes) without selecting anything?

**Comment by fiorella-io** [comment]
@aloverso 
[Error when nothing is selected for step 2](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13646%3A173729)
<img width="668" alt="image" src="https://user-images.githubusercontent.com/91498500/171277133-b9f641f0-02fa-4e8e-aac6-4f23ee98f08c.png">

[Step 2 mobile](https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13646%3A174016)
<img width="258" alt="image" src="https://user-images.githubusercontent.com/91498500/171277770-1181b23e-34c3-41de-bbd4-72210e70160e.png">

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by fiorella-io** [comment]
Hi @aloverso, 

- [ ] Please make sure the content follows what's written in the story. I reviewed Jess's content changes, and she mentioned that she changed it in the AC. So, we've updated the design to match the AC.
<img width="825" alt="image" src="https://user-images.githubusercontent.com/91498500/171916103-c09cf6b2-8b19-467e-a631-fd5c3e041e82.png">

- [ ] I've updated the designs for the Remote Seller roadmap as well based on @Jesslax @CeciliaRam feedback. They gave us this feedback on Friday but I've just made the content changes yesterday. Sorry for that. 
They are all **content changes** only. Please make sure they match: Step title, description, and task names.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/91498500/171919186-97a26374-94f9-4366-bb08-2348e3d497a7.png">

**Comment by aloverso** [comment]
@fiorella-io these content changes have been fixed

**Comment by fiorella-io** [comment]
Thank you @aloverso! LGTM!

**Comment by aaronvux** [comment]
@Jesslax please review.

**Comment by Jesslax** [comment]
Nice work, looks great. I have some small copy tweaks I need to make, can do that today. The insurance task screen is displaying the wrong task, but I think I can change this as well. However the insurance task is also showing "loading task dependencies", which should not be happening, wonder if this will continue to happen after I swap the insurance tasks?
![image](https://user-images.githubusercontent.com/78366346/172159663-d1ead0bf-31e5-4af3-b1cc-4c9c4729846b.png)
AND not sure where we are with gradual graduation, but are we keeping the copy highlighted:
![image](https://user-images.githubusercontent.com/78366346/172159442-87137ac4-f67a-4b91-bbf1-1b2cc16e0051.png)
@aaronvux @aloverso

**Comment by aaronvux** [comment]
@Jesslax #2818 removes the copy from Poppy,  but need to confirm this change will also be applied to Dakota.
