### ISSUE TITLE
Dakota - Nexus

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2920]
As Dakota with a Nexus Business, I need to be able to access the Navigator functionality so that I can operate my business in the State of NJ.

## Acceptance Criteria

**ONBOARDING**
- Update step 2 of Onboarding
  - Part of my business operations takes place in New Jersey
  -- Identifies user as Nexus 
- Displays inline feedback alert for NEXUS with contextual link name: "nexus-business"
- Step 5 (Location): displays physical location question "Will you own or lease space in New Jersey?" first (with radio button response); if "yes" is selected, display in the roadmap all tasks associated with non-home-based business. If user responded "no", ask if they are a home based business, the user's answer to this does not impact the roadmap, it informs funding programs.
- Show location dropdown regardless (can use the information for funding programs).

**Dakota PERSONA LOGIC**
- Option 1 supersedes the selections below it (Nexus)
  - Dynamically displays feedback snackbar for Nexus Business when selected.

**Legal Structure**
- Display radio button of legal structures for Nexus businesses.
-- Required Field Validation when clicking Continue button

**NEXUS ROADMAP**
- For all Legal structures replace name search task with modified name search task
- For C-Corp/S-Corp display new "certificate-good-standing-foreign" task as step 2a
- For all Legal Structures display modified "register-for-State-taxes-foreign" task
- For all Legal Structures display modified "research-insurance-needs-foreign"
- Do not display EIN Task
- Do not display graduation card
- All Nexus Businesses will get DBA Resolution and Form Your Business Task

**NEXUS NAME SEARCH**
- Display modified Name Search Task
  - Utilizes current Name Search API and functionality
  - A successful name search provides the user with the legacy bulleted list Formation Task
  - Link to go back search name again
  - Save successful search value when user leaves the page and returns.
  -- Resets the user back to a Nexus Business, without DBA.
  - Failed Name search displays modified Formation Task for foreign businesses "form-business-entity-foreign" + dependencies: "certificate-good-standing" (if applicable) and "dba-resolution-foreign"
  -- Adds DBA Resolution Task to Roadmap and mini-Roadmap
  -- Leaving the DBA Name Search and coming back will continue to display the DBA Name Search functionality. 

**DBA NAME SEARCH**
- Display DBA Name Search Field
  - Utilizes current Name Search API and functionality
  - Failed search must search again (displays error with closely matching taken names)
  - Available name displays success message
  - Save successful search value when user leaves the page and returns.

**GET A DBA RESOLUTION TASK**
- Display DBA Resolution Task as 3a

**FORM YOUR BUSINESS WITH NJ TASK**
- Initially displays warning copy to complete name search for content to display
  - Display either legacy bulleted list or new DBA Form Your Business based on Name search results.
- Enable new indented design within task screen 
- Clicking Form My Business button displays Before you begin Modal
  - Clicking Download Form button opens the PDF in a new tab.

**NEXUS DEPENDECIES**
- Name search task: no dependency
- Formation task: doing business as, name search and resolution task (if resolution needs to completed)
- NJ Tax Reg: Formation

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design

**Desktop - Step 1**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12922%3A282414

**Desktop - Step 5 (Location)**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12834%3A249327
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12922%3A282687

**Desktop - Step 1 Snackbar**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11861%3A230517

**Desktop - Legal Structure**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11756%3A225878

**Desktop - C-Corp/S-Corp Roadmap**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13030%3A266879

**Desktop - Nexus Name Search**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=11787%3A226052

**Desktop - Name Search Failure**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12848%3A256123

**Desktop - Get DBA Resolution**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13038%3A267534

**Desktop - DBA Resolution - Form Business**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12652%3A264320

**Desktop - Download Form**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=13070%3A263173

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@aaronvux Jess and I just spoke and agree that if the user's original business name is available, then the "Get a DBA Resolution" task should just be removed from their roadmap

**Comment by aloverso** [comment]
@aaronvux a note for pre-grooming. When we last discussed this story, we (the devs) suggested removing the AC for adding the DBA task dynamically after the name search. Now the AC is to dynamically remove the DBA task instead. This will be functionally the same as dynamically adding it, in terms of complexity. Especially since with the AC around going back to the name search, it needs to get dynamically re-added to the roadmap anyways. We also thought more about it, and we think the complexity of dynamically adding/removing tasks should be manageable. With that in mind, should we go back to the paradigm of only adding the task if the user needs it?

**Comment by aloverso** [comment]
Also, it feels like there is missing AC here around the failed name search. Looking at the designs, if the name search fails, then we display a new text input field for DBA name search. What does this do? What API does it hit? Is there validation? Does it ever fail? What does it look like if it succeeds or fails?

**Comment by aloverso** [comment]
Also, could we have some more specific AC around the DBA name search? Especially since we don't have any designs for what it looks like if it succeeds or fails, it's helpful to have more specific wording and language there. When we say "Failed search must search again" - what does the "must" mean in this context? Are we stopping the user from doing something until they search again? What does the failure look like on the page?

"Available name displays success message" - do we need to save this to the user's profile? I don't see anywhere where it is needed to be displayed anywhere else in the app, like in any other tasks. So is it correct to assume we don't need to save it yet for now, at least until the profile story?

**Comment by carye3** [comment]
@aaronvux added change to location question in AC and associated figma link re: jess' comment

**Comment by Jesslax** [comment]
@aloverso based on your slack question, I updated the story with the following information: - 
Step 5 (Location): displays physical location question "Will you own or lease space in New Jersey?" first (with radio button response); if "yes" is selected, display in the roadmap all tasks associated with non-home-based business. If user responded "no", ask if they are a home based business, the user's answer to this does not impact the roadmap, it informs funding programs.
- Show location dropdown regardless (can use the information for funding programs).
cc: @aaronvux

**Comment by aloverso** [comment]
@Jesslax makes sense. only question is, when you say "show location dropdown regardless" do you mean - no matter whether they answer Yes or No to "Will you own or lease space in New Jersey?", or, whether they answer Yes or No to being a home-based business?

Also, we have existing logic for certain industries that can or cannot be a home-based business. How does that apply here?
