### ISSUE TITLE
Update Step Format and Styling on Poppy Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#3002]
As a Poppy, I need to have updated formatting and styling of the Roadmap so I can have a more pleasant experience.

## Acceptance Criteria

**Desktop**
- New icons for Plan & Start
- New font styling and size for Plan & Start
- New colors for numbers
- New font size for numbers
- New color for vertical lines below the numbers
- Create new h4 size of 18px.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12623%3A262580
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12638%3A263818

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Need to add design AC to this story.

**Comment by FarazA22** [comment]
Currently we use H2 headers for accordion titles (i.e. plan) and H3 headers for each roadmap step. Design no longer uses designated headers for text. Need clarification on hierarchy for everything that falls under My Tasks.
i.e.
My Tasks - H2
Accordion Sections - H3
Roadmap Steps - H4
