### ISSUE TITLE
Add List View & Toggle on Oscar Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#3013]
As Oscar, I need the ability to view my Calendar in a list view and toggle between list and calendar views so that I can customize my experience

## Acceptance Criteria
- Create gray box encapsulating the calendar.
- Default to List View?
- Remember selection between sessions.

**List View**
- Left- aligned green vertical bar
- Due Date
- Task Description (link to task page, if applicable)

**Toggle Button**  
- White Button with Calendar icon (default)
  - Clicking the button will display the calendar view.
  - Button transforms to White Button with List view icon
  - Clicking the button will display the list view.

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12556%3A262740
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12636%3A265672

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux should the My tasks section be removed from the designs?

**Comment by aloverso** [comment]
@aaronvux pre-grooming notes: are we certain there's value in "Remember selection between sessions." - this definitely would increase the complexity by a point or so, imo. Is this valuable to include in this story or could it be broken out or prioritized later?
