### ISSUE TITLE
Export funding programs from Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#3033]
As a Content Administrator, I need the ability to export funding programs in Netlify, so I can work more efficiently.

## Acceptance Criteria
- Create the ability to export funding programs from Netlify so that they are viewable in a table format.
- Each field should be their own column
- Manual request for script to be run to get the export file

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@Jesslax here's the funding program export story.

**Comment by dsueltenfuss** [comment]
@aaronvux funding export has been sent to @Jesslax 

Note to devs: running `yarn export:funding` in the web folder will regenerate the file
