### ISSUE TITLE
Enhancements to Opportunity Cards

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#3055]
As a user, I need to scan brief descriptions of opportunity cards, so that I can quickly assess which is right for me.

## Acceptance Criteria
- Opportunity cards should display a description of the opportunity and NOT display the content in the markdown file
  - In CMS, separate "content" input into "description (with character limits)" and "content"
  - Only display "description" input in Opportunity cards

Issue to Be Resolved: <img width="348" alt="167653744-c7a5afbf-eec5-4a4e-b068-c61ad3571189" src="https://user-images.githubusercontent.com/62653834/170552413-9e5166a5-b210-4d51-9ee4-562da728dc0c.png">

## Additional Acceptance Criteria

- 508 Compliant
- Follows Design
- Works in Mobile

## Design

- Desktop
- Mobile

## Approvals

- [ ] Content Review
- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@aaronvux this was created in response to this issue captured in Dev/Design Pairing:
<img width="348" alt="167653744-c7a5afbf-eec5-4a4e-b068-c61ad3571189" src="https://user-images.githubusercontent.com/62653834/170552573-0ce1db10-1d99-4622-b371-e919e2639972.png">
 
We'd like to prioritize it soon

**Comment by aaronvux** [comment]
@Jesslax @CeciliaRam please review this ticket.
