### ISSUE TITLE
Industry Dropdown: Changes to All Other Businesses option

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#3056]
We need to add a line below the "All Other Businesses" option in the industry dropdown list and make it the first option that appears. Original story: #2822 

Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12556%3A256304

Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12590%3A264149

**Comment by carye3** [comment]
@aaronvux this was split out from #2822 to be prioritized in this sprint

**Comment by FarazA22** [comment]
@carye3 @aaronvux  I spoke to the Dev team about this ticket. We are not able to introduce the horizontal line since this is an auto complete component. I'll work on updating the sort order so it displays `other businesses` first.

**Comment by aaronvux** [comment]
LGTM.  @carye3 are we doing the styling in another ticket?  I only see the All Other Business Options as the first value.
