### ISSUE TITLE
Content: Research advantages of starting a business in New Jersey

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#308]
Activities:
- add copy to dashboard landing page
- add content onto website in pending page: "https://docs.google.com/document/d/1vyDSzLVR7Se-6ghe1qO89bdADMFi8MlfPDPQV5A_Gnw/edit?usp=sharingWhy start a business in NJ"

**Comment by carye3** [comment]
Resource from Don: https://www.choosenj.com/new-jerseys-assets/
