### ISSUE TITLE
Design so people more easily see the chat

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#312]
Users did not know where to go if they had questions about the Navigator. When prompted on where they would go to get help, they said Google. Users did not see the chat feature at the bottom. When prompted to find the chat feature, they were able to find it.

Activities:

    Make it easier for people find the chat feature
    Explain how they can use/benefit from the chat feature

**Comment by skeeJay** [comment]
@Jesslax Can you expand on what user testing/anecdotal evidence is leading to this?

**Comment by Jesslax** [comment]
Users did not know where to go if they had questions about the Navigator. When prompted on what they would to get help, they said Google.  Users did not see the chat feature at the bottom. When prompted to find the chat feature, they were able to find it. 

Activities:

- Make it easier for people find the chat feature
- Explain how they can use/benefit from the chat feature
