### ISSUE TITLE
Design: Dakota improvements to Landing Page

### ISSUE THREAD

**Issue by fiorella-io** [newjersey/navigator.business.nj.gov#3163]

**Comment by carye3** [comment]
Discussion with Jess, Katie, Fiorella, and Kelsey during which we decided to put a pause on designs until Jess, Joe & Katie have decided how to structure the landing page @aaronvux @skeeJay

**Comment by carye3** [comment]
This includes whether to consider an objective-based theme instead of persona and feature-based as it is currently. Let me know if you'd like add anything @Jesslax
