### ISSUE TITLE
User Testing: Investigate if users are confused when following external link on B.NJ.gov, whether we need some kind of pre-leaving message

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#321]

**Comment by skeeJay** [comment]
@Jesslax Is this necessary if we implement #324? Feels like it would be overkill and make Business.NJ.gov more "government-feeling."

**Comment by Jesslax** [comment]
@skeeJay Good question. We can change this to a user testing story, see if we still need this after making the #324 update?

**Comment by skeeJay** [comment]
@Jesslax Sounds good, updated the title.

**Comment by aaronvux** [comment]
@skeeJay can we add this to a design milestone?  
"Help users understand when they are leaving biz.nj"

**Comment by skeeJay** [comment]
@aaronvux Done

**Comment by Jesslax** [comment]
Redundant with #171
