### ISSUE TITLE
Research: Database for financing programs for Business.NJ.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#323]
Activities:

1) Determining database categories
2) Determining maintenance schedule
3) What are best practices for displaying this content at other agencies?
3) Get agencies to input their data
4) Review data and edit program description
5) Get agency approval on more user friendly program description
6) conduct user testing with agencies
7)iterate

(Probably needs to be multiple tickets)

**Comment by skeeJay** [comment]
@Jesslax is actively working on this, so moving it to Getting Researched for accuracy.
