### ISSUE TITLE
Research: Best practices for banner bar for Business.NJ.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#327]
What "rules" should we have around a banner bar?
- what gets a banner bar?
- how long does a banner bar stay up to get extra foot traffic?
- what are best practices

**Comment by skeeJay** [comment]
@Jesslax Did we complete this?

**Comment by Jesslax** [comment]
@skeeJay by end of day

**Comment by aaronvux** [comment]
@Jesslax any update on the timeframe for leaving the banner bar displayed?

**Comment by Jesslax** [comment]
@aaronvux we have a draft ready to go, @carye3 when you can take a look, would be good to get your input: https://docs.google.com/document/d/1Eiumtmfnj0midbOwunFeY0-0ohQfICQdwM7ol0BFZkg/edit?usp=sharing

**Comment by Jesslax** [comment]
@skeeJay,  "features" section is ready for review: https://docs.google.com/document/d/1Eiumtmfnj0midbOwunFeY0-0ohQfICQdwM7ol0BFZkg/edit?usp=sharing
