### ISSUE TITLE
Content: Update Style guide Updates

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3284]
- Template the different screens and explain what goes where
- Explain use of contextual info vs. tooltip
- Funding: benefits: no bulletpoint unless more than 1 item
- Title Case Converter - resource
- Wiki Markdown guide on Github: add as resource (link)
- Yellow bars in the navigator (what are they called, Cary?) have punctuation (ends in period)
- License Requirement Logic: 1)individual licenses are required when the firm license requires them, 2)individual licenses are required when there is no firm license, and 3)the individual licenses are optional if the firm license does not require the owner to have individual license

**Comment by Jesslax** [comment]
@CeciliaRam is this done?

**Comment by CeciliaRam** [comment]
@Jesslax In progress-- I missed an item on this list.

**Comment by CeciliaRam** [comment]
all done! 
https://docs.google.com/document/d/1lXDOnmbUjc3esajgLX2FnnZhTFh7LJCbYi0uJvqKgSw/edit#
