### ISSUE TITLE
Business.NJ.gov: update design of Updates section

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#3289]
**As** a B.NJ visitor and business owner
**I need** a centralized place 
**so that** I find the information I need 
**and** stay up-to-date with new regulations for my business industry

## Testing (Current State)
- What's important to view at a glance? Eligibility? Benefits?
- Filtering: do these categories make sense? What would you like to see?

## Design
- Tiles / Cards
  -  IF expand /collapse isn't feasible, then...
    - Content limits for tiles / cards
    - Dedicated pages for full content
- Filter
  - Category copy 
- Additional Questions
  - See https://docs.google.com/document/d/1EyGP0qvTwbrBoTqjGOoo0Y8v6GjBQv2Jx5LEMGHOeBQ/edit# 
  - Is it clear what critical opportunities/laws that might impact their business right now
  - What are desirable filter categories for the user?
  - Industry
  - Type: Regulation, Funding
  - How would users like to sort an Updates article?
  - What is the right layout/framework of the Updates section?
  - How do we tell users there is new information on the site?	

## Notes
- Priorities:
  - Information in Updates also lives in Newsletter blasts. 
  - Do the filter categories make sense?
  - Should we update the tags? Do the current tags make sense?
  - What is being linked in the newsletter? Should all content have a dedicated page?
  - Should users be able to scan the content easily?  Some posts a longer than others.
- For later:
  - What would be the difference between content here vs Navigator?

## AC
- Consistent page behavior 
    - Some posts have a "Read more" link that opens to a new dedicated page that then has a "Learn More" link
    - Other posts have the full content description and only have a "Learn More" link

[Reference Document](https://docs.google.com/document/d/1EyGP0qvTwbrBoTqjGOoo0Y8v6GjBQv2Jx5LEMGHOeBQ/edit#heading=h.o93q3up97ij9)

## To Do
- [ ] Test Existing site for search & Updates

**Comment by fiorella-io** [comment]
I spoke to Joe and added more information
