### ISSUE TITLE
Update Search Page in biz.nj

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#3583]
## Acceptance Criteria
- Remo tabs from search results (FAQ and COVID)
- Remove Sort By component: always sorted by relevance
- Add pagination
- Move Ask NJ Expert to the Left to mobile and desktop
- Add Sign up to search results to desktop and mobile
- Update link colors

## Design

**Desktop**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=15846%3A242916

**Mobile**
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=15846%3A243073

**Comment by dltinnovate** [comment]
Ready for QA. Pushed live to the staging site. [https://beta.business.nj.gov/search-results?query=testing&filter=](https://beta.business.nj.gov/search-results?query=testing&filter=).
