### ISSUE TITLE
Content: Create contextual info for Gov2Go

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3705]

**Comment by CeciliaRam** [comment]
@Jesslax 
Contextual info ready https://dev.navigator.business.nj.gov/mgmt/cms#/collections/contextual-information/entries/gov2go

Can't publish until the cspell issue is solved, though. fyi

**Comment by Jesslax** [comment]
Thanks can you add:
1. link to give 2 go platform
2. explain who runs this site, and that it is a subcontractor of NJ Dept of Treasury? Want to make sure user knows that it is a reliable trustworthy site.

**Comment by CeciliaRam** [comment]
@Jesslax  all done
