### ISSUE TITLE
Design: Tax calendar flow before Up-and-Running

### ISSUE THREAD

**Issue by fiorella-io** [newjersey/navigator.business.nj.gov#3725]
Improve when the tax calendar arrives in user experience (potentially in phases earlier than Up-and-Running)

**Comment by Jesslax** [comment]
@fiorella-io @carye3 I need to sync with whoever picked this up. We did not have a chance to discuss the scope of this tkt/ideation.

**Comment by carye3** [comment]
we're not working on this yet, it must have been mistakenly prioritized in github @Jesslax

**Comment by Jesslax** [comment]
No problem, Ill add to milestones, thanks
