### ISSUE TITLE
Design: Improve NAICS code task to look similar to EIN/Tax ID tasks

### ISSUE THREAD

**Issue by fiorella-io** [newjersey/navigator.business.nj.gov#3766]
- Move the "Save NAICs Code" button next to the field. 
- Make success alerts similar. 
- Make designs similar.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/91498500/183510184-0971811a-cad1-4482-bf00-d944ed588a96.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/91498500/183510220-03e43347-1870-4712-a23c-d95016f79590.png">

**Comment by Jesslax** [comment]
@carye3 do you know if this still needs to get prioritized?
