### ISSUE TITLE
Content: Add logistics industry 1

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3813]

**Comment by CeciliaRam** [comment]
@Jesslax this is on the content site and can be reviewed.
We'll need an essential Q for this roadmap:
Will you be driving your commercial vehicle across state lines? 
_if YES: Add trucking-boc3, trucking-usdot, trucking-irp tasks
_if NO: show roadmap as is

**Comment by CeciliaRam** [comment]
V1 published - essential Q not implemented yet
