### ISSUE TITLE
Content: Add afterschool program industry 4

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3816]
This may not need to be a new industry, I think it can just be added to generic but need to double-check with Don

**Comment by CeciliaRam** [comment]
To confirm with Don:
After school can be a synonym added to the 2 Childcare roadmaps?

The why: an afterschool program doesn't need permitting if inside a school, and if it's outside a school it becomes a Daycare/ Family Daycare, it's just called "after school program"
