### ISSUE TITLE
Content: Add day care industry 3

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3819]

**Comment by Jesslax** [comment]
1) should they get the reseller task?
2) obtain a certificate of occupancy seems to be in the wrong location, should be somewhere in step 3?/replace the existing "Obtain Site Safety Permits" task? 
3) also home-based business q isn't being asked in the profile, which makes sense, but i am not seeing the place-based tasks and I should
4) this formatting looks weird, we should ask for the ability to have subullets -for dev/content pairing while Im out
![image](https://user-images.githubusercontent.com/78366346/187751392-24607b3c-7289-443e-b3a4-6dae0ee5f2dc.png)


@CeciliaRam

**Comment by CeciliaRam** [comment]
feedback incorporated into task
