### ISSUE TITLE
Content: add health care provider industry 6

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3821]
1. synonym PT, Dentist, Physician
1. Create a generic task that says Health care providers must be licensed that can be used for multiple types of 
2. JL  to add non-essential Q surgical center -> DOH license task

**Comment by CeciliaRam** [comment]
Roadmap is ready. Once we show Don we can close this ticket. 
Industry name: Healthcare

**Comment by Jesslax** [comment]
Looks good
- Should Doula be added to this?
- Can you look at our starter kit request sheet and see if there are any synonyms we are missing?
- If I was a business owner, I'd want to know the best way to affirm someone is licensed. Should they provide me with a certificate? Should I look up their license # in some database? Can we explain this to the business?
- Under "Licensing Requirements" I would include a sentence that says " All of the following professionals providing care will need a license from New Jersey's Department of Consumer Affairs. Each profession has their own specific board that they must have received certification. 
- Copy "All healthcare providers in your medical center need to be licensed medical professionals.Can we instead say "Any individual providing healthcare services in your..." i just want to make sure its super duper clear it's at the individual level
