### ISSUE TITLE
Content: Tax Contextual Information

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3898]
- [x] Short-period returns needs to CI. Notes: good example is a corporation originally filing calendar year and decided to switch to fiscal year, need to file for that in-between time. Update 3 tasks that use "short period returns" with CI.
- [x] CI: registered managerial member
- [x] Identify and list the following activities: Corporations that qualify as financial businesses are those which derive 75% of their gross
income from the financial activities enumerated at **N.J.A.C. 18:7-1.16(a)1 through (a)7,**, update the copy accordingly in detail screen cbt 100
- [x] Turn "conslidated return" into a URL: Taxpayers that file the TIR-100 and have multiple locations may request to file a consolidated return  and report sales for all locations under one federal identification number.
- [x] contextual info on extension time, explaining that payment of extension time is not allowed- needs it's own research
- [x] pte-100, find the URL and link "timely election form"
- [x] CI: Entire Net Income Your entire net income is the profit you earned from all sources of revenue minus any allowable deductions and taxes already paid. And link as needed.
- [x] Online  CI: online can either be electronic or online. Electronic filings done through third party. Anytime its online is it also electronic? what does electronic mean?

**Comment by CeciliaRam** [comment]
Re: Consolidated Tax Return for TIR-100. Looks like the request needs to be made in writing - added the info to AirTable
https://www.state.nj.us/treasury/taxation/motorv.shtml
