### ISSUE TITLE
content: review all tax detail screens

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3958]
1. review copy in the description section make sure it meets our styleguide
2. double check how all tasks look in the content site

**Comment by CeciliaRam** [comment]
Dev is working on this soon. Monday(?)

**Comment by Jesslax** [comment]
Items for review: 
1. Add CI for “short-period” when found
2. Consistent formatting of _(due..)_
3. Ensure periods are being constantly used throughout
4. Make sure “Form” is form
5. Consistency in styling of "Bullets" use
6. Review disposition of revenue, remove copy "disposition of revenue" when it’s there twice in header and body
7. Change agency to IRS for 1094 and 1095
8. If any content is confusing,  add questions to be sent to SME here: https://docs.google.com/document/d/1-KEzHIMNikFN-Lda7-9diYZein5X6EUZ-mKkG5rMS80/edit?usp=sharing
9. Ensure form copy has correct spacing
10. PTE 100- add url for BAIT and spell out acronym
11. In Millville tax there is reference to UZ-2 in tax rate - this either needs a link or contextual information
12. Consistency on when we reference the tax form name in description

**Comment by kadamson-fearless** [comment]
On CBT-100S & NJ-1065: spacing between Filing Method and the bullets looks HUGE
Should "taxable income" be CI? We define it on multiple entries. 

Otherwise - done and ones with changes are "in review" on netlify @Jesslax

**Comment by kadamson-fearless** [comment]
@Jesslax made updates to all but first two in netlify

**Comment by Jesslax** [comment]
1. please show us this issue Monday 16th minute - want Cary and Mike to see the design issue. Can you put a screenshot of it here.
2. our rule for CI is if we have it in our CI folder, link it upon first use in a task. 
3. Doesn't seem like you had any questions to add to google doc, if that's the case I will email the SME, please confirm.

**Comment by Jesslax** [comment]
@kadamson-fearless reviewed everything, please publish what has been moved to ready column. we can touch base tomorrow, to close out a few of the more tricky ones.

**Comment by kadamson-fearless** [comment]
@Jesslax done!
