### ISSUE TITLE
User Feedback Improvements

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4047]
## Questions for Users:
- Personalization
  - On a scale of 1-5, do you feel like your roadmap is customized to...
    - your business?
    - your industry?
    - your legal structure?
  - Describe your answer
- Current Notifications
 - What do you currently receive (tax deadlines etc)? How are the notification settings for this?
 - Adding notification setting from intercom to Navigator Profile

## Tactics for Gathering Feedback:
- Feedback button
- Specific tasks / phases
- Specific phases
- Based on persona / industry type / legal structure etc

**Comment by carye3** [comment]
@Jesslax adding potential new survey questions here for when we get around to it

**Comment by CeciliaRam** [comment]
@carye3 Is it a more general survey or do we have a "theme" for Qs?
If more of a general survey, I'd like to ask about content quality (easy to read, had the info they needed, etc.)

**Comment by carye3** [comment]
@CeciliaRam I renamed this task. We could just compile all our questions and then consider how they fit into a broader customer feedback strategy. 

EG we might decide that some of the questions shouldn't be part of the big ol' survey, they can be asked contextually (eg we ask it after completing a certain task), or with a specific persona
