### ISSUE TITLE
Adjust Pop-Up Survey Frequency

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4048]
Seems like this is popping up a bit too frequently, and it might disrupt users. Can we adjust?

**Comment by carye3** [comment]
fyi @Jesslax

**Comment by Jesslax** [comment]
@dltinnovate has this been addressed or do we need to prioritize it?

**Comment by dltinnovate** [comment]
@Jesslax we can close this. We've implemented the new survey system that addresses this issue.
