### ISSUE TITLE
Design: Dakota Graduation

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4069]
# Tasks
- [ ] Jess to review dakota testing protocol
- [x] Take screenshots of dakota (every sub-persona) ui across all phases
  - See if there are any inconsistencies in UX for Dakotas throughout the phases

# Notes
- Which Dakota users are allowed to graduate? Nexus
- Nexus skip certification but they can get funding
- Remote worker and seller: They would only need to see their taxes

# Draft User Stories
Given a Dakota Nexus has formed their business in NJ using a DBA (doing business as) name
When they open the “Needs to Register” modal
Then they will be requested to provide their DBA name instead of a business name

- Allow Dakota to graduate from phase to phase
- Only difference is if they have a DBA name, then the DBA name has to show on the modal

**Comment by fiorella-io** [comment]
@carye3 is this waiting for user research?
