### ISSUE TITLE
Content: Add Industry "Professional, Labor, and Political Organizations" 5b

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4073]

**Comment by CeciliaRam** [comment]
roadmap blocked until we develop service for non-profits.

Per Don:
- This roadmap would take the same steps as "starting a non-profit" roadmap
- The Election Law Commission will have additional requirements to turn into tasks
- Political organizations can be campaigns or PAC. The first endorses a candidate and has a fundraising limit, the other endorses an agenda/issue and has no fundraising limit
- Will need a task related to getting non-profit status with IRS for tax exemption purposes
