### ISSUE TITLE
Content: Add synonym to retailer: Clothing and Clothing Accessories Retailers

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4075]
1) Add to synonym to e-commerce "merchandise" "clothing" or something to that effect "retail" (consider adding retail to the description)  "electronics retail" "appliance retail" 
 2) Add synonym to retailer: "Clothing" "Clothing Accessories"

**Comment by CeciliaRam** [comment]
updates completed
