### ISSUE TITLE
Content: Add Industry: Investigation and Personal Background Check Services 5b

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4077]
license private detective agency - state police
-->need to double check

**Comment by CeciliaRam** [comment]
After a chat with Jess:
- Industry name: Private Detective
- Generic roadmap + 1 licensing task
- The licensing task will indicate: "staff providing services must be properly licensed as a private detective"

Jess will reach out the State Police to confirm that the only license available is at the individual level and not at the business level (private detective license vs. private detective AGENCY license or registration)

links to info:
state police: https://www.nj.gov/njsp/private-detective/index.shtml
PI application instructions: https://www.nj.gov/njsp/private-detective/pdf/sp-171-instructions_2020.pdf
PI application: https://www.nj.gov/njsp/private-detective/pdf/sp-171.pdf

**Comment by CeciliaRam** [comment]
Update:
We heard back from the State Police, but still have Qs. A call might be best. 
Drafting a doc with all our questions.
