### ISSUE TITLE
Content: double check style consistency for funding programs

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4125]
- add periods
- no fragments

**Comment by Jesslax** [comment]
@Jesslax hey ready for your review

**Comment by kadamson-fearless** [comment]
@Jesslax updated - mostly just fixing periods on a handful of bullets are adding punctuation to the benefits section as needed.

**Comment by Jesslax** [comment]
great, I do not need to double-check, please publish.

**Comment by kadamson-fearless** [comment]
@Jesslax done!
