### ISSUE TITLE
Content: add Electric Vehicle Tourism Program to funding content

### ISSUE THREAD

**Issue by kadamson-fearless** [newjersey/navigator.business.nj.gov#4207]

**Comment by kadamson-fearless** [comment]
@Jesslax - EVTP added to in review on netlify. Already sent along my clarifying questions. Unsure if we should add links/info that define the types of chargers (listed in benefit section)

**Comment by Jesslax** [comment]
@kadamson-fearless that all sounds good.

My only recommendation beyond the ones you came up with yourself--the eligibility criteria is reading more like evaluation process. Once BPU answers your questions, let's scrap and rewrite the eligibility criteria section- the point of this section is to help users quickly evaluate if they can apply to this program or not. Hopefully, their answer will give the information needed .

**Comment by kadamson-fearless** [comment]
@Jesslax made some changes. 

My thoughts in respect to the Tourism Areas definition: it might be better to define it with contextual information since no definition can be found directly on the site. It could basically give the same info as what he provided for eligibility and provide the link to show "examples". Thoughts?

**Comment by kadamson-fearless** [comment]
@Jesslax updated both the funding program and the contextual information. Both are "in review" for you 😄

**Comment by kadamson-fearless** [comment]
@Jesslax published and checked in content!

**Comment by Jesslax** [comment]
@kadamson-fearless we can close this tkt?

**Comment by kadamson-fearless** [comment]
@Jesslax yes!
