### ISSUE TITLE
Process Exploration: Story Mapping Template

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#433]
Hypothesis:

We believe that mapping user stories (in a story map) will help the team associate stories with the user's journey and plan delivery accordingly. We'll know this when we get positive feedback from the team on a conceptual story map.

**Comment by carye3** [comment]
@Jesslax since you're working on an iteration of this

**Comment by Jesslax** [comment]
[Initial draft in development](https://docs.google.com/spreadsheets/d/1TggmaCgmSUYSD6CtuGYtRtgtDSOwrrbqqDB7jQ6wdMw/edit?usp=sharing)
