### ISSUE TITLE
Content: Add disposition of revenues where missing.

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4359]
1. All the tax files have a placeholder for disposition of revenues
2. Not all tax files have a disposition of revenues content
3. research and add disposition of revenues information for all "relevant" taxes (not all taxes have disposition of revenues information easily available)
4. JL review once drafted.

**Comment by kadamson-fearless** [comment]
most descriptions are [here](https://docs.google.com/document/d/16p25AF6j7LhJtuaJ6JQYGopoGrIRzGCTqtjjybTu5ew/edit?usp=sharing). @Jesslax still working through remaining

**Comment by kadamson-fearless** [comment]
@Jesslax worked through remaining.

**Comment by Jesslax** [comment]
Great, only a few I suggest you add. please 1) add to netlify 2)publish and 3)make sure looks good on content site @kadamson-fearless  once you're done with that, please close this tkt.
