### ISSUE TITLE
Content: Identify Heading level 2 in webflow

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4382]
https://docs.google.com/document/d/1ekiWmYZcM6YBeMqHVuDoBxqqC-JbodylE6hKwSJjjV4/edit?usp=sharing

**Comment by Jesslax** [comment]
1. confirm what should be level header 2
2. jess review
3. discuss with joe implementation

**Comment by kadamson-fearless** [comment]
@Jesslax reviewed in full by me. Left some notes in the Google doc,  but otherwise all good!

**Comment by Jesslax** [comment]
@kadamson-fearless done reviewing, nice work!

**Comment by Jesslax** [comment]
@kadamson-fearless looks good, a few notes in there for you. I think now that we have these headers, we should check and give the headers style consistency (Title Case etc). and should add the new style to the styleguide. I think that would be a good next step.

**Comment by kadamson-fearless** [comment]
@Jesslax all items have been implemented except "Buy an Existing Business or Franchise" - left some notes in the doc for you to review

**Comment by Jesslax** [comment]
Awesome, responded to that. Did you change business structure to legal structure too? Can you remind me where that stands. Also are you saving everything from bablic before publishing, was that done already?

**Comment by kadamson-fearless** [comment]
I haven't changed to legal structure yet, we need to wait to see when dev can go ahead and change it on the navigator too so it all get changed on the same day. 

And I haven't published yet - just saved. But will be compiling the bablic today. @Jesslax

**Comment by kadamson-fearless** [comment]
Spanish has been copied over (https://docs.google.com/document/d/1A6p6BW1h5qBvKsldzBDvpG4LiFbicYHIc62m7T5KHjQ/edit?usp=sharing)
It's ready to publish whenever! @Jesslax

**Comment by kadamson-fearless** [comment]
Items have been completed, and Anna Melendez has been pinged about Spanish translations and sent the doc.
