### ISSUE TITLE
Content: SEO for templates on business.nj.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4439]
review four-page templates and provide recommendations for improving SEO

- pages
- licenses
- funding
- starter kits
- updates

**Comment by kadamson-fearless** [comment]
Provided initial suggestions/comments in Google Doc (https://docs.google.com/document/d/1TYBEkkpd1fhQ-n5fnsgyUbFoaqbJSPP1CgOA8Rmt1eU/edit?usp=sharing)
@Jesslax @dltinnovate

**Comment by kadamson-fearless** [comment]
@Jesslax @dltinnovate just waiting on review

**Comment by kadamson-fearless** [comment]
@Jesslax going to close this and we'll open new tickets for the items that came from review
