### ISSUE TITLE
Content: Add alt text copy on any image

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4475]
1. look into best practices - write out guidelines
2. add alt text copy

**Comment by kadamson-fearless** [comment]
@Jesslax[ doc is here](https://docs.google.com/spreadsheets/d/1QQBur8EslFpBnxziebAwimS0q_CTKLVdCZ9ZdnHu1-Q/edit?usp=sharing)

ready to implement, please inform next steps for implementation

**Comment by Jesslax** [comment]
Hey, dont have ability to edit this doc. I will put my comments here:

1. What does N/A mean in this context
2. A few of these have punctuation and a few don't, I think pick one, stay consistent
3. What is your suggestion for the yellow one? do they need new images?
4. #3 I'd remove "black" from this because it's the only instance where we include someone's race.

Next Steps 
1. need to figure out what to do with yellow and need to input in webflow - for both of these lets connect with Joe on slack.

**Comment by kadamson-fearless** [comment]
@Jesslax 1. n/a means that it gets no alt text. 2. best practices suggest that short phrases don't get punctuation while full sentences do. 3. the ones marked in yellow, the images don't appear correctly. I'll confirm with Joe, but yes they should be replaced if what I'm seeing is what the user is seeing.  4. done.
