### ISSUE TITLE
Content: create social marketing value prop doc

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4476]
Help build social media marketing case statement

1) potential benefits to obtaining users
2) information we can learn about our users

https://docs.google.com/document/d/1PEZoiZF2UKHQCi7FFQr23ck3wliqjawSGDRVuF4Nfsw/edit?usp=sharing

**Comment by kadamson-fearless** [comment]
@Jesslax have some initials notes in the [doc](https://docs.google.com/document/d/1PEZoiZF2UKHQCi7FFQr23ck3wliqjawSGDRVuF4Nfsw/edit?usp=sharing) (still noodling on goals) for you to review and see if we're on the right track/if it makes sense.

**Comment by Jesslax** [comment]
@kadamson-fearless headed in the right direction! My main suggestion is doing a bit of research to give concrete examples or data to back up your points of view.

**Comment by kadamson-fearless** [comment]
@Jesslax  made some updates regarding your comments

**Comment by Jesslax** [comment]
notes in the doc @kadamson-fearless

**Comment by kadamson-fearless** [comment]
@Jesslax updated
