### ISSUE TITLE
Design: Update all Profile Field Labels

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4546]
## User Stories

As a business owner, I need to consistently see all dropdown and text field labels on the profile page so I can enter or edit my information quickly??

## Acceptance Criteria

- Given I am a registered user or Navigator guest, 
when accessing the 'Business Information' and 'Reference Number' sections within my profile page
then the field labels are rendered per the new design with the existing information side modal hyperlinks.

# Designs
Reference Numbers (All) https://www.figma.com/file/Qs8qQrlVdl3ajcWpwcvnGP/44---50.-Navigator-Designs?node-id=19316%3A117174
Business Information (All): https://www.figma.com/file/Qs8qQrlVdl3ajcWpwcvnGP/44---50.-Navigator-Designs?node-id=19491%3A125259

**Comment by Jesslax** [comment]
@carye3 Can you add a sketch out of what the scope is for this when you have a minute?
