### ISSUE TITLE
Calendar: Event Clutter

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4550]
Problem: Users may be overwhelmed and deterred from using the calendar if it is cluttered. A large percentage of users will have at least 2 taxes every other month. 

Benefit Hypothesis: Upon reducing the number of viewable events users will be better able to find events, and will find the dashboard less overwhelming and usable.

Success Criteria
- We will know this when usability testing comparing the old design to the new design results in a majority of users preferring the new design (out of 5).
- We will know this when more folks are clicking on tax detail screens

Potential Scope:

- Users don't need to see more than 4 months ahead at a time
- Users should be immediately able to see at least 3 tax types within a month, and have the ability to see more if necessary
- Users can paginate ahead up to one year
- Ensure the calendar is accessible 
- Review existing patterns

Draft User Stories:
- Three Column Four Row Calendar View
- Calendar Month View More - View Less Events

Ideation:
https://app.mural.co/t/officeofinnovation7132/m/officeofinnovation7132/1658244433065/c88facbfbc669d46ed0835ccd089136a124905fa?sender=ua2d28992b36439ee4c7e5894

Feature Readiness Check List:
- [x] Create V1 designs based on ideation conversations (Thursday)
- [x] Get feedback on new designs at Design review (Tuesday)
- [x] Make updates based on feedback
- [x] Create figma prototype 
- [x] Write TryMyUI prompts and create space of analysis in Mural
- [x] Set up TryMyUI test and get approval from design team 
- [x] Launch TryMyUI test (Thursday/Friday)
- [x] Analyse results
- [ ] Share results at Dev Design review (Wed after demo)
- [ ] Make updates based on feedback (Tuesday afternoon)
- [ ] Move all designs into "Ready for content review" and tag Jess, Ce, and Kellie 
- [ ] Clean up Figma files and update Page status 
     - [ ] Include tab order

**Comment by dsullivan-fearless** [comment]
@Jesslax, I've added "Tax Type Calendar Tile Differentiation" to the scope.
