### ISSUE TITLE
Navigator Landing Page A/B Testing - Launch

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4570]
Tasks:
- [ ] Facilitate kickoff meeting
- [ ] QA the landing pages
- [ ] Create next steps ticket

**Comment by carye3** [comment]
@dsullivan-fearless was this prioritized for the next sprint?

**Comment by Jesslax** [comment]
@carye3 @dsullivan-fearless  Didn't Joe say this will be built by Friday? Where are we in the tkt with dev building it?

**Comment by dsullivan-fearless** [comment]
@carye3 @Jesslax apologies, yes -we have this dev ticket we created yesterday - https://www.pivotaltracker.com/story/show/183677276

**Comment by Jesslax** [comment]
Great and we have a story to build the actual landing page design?

**Comment by dsullivan-fearless** [comment]
@Jesslax yes - currently prioritized high on the backlog, likely implemented next sprint. 

- https://www.pivotaltracker.com/story/show/183443994
- https://www.pivotaltracker.com/story/show/183444029
- https://www.pivotaltracker.com/story/show/183444050

**Comment by Jesslax** [comment]
so @carye3 can you close this tkt? We also worked on next steps/other things we want to test.
