### ISSUE TITLE
CMS Backend Interface for Navigator (Internal)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#493]
As a content editor, I need an easy way to create content in GitHub in order to manage content efficiently while reducing errors.

#### Template for updating content & routing it to right location (sketches by Anne Loverso 9.20.21)
![image](https://user-images.githubusercontent.com/62653834/134372576-ab4357e3-8974-4ef3-99c9-28b0bf917648.png)

**Comment by carye3** [comment]
@CeciliaRam @Jesslax for now this would be a tool for internal content editors; what's a longer term vision for allowing agencies to edit content on Navigator?

**Comment by Jesslax** [comment]
@carye3 This is an important, but huge question. My understanding is that we don't want to prioritize the development of a long-term product maintenance plan yet. When we do, we'd probably want to start by talking to other states and learning from their approach. @skeeJay

**Comment by carye3** [comment]
Ok @Jesslax -- it sounds like there's a long-term vision for this and a shorter term one. In the short term, this could be very useful for content management internally. 

Discussed this yesterday with @CeciliaRam @aloverso and @mikewolfd; the latter two can speak to the functionality outlined in the images above which they think is feasible.

**Comment by Jesslax** [comment]
@carye3 totally, makes sense to address short term needs. Let's connect tomorrow or Friday so I can get a sense of what this is.

**Comment by skeeJay** [comment]
Based on our conversation yesterday, this is really more of an epic than a user story. Should we close this ticket now that we're including it in our epic AirTable? cc @carye3 @aaronvux @aloverso

**Comment by skeeJay** [comment]
@aaronvux I think we should probably delete this, since it's an epic instead. We may want to save the sketches though.

**Comment by aloverso** [comment]
I have a phone again so I could take better photos of the sketches if you like
