### ISSUE TITLE
Task Status Orientation in Roadmap (Main & Mini)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#517]
**As** Poppy
**I need to** have a clean interface that clearly shows the status of my roadmap tasks
**So that** I can 

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Designs

https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=4948%3A112982
![image](https://user-images.githubusercontent.com/62653834/138144715-b4757e3a-b2f1-4cfc-9b69-1c12fca408e1.png)

Mini roadmap
Roadmap

- [ ]

**Comment by aaronvux** [comment]
@carye3 I believe we already did this correct?
