### ISSUE TITLE
Determine best technology for user testing

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#525]
- a/b testing
- recruitment with business community
https://docs.google.com/spreadsheets/d/12Oz589T2ogotb1FCubb2r2_SIkVcT-iCefZYlSSYj6s/edit?usp=sharing

- [ ] Compile additional criteria and complete assessment of Usertesting.com platform
- [ ] Meet and complete final assessment & action items

**Comment by kmelefsky** [comment]
@carye3 checking in to see if there's any update here and if it's living in the right swim lane - thx!

**Comment by carye3** [comment]
lets keep it here or move it to Next Sprint @kelsey since this is dependent on #808 and #818

**Comment by aaronvux** [comment]
do we need to keep this ticket open?

**Comment by Jesslax** [comment]
@aaronvux did we decide on user testing software? Or is this a duplicate tkt?

**Comment by aaronvux** [comment]
we just started our trymyui.com trial, so we can leave this ticket for now.

**Comment by aaronvux** [comment]
Trymyui has been chosen.  Closing.
