### ISSUE TITLE
Snackbar displayed for unlocked tasks

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#566]
Given Viewing a task screen
When The status of a "parent" task has changed to "Completed"
Then A snackbar appears notifying the user that this task's "children" are now available.

per dev/des with Fiorella and Cary, on changing status to "Completed" it will:
- show ONLY the blue info snackbar (not the green snackbar)
- snackbar header is same as green ("Task Completed!")
- snackbar body displays unlocking info ("The following tasks have been unlocked... ")

**Comment by aaronvux** [comment]
@carye3 Is this ticket still valid?
