### ISSUE TITLE
Create a read me document for the Navigator

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#573]
## Goal: 

To track roadmap structures in a way that is easily understandable/editable to potential contributors, including contributors from specific agencies. 

## Attributes: 
1)identify if the industry has special descriptions and why they require a special description (onboarding) 
2)identify if the home based business question needs to be asked (onboarding) 
3) why that task appears in the roadmap (if it's due to industry, legal structure or home-based business) 
4) easy to distinguish tasks in the roadmap based on what agency might be responsible for managing it (i.e if I am Consumer Affairs, I would want to easily identify task screens that are relevant to me and what industries they relate to)

**Comment by CeciliaRam** [comment]
Draft content created. Shared with @Jesslax for feedback.

**Comment by CeciliaRam** [comment]
Doc: https://docs.google.com/document/d/1mTUZ42PahbTHX1Yy81dXVwHUlzYUjmMK2uN9PNAj4DU/edit#
moving ticket to backlog for now, per Jess.
