### ISSUE TITLE
Remember open/closed state of Steps in Plan/Start in mini-Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#587]
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by aaronvux** [comment]
@skeeJay I believe we've done this work.  I see it in dev.  Closing.
