### ISSUE TITLE
Consulting industry

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#598]

**Comment by kmelefsky** [comment]
@CeciliaRam checking in to see if there is any update on this story or if it can be closed. thanks!

**Comment by kmelefsky** [comment]
@Jesslax got it, sounds good! just wanted to make sure this wasn't forgotten about :)

**Comment by kmelefsky** [comment]
@Jesslax i'm going to rename this as a design ticket and move it into the backlog until the design gets prioritized
cc @skeeJay - do you want me to add this to the 28 milestone as a possibility?

**Comment by skeeJay** [comment]
@kmelefsky That's okay, not yet… in general, I don't think it makes sense to assign milestones until we do proper sprint planning.
