### ISSUE TITLE
Mini-Profile: Reformat Tax-related ID #'s after Entry

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#632]
Reformat #'s (including proper hyphenation) for the following numbers added in the profile page:
- [ ]  Employer Identification Number (input field)
- [ ]  Entity ID (input field)
- [ ]  NJ Tax ID (input field)

**Comment by aaronvux** [comment]
@carye3 do we still need this?

**Comment by aaronvux** [comment]
Closing.
