### ISSUE TITLE
Biz.NJ Homepage: Create Industry Section

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#653]
As a NJ Business Owner I need to be able view Industry information about my business so that I am able to make well informed decision.

## Acceptance criteria

- [ ] Side scrolling
- [ ] Alphabetical order
- [ ] Includes prompt to add your industry
- [ ] Desktop: Horizontal-scrolling tiles with scroll-right chevron advancing 3 tiles. Hide left-scroll chevron; upon scrolling right, display left-scroll chevron.

## Designs
[Homepage: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75320)
![image](https://user-images.githubusercontent.com/62653834/139759392-9918024a-d101-4405-b367-080af55e8346.png)

[Homepage: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6126%3A68946)
![image](https://user-images.githubusercontent.com/62653834/139759487-db83cc51-d488-4d5d-903d-ec35a608c963.png)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by dltinnovate** [comment]
@aaronvux 

Not built yet. Currently displaying the old resources section with an updated skin. Can built or add in next iteration.

![Screen Shot 2021-12-13 at 1 58 40 PM](https://user-images.githubusercontent.com/68555384/145871855-46fbaa63-cb66-4395-9e43-160aec8c2943.png)
