### ISSUE TITLE
CI Pipeline - Autocancel redundant builds

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#688]
We should cancel redundant builds on the main branch
Because there is no need to build previous commits to main, just the latest
We will be done when the builds automatically are cancelled

**Comment by aaronvux** [comment]
@aloverso @mikewolfd is this ticket still valid?

**Comment by aaronvux** [comment]
@dsueltenfuss is this ticket still needed?

**Comment by dsueltenfuss** [comment]
@aaronvux this is still an icebox issue for dev

**Comment by aaronvux** [comment]
@dsueltenfuss should we continue to hold this ticket on the board?

**Comment by dsueltenfuss** [comment]
I think this can be closed. We can also add a new one if needed.
