### ISSUE TITLE
Unable to navigate to the FIlings page within Cypress in CircleCi

### ISSUE THREAD

**Issue by FarazA22** [newjersey/navigator.business.nj.gov#715]
We should investigate why Cypress is not able to navigate to the filings page (only an issue within CI/CD) 

Before we add the filings page to the performance and accessibility test file.

Because checking the accessibility and lighthouse metrics will provide insights into performance / screen reader issues.

We will be done when we are able to get pa11y and lighthouse metrics.

----------
Notes: 

The test was working correctly in a local environment. 

Cypress tests include:
1) From the roadmap page, Cypress clickes the operate accordion to open it and clicking submit. The date of formation is already set to the current month.
2) After click, the calendar is expected to render, however, it does not. When watching the video, I noticed the accordion closes after the submit button is clicked. This is not the expected behavior either.
3) Once the filings page is rendered, Cypress should perform pa11y and lighthouse tests

![Performance and Accessability  all  -- Filings -- it should pass the audits (failed)](https://user-images.githubusercontent.com/72581979/138312490-5f986806-0197-4c0c-9138-77d1bb20ca40.png)

**Comment by dsueltenfuss** [comment]
@FarazA22 is this still an issue, since the fillings page no longer exists for the Poppy persona?

**Comment by FarazA22** [comment]
@dsueltenfuss Yes, we can close since it no longer exists
