### ISSUE TITLE
Criteria for when content is eligible for Navigator vs Biz.NJ

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#748]
**As** <PERSONA>
**I need to** clearly understand difference between Navigator and Biz.NJ
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by Jesslax** [comment]
duplicat eof #361
