### ISSUE TITLE
Design: Navigator UX Improvements

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#762]
## Priority Tasks
- [ ] Change input fields to match height of buttons (40px)
- [ ] URLs for all pages
- [ ] The problem of the "next/previous" buttons...
  - [ ] Option 1: Move the buttons elsewhere
  - [ ] Option 2: disappear the buttons when filling out a form
- [ ] Adjust inline error message. Font-size: 1rem, Margin: 8px 0px 0px
  ![image](https://user-images.githubusercontent.com/91498500/144509593-21623c5e-f997-4ba9-8c89-bb4cfc0e3f31.png) -> ![image](https://user-images.githubusercontent.com/91498500/144509559-48c3ac76-b707-46da-bb62-7c442be3dd1e.png)
- [ ] Provide more visual differentiation of contextual info links

## Potential Tasks
 - [ ] Redesign contextual menu link (dotted underline)
 - [ ] Section & Step Icon Redesign, Size & Color Adjustments: Adjust color of section icons to match NJ's dark green and reduce size of steps by 75% (currently competing in hierarchy with section icons. Redesign Section Icons (they are currently Noun Project).
  - [ ] Allow users to update task status on the roadmap?
  - [ ] Add explicit action to each task, such as "Mark as complete"
  - [ ] When forms are included in a task, the task status should auto change. If user wants to mark at as complete without completing the form, we should warn them but still allow them. (will there be any exclusions to this rule?) 
  - [ ] Hover states: Unchecked tasks within the mini-road do not change color on hover
  - [ ] Left-aligned task status
  - [ ] Content improvements
  - [ ] Selection border (accessibility)
  - [ ] Section Icons: sync with Biz.NJ
  - [ ] Bookmarks in mini roadmap / text running over
  - [ ] Rounded corners: text fields, location dropdowns, task windows, mini roadmap
  - [ ] Favicon [Added by E.J.]
  - [ ] Better selection for Industry dropdown… does it need a keyboard search as it gets longer? [Added by E.J.]
  - [ ] Welcome screen
  - [ ] Bookmarks - more visually distinct (in mini roadmap)
  - [ ] Spacing issues in mini roadmap
  - [ ] Business name check in profile
  - [ ] Business name check in onboarding
  - [ ] Primary button grey background 
![image](https://user-images.githubusercontent.com/62653834/142451737-a3b68434-862e-4267-b5a2-dfba6d5b5608.png)
  - [ ] Task Screen: Append "Next" "Previous" buttons with "...Task" 
  - [ ] Mark as Complete button

**Comment by skeeJay** [comment]
@carye3 @fiorella-io Can we add a Business.NJ.gov favicon to this? The Navigator actually still has a default favicon, which is not great.

**Comment by Jesslax** [comment]
@aaronvux @carye3 Are all these items still open?

**Comment by fiorella-io** [comment]
@aaronvux @carye3 These are still outstanding
