### ISSUE TITLE
Content: Add malpractice insurance

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#769]
Community Affairs Request:

Add malpractice insurance to the list of common types of insurance (required for a large number of licenses where the business could be very small, e.g., a speech pathologist who forms a company to take on a few clients as a side gig and should pay $50 a year for coverage)

1) Ask don what industries should have this added to their task screen
2) Perhaps need to make two insurance tasks and update all existing tasks that need to get the new task screen
3) Propose how this gets incorporated into the new roadmap template

**Comment by CeciliaRam** [comment]
Content has been created and reviewed by Jess. Needs Don's feedback on a couple of questions.
