### ISSUE TITLE
Content: Weekly Navigator Checks

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#798]
Check for dead links:
Check for underutilized files that can be archived: https://dev.d1fxpe8xsdfr62.amplifyapp.com/mgmt/deadlinks 
Add copy to Oscar: "If you don't know if you've registered, select no"

**Comment by Jesslax** [comment]
@CeciliaRam 
Only one item for you to do on here, in: /tasks/register-vehicle, the following link is not working and needs to be updated: https://www.nj.gov/mvc/pdf/about/ISM_SS-7.pdf

**Comment by Jesslax** [comment]
@CeciliaRam you can close this tkt once you swapped out the link.

**Comment by CeciliaRam** [comment]
link updated
