### ISSUE TITLE
Design: Redesign Beta Banner at the Top of the Navigator

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#822]
As Poppy, I need to be able to access a Navigator survey from the Banner bar so that I can easily give feedback about the application.

## Acceptance criteria
- Remove the highlighted BETA word.
- Link to feedback survey.
- review design update as necessary 

## Design
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109170

## Notes

- [x] UX Review
- [x] PO Approval

**Comment by carye3** [comment]
![image](https://user-images.githubusercontent.com/62653834/148788503-5940ea29-55c4-4f54-b0e2-ef23521932d2.png)
@aaronvux @fiorella-io 
this is i think the original intended design

**Comment by carye3** [comment]
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109170

**Comment by carye3** [comment]
@aaronvux latest design added above & ready for delivery board

![image](https://user-images.githubusercontent.com/62653834/151233553-2b8d3945-4db6-4038-adbd-f603f6d351e8.png)
