### ISSUE TITLE
Google Analytics Improvements

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#876]
As an Innovation team member, I need to be able to leverage specific data points in Google Analytics so that I can make better informed decisions.

## Acceptance Criteria

- Update Google Analytics with the Following data points:

**Pageviews**
- Arrival on Profile Screen
- Arrival on each Task/Filing Screen

**Events**
- landing_page_hero_log_in/click/go_to_myNJ_login
- landing_page_hero_get_started/click/open_create_account_modal
- landing_page_navbar_log_in/click/go_to_myNJ_login
- landing_page_navbar_register/click/open_create_account_modal
- landing_page_registration_create/click/go_to_myNJ_registration
- roadmap_profile_edit_button/click/go_to_profile_screen
- roadmap_PBS_link/click/go_to_PBS
- roadmap_footer_live_chat_link/click/open_live_chat
- roadmap_section/click/expand_contract
- profile_save/click/save_profile_changes
- profile_back_to_roadmap/click/view_roadmap
- tooltip/mouseover/view_tooltip

**Custom Vars/Dimensions**
- dimension6: “Persona”/[“Prospective”, “Existing”, etc]

**Additional**
Check that all contextual links are being tracked.
Check if tooltips are being tracked on each page.
Oscar onboarding tracking (possible different URLs)

https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

**Comment by skeeJay** [comment]
@aaronvux I am adding some landing page events to the spec that can be added as part of this ticket.

**Comment by skeeJay** [comment]
@aaronvux When we are supporting Oscars as well as Poppys, we should figure out how to track what phase each user is in via the analytics. I proposed a new custom dimension in the spec.

**Comment by skeeJay** [comment]
@aaronvux Do you think this could make it in to Next Sprint? I have suggested some additions, per the comments above, but I know you planned on doing a more comprehensive evaluation of what should get added to the spec/story.
