### ISSUE TITLE
Design: Display a Welcome Message after any user completes the Navigator Onboarding Process

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#881]
As a NJ Business owner, after I complete the Navigator Onboarding Process, I need to be a shown a welcome message on the Roadmap/Dashboard so that I can understand the value the Navigator provides me and my business.

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by Jesslax** [comment]
@aaronvux @carye3 has this need been validated by user testing at all? If not, can we add user testing label.

**Comment by aaronvux** [comment]
Yes, I believe this was based on testing feedback.
