### ISSUE TITLE
Allow Users to Opt out of the Newsletter and User Testing

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#883]
As a Navigator user, I need the ability to opt-out of the newsletter and/or user testing so I'm not receiving emails that I am not interested in.

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by skeeJay** [comment]
@kmelefsky So I know this was the mysterious disappearing ticket, but we should probably close/resolve this, since we built this function into the Navigator long ago, right?
