### ISSUE TITLE
Update the Industry Dropdown With Ability to Search/Filter Industry by Title and Description

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#884]
As a Navigator user, I need the Industry Dropdown to match the functionality of the Location Dropdown so that I can have a consistent experience.

## Acceptance criteria

- Update Industry dropdown to match the Location dropdown style.
- Searchable & selectable
- Searches industry title and description
- 508 compliant
- Works in Mobile

## Notes

- [x] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
autocomplete changing filtering: https://mui.com/components/autocomplete/#custom-filter

**Comment by aloverso** [comment]
@carye3 @fiorella-io currently, the industry dropdown has a separator line between the "generic" option and the rest of them. Do you want this to remain now that we're changing the component to a typeahead dropdown?

**Comment by aaronvux** [comment]
This looks good.  @carye3 please review

**Comment by carye3** [comment]
Deferring to @fiorella-io who led this design https://dev.d1fxpe8xsdfr62.amplifyapp.com/profile

**Comment by fiorella-io** [comment]
@dsueltenfuss 
Thank you, Dave. The design looks great! 
Two suggestions:
1.  When typing "Car" you don't see the "Auto-Body Repair" option. Perhaps we can change the description to add "car and vehicles" @Jesslax 
2. Typing "ecommerce" doesn't bring up E-Commerce"

**Comment by aaronvux** [comment]
Ready for Staging.  Creating a new ticket for synonyms and styling the "Any Other Business Type"
