### ISSUE TITLE
Left Align Task Status on Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#886]
As a Navigator user, I need to have a better visual representation of task statuses so that I can more easily comprehend what each status is.

## Acceptance criteria
- Left align the task status 
- Remove bullets
- All tags should be the same width
- Follow Design

## Designs
![Screen Shot 2021-11-05 at 1 16 25 PM](https://user-images.githubusercontent.com/36163601/140551677-01e94d7a-8894-4da0-836c-fe24b9d1c547.png)
[Desktop Figma link](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5136%3A116390
)

<img width="157" alt="Screen Shot 2021-11-22 at 3 23 54 PM" src="https://user-images.githubusercontent.com/72581979/142930075-b6c9f5c0-ba50-4d3b-9f1f-20db0e94c6aa.png">
[Mobile Figma Link](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6345%3A120494)

## Notes

- [x] UX Review
- [x] PO Approval

**Comment by FarazA22** [comment]
@aaronvux @carye3 @fiorella-io 
I thought about the fixed tag width issue a bit more. If we have a fixed size for all tags, we may run into issues with the tag component that is being used inside the filings calendar (i.e. annual report link) and how it behaves on different screens.

Perhaps we can make the fixed width an optional amount for tag components. If we go this route, we can dynamically decide when to apply it. Cary, I'd need to know the exactly number of pixels you'd want the width to be (let a comment in Figma design system).

**Comment by carye3** [comment]
@FarazA22 it looks like the fixed width is as follows: 
![image](https://user-images.githubusercontent.com/62653834/140993231-8a50ff5c-a667-4b32-ba3e-81e47a956e92.png)

and @fiorella-io they're now figma component variants

**Comment by FarazA22** [comment]
@aaronvux Ready for review. Note the styling within the task status dropdown on the task page was also updated.

**Comment by aloverso** [comment]
![image](https://user-images.githubusercontent.com/6563663/142681217-82cef766-4994-4342-b27e-d3675fb73bed.png)

just noticed this, is it supposed to wrap in the same column or like this?

**Comment by aaronvux** [comment]
I would think in the same column.  @carye3 please review.

**Comment by FarazA22** [comment]
@carye3 @fiorella-io can you attach a mobile design to this story. We may want to keep the bullets or have the status appear after. It does look a bit funky.

**Comment by fiorella-io** [comment]
Hi @FarazA22. I've attached the mobile designs. Let me know if you have any questions. :)

**Comment by FarazA22** [comment]
@aaronvux This ticket is ready for review.

**Comment by aaronvux** [comment]
This looks good.  @fiorella-io please review

**Comment by fiorella-io** [comment]
Looks good to me. Thanks @FarazA22

**Comment by aaronvux** [comment]
Moved to staging.
