### ISSUE TITLE
Gracefully handle an authentication error

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#904]
If something is broken with login, users see a terribly ugly AWS page instead of a useful error message

This should really never get shown to users, we should have a nicer error page to let them know something's wrong and they can't get in right now

![image](https://user-images.githubusercontent.com/6563663/140780224-7942c24c-b6b6-457d-bf00-840ef51392c8.png)

## Design
[Figma -- Error Msg](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9155%3A233595)

[Figma -- Page not Found](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=9155%3A233722)

**Comment by aloverso** [comment]
@carye3 @skeeJay @aaronvux thoughts?

**Comment by carye3** [comment]
Tagged for needing design @aloverso

**Comment by dsueltenfuss** [comment]
@aaronvux I think this should go to the Icebox for now
Its not something that occurs regularly, only if we have an AWS configuration error, and still needs further research into how much  custom layout we can actually implement for this page

**Comment by aaronvux** [comment]
@kmelefsky can we talk about this one at standup please?
