### ISSUE TITLE
Update Spinner on Buttons

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#907]
As a Navigator user, I need better feedback that the application is processing my request so I am well informed that an action is ongoing.

## Acceptance criteria

- Update Spinner on existing buttons that have the spinner.
- Follow Design

## Designs
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5842%3A106725

<img width="472" alt="Screen Shot 2021-11-08 at 1 32 36 PM" src="https://user-images.githubusercontent.com/36163601/140798078-03503762-fffa-4eb2-8228-684c320b9b4e.png">

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux I wanted to know if the loading interaction should be applied to every primary and secondary button across the app or if it applies to the task page.

**Comment by aaronvux** [comment]
I believe it was supposed to be applied consistently across the application, not just the task page, but @carye3 what were you thinking?

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
@carye3 please review.  Looks good to me.

**Comment by aaronvux** [comment]
@carye3 waiting for your review

**Comment by FarazA22** [comment]
@carye3 The spinner is not vertically centered across the application.

**Comment by aaronvux** [comment]
@FarazA22 this look centered to me now.  Was it updated?

**Comment by aaronvux** [comment]
Moving to staging.
