### ISSUE TITLE
Add Opt Out of the Newsletter when registering with myNJ 

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#925]
As a Navigator user who is registering in myNJ, I need the ability to Opt Out of the Newsletter & User Research so that I am not receiving emails I do not want.

## Acceptance criteria

- Add Checkbox to Opt Out of the Newsletter
-- Selected By Default
-- Copy: “I want to receive a weekly newsletter”
- Add Checkbox to Opt Out of User Research
-- Selected By Default
-- “I want to receive the Business.NJ.gov newsletter that shares pertinent regulations and resources relevant for my business”
- 508 compliant
- works in mobile

## Design
![image](https://user-images.githubusercontent.com/91498500/141189695-d8f3bb28-a096-48dd-9c71-f135d949a79b.png)
[Figma Link](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6130%3A111978)

## Notes

- [ ]

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please update the design and attach.

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by Jesslax** [comment]
@fiorella-io can you update the design to replace the following copy: "Please provide the..." with this copy: "We register businesses with my New Jersey (myNJ), a secure login platform run by the State of New Jersey. With your MyNJ login, you can use the Navigator along with any other online services you have registered for. Please provide your contact information below."
@aloverso does this need to a separate tkt to change out the copy at the top of this?

**Comment by aloverso** [comment]
@Jesslax you can change the copy anytime you like here's the file https://github.com/newjersey/navigator.business.nj.gov/blob/main/web/display-defaults/SelfRegDefaults.ts

**Comment by aloverso** [comment]
@Jesslax you can change the copy anytime you like, here's the file: https://github.com/newjersey/navigator.business.nj.gov/blob/main/web/display-defaults/SelfRegDefaults.ts

**Comment by Jesslax** [comment]
@aloverso cool, ill see if the pop-up box changes size with the new text.

**Comment by aaronvux** [comment]
This looks good to me.  @fiorella-io please review

**Comment by fiorella-io** [comment]
@aaronvux @aloverso 
Can we adjust the following:
- Making the spacing consistent with other input fields. Increase the space between the label and input field to 12px
![image](https://user-images.githubusercontent.com/91498500/141816600-cda73b2c-adad-4f9d-99e2-f010e666fc80.png)
- Can we add a close icon 
- Can we add the "I already have an account link". (do we need a story for this?)
- In the design I suggest to keep the placeholder text the same as the label to make it more clean. I think in instances where we have an input that can do a search, such as the Location field, we can add more descriptive placeholder text, for simple ones like this one we just keep the label and placeholder text the same. 

Gracias :)

**Comment by aloverso** [comment]
@fiorella-io for each of your points:
- for spacing, we can do this during des/dev pair or as a separate story. this story didn't cover anything to do with the input fields
- a close icon with its own behavior can be a separate story, it's not part of the functionality described for these checkboxes
- same with "i already have an account", that can be a separate story since that provides different value to the user than the checkboxes here
- sure thing, any of the copy on the page can be edited to whatever you like here: https://github.com/newjersey/navigator.business.nj.gov/blob/main/web/display-defaults/SelfRegDefaults.ts

**Comment by aaronvux** [comment]
Create two new stories for close icon and link in Next Sprint column

**Comment by aaronvux** [comment]
As a part of this ticket, a Navigator table was created to store the user preferences for the newsletter and user research.  The two additional services for the Granicus and Airtable query this table to populate each external source respectively.    Moving to staging.
