### ISSUE TITLE
Update the Navigator Database to Store Opt-Out Selections of Newsletter

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#926]
- If a user Opts in (checkbox is selected) to the newsletter, send contact information to Granicus.
-- Opt Out: Do not send any information to Granicus

**Comment by aaronvux** [comment]
@carye3 please attach link for the User Research Airtable that we can write to.

**Comment by carye3** [comment]
https://airtable.com/shraCkSHiknc9iHj8

lmk if i can share it with a specific airtable user @aaronvux

**Comment by aaronvux** [comment]
Closing and creating a ticket for Dave to track OIT firewall change for this to go live.
