### ISSUE TITLE
Content: Improve Register Your Business article on business.nj.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#928]
https://business.nj.gov/pages/register-your-business

1) Look at intercom to see what questions businesses usually have about business registration. 
2) Find the answers to these questions and incorporate them into the article
3) Consider ways it can provide more details/ information to support the Navigator's Step 3.
4) Update EIN section:
- article is a bit clunky should clearly say a)what is it, b) who needs it, c) who gets it, d)repercussions if you don't have it, e) how to get it, f) what you get after you register
5) Business Formation section:
- article is lacking some information, a)what is it, b) who needs it, c) who gets it, d)repercussions if you don't have it e) how to get it, f)what you get after you register

**Comment by CeciliaRam** [comment]
changes implemented in webflow
