### ISSUE TITLE
Make Entity ID Editable from the Operate Section after it has been successfully validated

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#943]
As a Navigator user, I need the ability to edit my Entity ID after it has been successfully validated in the Operate section of the Navigator so I can easily change my Entity ID if I have made a mistake.

## Acceptance criteria

- Display validated Entity ID
- Allow it to be editable
-- Display Entity ID in the input field that the user can update and resubmit.

**Comment by Jesslax** [comment]
@carye3 @aaronvux is this an issue in the current design?

**Comment by aaronvux** [comment]
I believe we can delete this since we are sending the user back to the Profile in the Oscar dashboard.
