### ISSUE TITLE
Semantic Release - Branch Issue

### ISSUE THREAD

**Issue by dsueltenfuss** [newjersey/navigator.business.nj.gov#950]
Research the branch issue with semantic release tagging

**Comment by dsueltenfuss** [comment]
Issue was related to rebasing the PR from the release branch back into main
Instead, it must be a merge PR, so that the commit ids don't change

Still investigating the issue with the skip ci in the release branch

**Comment by dsueltenfuss** [comment]
Yes, its still something I want to look into, at some point

**Comment by aaronvux** [comment]
@dsueltenfuss should we continue to hold this ticket on the board?

**Comment by dsueltenfuss** [comment]
Yea, I have not yet found a solution to the issue, but its also a minor issue
