### ISSUE TITLE
Investigate useSWR and caching, and its impact on state-caching for accordion changes

### ISSUE THREAD

**Issue by aloverso** [newjersey/navigator.business.nj.gov#976]
When onboarding is first completed for a new user, the sectionCompletion object is not created. Therefore, when the user updates the status of a task, the user data is not updated. Additionally, when the industry is changed within the user profile, the new roadmap is built, but a new section completion object is not created. Added logic to get and set section completion within profile and onboarding pages.

To test: Complete onboarding flow as a new user. Complete all the tasks within a section. The mini roadmap should update. Then navigate to the profile page to change the industry. After saving, return to the roadmap page to confirm the task statuses for relevant tasks are still present.

**Comment by FarazA22** [comment]
@aaronvux This ticket is ready for review. Let me know if you want to chat through test steps or need further clarification.

**Comment by aaronvux** [comment]
@FarazA22 does this have to be for a new user?  What about existing users?  Will this still be an issue for them?

**Comment by aaronvux** [comment]
this looks good to me.  moving to staging.
