### ISSUE TITLE
Add Close Icon to Navigator Registration

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#979]
## Designs
![image](https://user-images.githubusercontent.com/91498500/142888904-e1d0939c-e4b4-466b-bf60-22cef4f9abb1.png)
[Figma Link](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6130%3A111978)

## Notes

- [ ]

**Comment by aaronvux** [comment]
This looks good.  @fiorella-io please review.

**Comment by fiorella-io** [comment]
@aloverso @aaronvux Hi Anne is there any way we can align the close button to "Create account" to follow the design.
![image](https://user-images.githubusercontent.com/91498500/144619753-c6edcb16-9426-455d-847c-5b0d0858735d.png)
![image](https://user-images.githubusercontent.com/91498500/144619927-7c196839-aceb-40d1-95b3-ef4a099d8951.png)

**Comment by aloverso** [comment]
@fiorella-io sure, but just to let you know, it's currently positioned in the same place it is for the congratulatory modal, so moving it here will make our modal designs inconsistent. if that's what you expected, then I can make the change

**Comment by aaronvux** [comment]
Let's punt on this one so we don't cascade a change we haven't considered. Moving to staging.
