### ISSUE TITLE
Design & Test: MyNJ Login Post-Onboarding

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#999]
As a user, i need a streamlined and unintimidating onboarding experience in order to start using any tool.

Response to Google Analytics showing dropoff in users from onboarding process at the point of creating a MyNJ account.

**Hypothesis:** giving users a streamlined onboarding process and giving them a preview of the roadmap -- after which they are  prompted to add a MyNJ account to save that roadmap -- will increase number of users finishing onboarding

**Comment by aaronvux** [comment]
Marking as Delete.  Holding #1175
